### ISSUE TITLE
ModuleNotFoundError: No module named 'requests

### ISSUE THREAD

**Issue by jagonpe** [facebookresearch/demucs#101]
I'm working on a macOS Catalina. I've downloaded everything described but it struggles in the last   step. 

I run the command
python3 -m demucs.separate --dl -n demucs 
and the dragged the file, but the next error appears.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/javig/Desktop/demucs/demucs/separate.py", line 12, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

I don't understand about programming, so I'd like to be helped with "understandable" solution.

Thank you.

**Comment by adefossez** [comment]
Hey, can you run in the anaconda prompt:
```
conda activate demucs
pip install requests
```

**Comment by RaviFefar** [comment]
Error : `Traceback (most recent call last):
  File "liveness_certificate.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Requests is not a built in module (python installation does not come with), so you will have to install it:

`$ pip install requests`

![pip-install-requests](https://user-images.githubusercontent.com/50593606/95046563-09c27500-0702-11eb-8c47-e226db47cc2d.png)

**Comment by IrishAce** [comment]
> Error : `Traceback (most recent call last): File "request_test.py", line 4, in <module> import requests ModuleNotFoundError: No module named 'requests'`
> 
> Requests is not a built in module (python installation does not come with), so you will have to install it:
> 
> `$ pip install requests`

I have this issue, and the requests module is already installed. (see screenshot).
**So what is the next step?**
(I'm also a noob and have been trying to debug this issue for hours now.)

![Screenshot_2020-10-09_22-05-34](https://user-images.githubusercontent.com/72641344/95646234-36b4b600-0a7b-11eb-8fb5-7630abce8284.png)

**Comment by Faruk-F** [comment]
ModuleNotFoundError: No module named

**Comment by CarlGao4** [comment]
Please use `python3 -m pip install requests` instead.
