### ISSUE TITLE
how can I increase the audio quality/como se puede aumentar la calidad del sonido

### ISSUE THREAD

**Issue by pare1415** [facebookresearch/demucs#107]
Hello, thank you for the contribution.

I have run a few mp3s through the program and I would like to know if the audio quality can be increased.

Thank you very much in advance, greetings

hola, mil gracias por el aporte.

he pasado unos cuantos mp3 por el programa y me gustaría saber si se puede aumentar la calidad del audio.

Muchas gracias de antemano, un saludo

**Comment by adefossez** [comment]
Hey,
the quality is what it is, you can't get better separation with the current models. Maybe advances in my research in the future will lead to further improvement.

**Comment by pare1415** [comment]
hi, perfect...

thanks
