### ISSUE TITLE
Error whilst trying to separate song

### ISSUE THREAD

**Issue by OmegaT1** [facebookresearch/demucs#11]
I've tried to do this as perfectly as possible, however when I run the
`python.exe -m demucs.separate --dl -n demucs PATH_TO_AUDIO_FILE_1`
command, it outputs the following:
`Traceback (most recent call last):
  File "C:\Users\MYNAME\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\MYNAME\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MYNAME\Desktop\demucs-master\demucs\separate.py", line 13, in <module>
    import torch as th
ModuleNotFoundError: No module named 'torch'`

not really familiar with python so anything helps

**Comment by adefossez** [comment]
Do you have conda installed ? You can follow the instructions there [anaconda on windows](https://docs.conda.io/projects/conda/en/latest/user-guide/install/windows.html]). Then you need to start an anaconda prompt, navigate to the root of the demucs repository and run the commands given in the [requirements section of the README](https://github.com/facebookresearch/demucs#requirements).

**Comment by OmegaT1** [comment]
yes, I installed it, and I also ran the commands, the error shows after those.

I'll try uninstalling everything and doing it all over again

**Comment by OmegaT1** [comment]
After removing everything and starting back from the start I have noticed an issue on the cuda command

`(base) C:\Users\MYNAME\Desktop\demucs-master> conda env update -f environment-cuda.yml
Collecting package metadata (repodata.json): done
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.\
Examining scipy:  99%|████████████████████████████████████████████████████████████████▏| 74/75 [00:13<00:00,  2.05it/s]\failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package cudatoolkit conflicts for:
cudatoolkit=10.0
pytorch=1.3.1 -> cudatoolkit[version='>=10.1,<10.2']

`

**Comment by adefossez** [comment]
Hey @OmegaT1 , sorry for my late reply, I have updated the file `environment-cuda.yml`, it should work now :)
