### ISSUE TITLE
How to make size smaller? of the generated .wav files 

### ISSUE THREAD

**Issue by wubinbai** [facebookresearch/demucs#114]
Does anyone figure out how to make the size of  ~80MB of each .wav file smaller? For practical use, I think ~20MB for each .wav should be good enough.

**Comment by adefossez** [comment]
Add `--int16` flag to the command line. By default the code outputs waveform in float32 format, this will use the more standard int16 one which is twice as small :)

**Comment by wubinbai** [comment]
Great answer!!! And thank you so much! @adefossez 
But to improve more on reducing the size, any other methods to produce files that is of around the same size of the original file? Also, is there any reason that the generated file's size is pretty large ~100MB for a lossless music song? 


Result (using --int16):
adding --int16 on the command line halves the size of the generated files, which is great!

My example is from a 22M .flac, generate to four 38M .wav files.
Another example is from a 38M .flac, generate to 41M .wav files.

**Comment by adefossez** [comment]
You can output as MP3 using the `--mp3` file, it will encode at 320kbit which should be sufficient for most usage (especially given that the output of Demucs itself is not perfect, so there is not much point in doing lossless on it). There is no support for lossless compression of the output.

**Comment by wubinbai** [comment]
thanks! looks professional! @adefossez

**Comment by wubinbai** [comment]
@adefossez  Hi, actually, I tried using --mp3 flag, but there is no this kind of thing in the code /demucs/separate.py
