### ISSUE TITLE
demucs.separate: error: the following arguments are required: tracks

### ISSUE THREAD

**Issue by Nicko2679** [facebookresearch/demucs#117]
Después de solucionar varias faltas de módulos, me llega este error, estoy por tirar la toalla, ayuda por favor...por cierto estoy en Mac OS X 

Gracias

**Comment by adefossez** [comment]
What is the exact command you used ? It seems you are missing the name of the track to separate.

**Comment by Nicko2679** [comment]
Last login: Thu May 28 17:53:06 on ttys000
. /opt/anaconda3/bin/activate && conda activate /opt/anaconda3; 
(base) iMac-de-Javier:~ javierberrenderovegas$ . /opt/anaconda3/bin/activate && conda activate /opt/anaconda3; 
(base) iMac-de-Javier:~ javierberrenderovegas$ cd ~/demucs
(base) iMac-de-Javier:demucs javierberrenderovegas$ conda activate demucs
(demucs) iMac-de-Javier:demucs javierberrenderovegas$ python3 -m demucs.separate --dl -n demucs -d cpu/Users/javierberrenderovegas/Desktop/Aphonnic\ -\ Heroes\ -\ 02\ -\ Ahora\ que\ t.mp3 
usage: demucs.separate [-h] [-n NAME] [-Q] [-v] [-o OUT] [--models MODELS]
                       [--dl] [-d DEVICE] [--shifts SHIFTS] [--nosplit]
                       [--float32] [--int16] [--mp3]
                       tracks [tracks ...]
demucs.separate: error: the following arguments are required: tracks
(demucs) iMac-de-Javier:demucs javierberrenderovegas$

**Comment by Nicko2679** [comment]
> ¿Cuál es el comando exacto que usaste? Parece que te falta el nombre de la pista para separar.

Este es el comando que utilicé: 

(demucs) iMac-de-Javier: demucs javierberrenderovegas $ python3 -m demucs.separate - -dl -n demucs -d cpu / Users / javierberrenderovegas / Desktop / Aphonnic \ - \ Heroes \ - \ 02 \ - \ Ahora \ que \ t.mp3

y este el resultado:

uso: demucs.separate [-h] [-n NAME] [- Q] [-v] [-o OUT] [--modelos MODELOS]
[--dl] [-d DISPOSITIVO] [--shifts SHIFTS] [--nosplit]
[--float32] [--int16] [- -mp3]
pistas [pistas ...]
demucs.separate: error: se requieren los siguientes argumentos: tracks
(demucs) iMac-de-Javier: demucs javierberrenderovegas $

**Comment by rubencabrera** [comment]
Has escrito dos versiones del comando y ambas son algo sospechosas porque el último argumento es el nombre de la pista y el penúltimo es `-d cpu`. 

Lo que le sigue debe ser un espacio y a continuación la ruta al archivo donde está la canción. 

No uso MacOS, pero los espacios en una ruta, en caso de existir, deben ir precedidos del símbolo `\`. Sin tener ni idea del nombre del archivo ni de si `/Users` es la carpeta en la raíz de la que parte tu ruta, creo que te falta un espacio tras `cpu` en el comando:

`python3 -m demucs.separate --dl -n demucs -d cpu /Users/javierberrenderovegas/Desktop/Aphonnic\ -\ Heroes\ -\ 02\ -\ Ahora\ que\ t.mp3`

**Comment by Nicko2679** [comment]
> Has escrito dos versiones del comando y ambas son algo sospechosas porque el último argumento es el nombre de la pista y el penúltimo es `-d cpu`.
> 
> Lo que le sigue debe ser un espacio y a continuación la ruta al archivo donde está la canción.
> 
> No uso MacOS, pero los espacios en una ruta, en caso de existir, deben ir precedidos del símbolo `\`. Sin tener ni idea del nombre del archivo ni de si `/Users` es la carpeta en la raíz de la que parte tu ruta, creo que te falta un espacio tras `cpu` en el comando:
> 
> `python3 -m demucs.separate --dl -n demucs -d cpu /Users/javierberrenderovegas/Desktop/Aphonnic\ -\ Heroes\ -\ 02\ -\ Ahora\ que\ t.mp3`

Lo primero es darte las gracias por tomarte tiempo en responder, no estoy recibiendo demasiada ayuda y me gustaría poder lograr hacerlo funcionar muchísimo. He probado lo que dices y no debe ser ese el problema, además te permite arrastrar el archivo y automáticamente te guarda la ruta, con lo cual no entiendo por que me dice que faltan las pistas. Pero gracias igualmente, mira ...


(base) iMac-de-Javier:demucs javierberrenderovegas$ conda activate demucs
(demucs) iMac-de-Javier:demucs javierberrenderovegas$ python3 -m demucs.separate --dl -n demucs -d cpu\/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC\ HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic\ -\ Heroes\ -\ 06\ -\ Amore.mp3 
usage: demucs.separate [-h] [-n NAME] [-Q] [-v] [-o OUT] [--models MODELS]
                       [--dl] [-d DEVICE] [--shifts SHIFTS] [--nosplit]
                       [--float32] [--int16] [--mp3]
                       tracks [tracks ...]
demucs.separate: error: the following arguments are required: tracks
(demucs) iMac-de-Javier:demucs javierberrenderovegas$

**Comment by rubencabrera** [comment]
En el texto que estás pegando sigue sin haber espacio después de `-d cpu`

El 4 de junio de 2020 0:24:22 GMT+01:00, Nicko2679 <notifications@github.com> escribió:
>> Has escrito dos versiones del comando y ambas son algo sospechosas
>porque el último argumento es el nombre de la pista y el penúltimo es
>`-d cpu`.>
>> >
>> Lo que le sigue debe ser un espacio y a continuación la ruta al
>archivo donde está la canción.>
>> >
>> No uso MacOS, pero los espacios en una ruta, en caso de existir,
>deben ir precedidos del símbolo `\`. Sin tener ni idea del nombre del
>archivo ni de si `/Users` es la carpeta en la raíz de la que parte tu
>ruta, creo que te falta un espacio tras `cpu` en el comando:>
>> >
>> `python3 -m demucs.separate --dl -n demucs -d cpu
>/Users/javierberrenderovegas/Desktop/Aphonnic\ -\ Heroes\ -\ 02\ -\
>Ahora\ que\ t.mp3`>
>>
>Lo primero es darte las gracias por tomarte tiempo en responder, no
>estoy recibiendo demasiada ayuda y me gustaría poder lograr hacerlo
>funcionar muchísimo. He probado lo que dices y no debe ser ese el
>problema, además te permite arrastrar el archivo y automáticamente te
>guarda la ruta, con lo cual no entiendo por que me dice que faltan las
>pistas. Pero gracias igualmente, mira ...>
>>
>>
>(base) iMac-de-Javier:demucs javierberrenderovegas$ conda activate
>demucs>
>(demucs) iMac-de-Javier:demucs javierberrenderovegas$ python3 -m
>demucs.separate --dl -n demucs -d
>cpu\/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC\
>HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic\ -\ Heroes\ -\
>06\ -\ Amore.mp3 >
>usage: demucs.separate [-h] [-n NAME] [-Q] [-v] [-o OUT] [--models
>MODELS]>
>                      [--dl] [-d DEVICE] [--shifts SHIFTS] [--nosplit]>
>                       [--float32] [--int16] [--mp3]>
>                       tracks [tracks ...]>
>demucs.separate: error: the following arguments are required: tracks>
>(demucs) iMac-de-Javier:demucs javierberrenderovegas$ >
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/facebookresearch/demucs/issues/117#issuecomment-638511805

-- 
Esta es una cuenta de desarrollo, si recibes un mensaje inesperado, por favor, disculpa las molestias.
This is a software development account. If you received an unexpected or weird message, please excuse the inconvenience.

**Comment by Nicko2679** [comment]
> En el texto que estás pegando sigue sin haber espacio después de `-d cpu` El 4 de junio de 2020 0:24:22 GMT+01:00, Nicko2679 <notifications@github.com> escribió:
> […](#)
> > Has escrito dos versiones del comando y ambas son algo sospechosas porque el último argumento es el nombre de la pista y el penúltimo es `-d cpu`.> > > > Lo que le sigue debe ser un espacio y a continuación la ruta al archivo donde está la canción.> > > > No uso MacOS, pero los espacios en una ruta, en caso de existir, deben ir precedidos del símbolo `\`. Sin tener ni idea del nombre del archivo ni de si `/Users` es la carpeta en la raíz de la que parte tu ruta, creo que te falta un espacio tras `cpu` en el comando:> > > > `python3 -m demucs.separate --dl -n demucs -d cpu /Users/javierberrenderovegas/Desktop/Aphonnic\ -\ Heroes\ -\ 02\ -\ Ahora\ que\ t.mp3`> > Lo primero es darte las gracias por tomarte tiempo en responder, no estoy recibiendo demasiada ayuda y me gustaría poder lograr hacerlo funcionar muchísimo. He probado lo que dices y no debe ser ese el problema, además te permite arrastrar el archivo y automáticamente te guarda la ruta, con lo cual no entiendo por que me dice que faltan las pistas. Pero gracias igualmente, mira ...> > > (base) iMac-de-Javier:demucs javierberrenderovegas$ conda activate demucs> (demucs) iMac-de-Javier:demucs javierberrenderovegas$ python3 -m demucs.separate --dl -n demucs -d cpu\/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC\ HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic\ -\ Heroes\ -\ 06\ -\ Amore.mp3 > usage: demucs.separate [-h] [-n NAME] [-Q] [-v] [-o OUT] [--models MODELS]> [--dl] [-d DEVICE] [--shifts SHIFTS] [--nosplit]> [--float32] [--int16] [--mp3]> tracks [tracks ...]> demucs.separate: error: the following arguments are required: tracks> (demucs) iMac-de-Javier:demucs javierberrenderovegas$ > > -- > You are receiving this because you commented.> Reply to this email directly or view it on GitHub:> [#117 (comment)](https://github.com/facebookresearch/demucs/issues/117#issuecomment-638511805)
> -- Esta es una cuenta de desarrollo, si recibes un mensaje inesperado, por favor, disculpa las molestias. This is a software development account. If you received an unexpected or weird message, please excuse the inconvenience.

Gracias por tu tiempo, ese no debe ser el problema, esta preparado para arrastrar directamente el patch y lo hace automático, aun así es que lo copié mal, lo probé con lo que decias y lo he vuelto a hacer:

(demucs) iMac-de-Javier:demucs-master javierberrenderovegas$ python3 -m demucs.separate --dl -n demucs\/Users/javierberrenderovegas/Desktop/OXIGENO\ LJ\ OK.wav 
usage: demucs.separate [-h] [-n NAME] [-Q] [-v] [-o OUT] [--models MODELS]
                       [--dl] [-d DEVICE] [--shifts SHIFTS] [--nosplit]
                       [--float32] [--int16] [--mp3]
                       tracks [tracks ...]
demucs.separate: error: the following arguments are required: tracks

**Comment by Nicko2679** [comment]
Ese no debe ser el error, cuando copio y pego aqui me lo cambia, pero hice lo que decias del backslash, además si arrastras el archivo de audio te añadae la ruta el automáticamente. No sé como solucionarlo.

**Comment by rubencabrera** [comment]
Lamento no poder ayudarte mucho más porque no uso el mismo sistema operativo y no puedo reproducir el error en mi equipo. 

No obstante, el error que recibes parece constante en cuanto a que no estás pasando el último argumento requerido, que es el de las pistas. 

Una forma de eliminar problemas de rutas relativas o con caracteres que puedan provocar errores es copiar una canción al mismo directorio desde el que ejecutas la orden. Una vez la tengas ahí, cámbiale el nombre a nombre.mp3. Para asegurarte de que lo has copiado donde debes, al escribir el comando, en lugar de escribir ese nuevo nombre `nombre.mp3`, introduce las tres primeras letras (`nom`) y luego pulsa la tecla "TAB", eso debería autocompletar el fichero e indicarte que es la ruta que crees. Procura no copiar y pegar, escribe el comando a mano por si acaso.

**Comment by adefossez** [comment]
@Nicko2679 , puedes intentar utilisar el siguiente commando?
```
python3 -m demucs.separate --dl -n demucs -d cpu '/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic - Heroes - 06 - Amore.mp3'
```

**Comment by Nicko2679** [comment]
![Captura de pantalla 2020-06-08 a las 11 05 19](https://user-images.githubusercontent.com/66068261/84012563-08618580-a978-11ea-8c54-55b614f69613.png)

Se queda bloqueado no hace nada adefossez, gracias por intentar ayudarme, me encantaría poder ponerlo a funcionar, me serviría mucho.


> Lamento no poder ayudarte mucho más porque no uso el mismo sistema operativo y no puedo reproducir el error en mi equipo.
> 
> No obstante, el error que recibes parece constante en cuanto a que no estás pasando el último argumento requerido, que es el de las pistas.
> 
> Una forma de eliminar problemas de rutas relativas o con caracteres que puedan provocar errores es copiar una canción al mismo directorio desde el que ejecutas la orden. Una vez la tengas ahí, cámbiale el nombre a nombre.mp3. Para asegurarte de que lo has copiado donde debes, al escribir el comando, en lugar de escribir ese nuevo nombre `nombre.mp3`, introduce las tres primeras letras (`nom`) y luego pulsa la tecla "TAB", eso debería autocompletar el fichero e indicarte que es la ruta que crees. Procura no copiar y pegar, escribe el comando a mano por si acaso.

Igualmente no me ha funcionado, pero gracias.

**Comment by Nicko2679** [comment]
> @Nicko2679 , puedes intentar utilisar el siguiente commando?
> 
> ```
> python3 -m demucs.separate --dl -n demucs -d cpu '/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic - Heroes - 06 - Amore.mp3'
> ```

![Captura de pantalla 2020-06-08 a las 11 05 19](https://user-images.githubusercontent.com/66068261/84012909-8d4c9f00-a978-11ea-8713-c3b0c33ec1ed.png)

Se queda bloqueado no hace nada adefossez, gracias por intentar ayudarme, me encantaría poder ponerlo a funcionar, me serviría mucho.

**Comment by Nicko2679** [comment]
> @Nicko2679 , puedes intentar utilisar el siguiente commando?
> 
> ```
> python3 -m demucs.separate --dl -n demucs -d cpu '/Users/javierberrenderovegas/Dropbox/DROPBOX/APHONNIC HEROES/aphonnic_heroes_2013_descargaverkami/mp3/Aphonnic - Heroes - 06 - Amore.mp3'
> ```

Ha funcionado, pero ahora poniendo las comillas me sale esto para otro track en la misma carpeta, no lo he conseguido solucionar poniendo las "":

![Captura de pantalla 2020-06-08 a las 12 57 39](https://user-images.githubusercontent.com/66068261/84023189-eff96700-a987-11ea-9448-cc7e3df22321.png)

**Comment by adefossez** [comment]
@Nicko2679 , type the beginning of the command `python3 -m demucs.separate --dl -n demucs -d cpu ` **with a space at the end**, then drag and drop the file you want to separate. Don't add any quotes or anything like that (this message is for Windows users who often lack them but when you drag and drop on Mac OS X it will do the right thing).

The only problem with your initial command was the missing space between the command and the filename.

**Comment by Nicko2679** [comment]
You are absolutely right, I really appreciate your support
