### ISSUE TITLE
demucs.separate: error: se requieren los siguientes argumentos: pistas

### ISSUE THREAD

**Issue by Nicko2679** [facebookresearch/demucs#118]
Después de solucionar varias faltas de módulos, me llega este error, estoy por tirar la toalla, ayuda por favor ... por cierto estoy en Mac OS X, este es el comando utilizado:

(demucs) iMac-de-Javier: demucs javierberrenderovegas $ python3 -m demucs.separate - -dl -n demucs -d cpu / Users / javierberrenderovegas / Desktop / Aphonnic \ - \ Heroes \ - \ 02 \ - \ Ahora \ que \ t.mp3
uso: demucs.separate [-h] [-n NAME] [- Q] [-v] [-o OUT] [--modelos MODELOS]
[--dl] [-d DISPOSITIVO] [--shifts SHIFTS] [--nosplit]
[--float32] [--int16] [- -mp3]
pistas [pistas ...]
demucs.separate: error: se requieren los siguientes argumentos: tracks
(demucs) iMac-de-Javier: demucs javierberrenderovegas $

Gracias

**Comment by adefossez** [comment]
duplicate of https://github.com/facebookresearch/demucs/issues/117
