### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Alexxlml** [facebookresearch/demucs#119]
Hello, I decided to try demucs to separate some songs, I followed the instructions and configured it according to the repository instructions to work with GPU since I have a GTX1060.

The problem came after a song being separated with the help of Cuda, the memory was not released and shows me the following:
https://drive.google.com/file/d/18u5izPDvU5rTmKOPoZ8YvE1BI4wFhUo3/view?usp=sharing

**Comment by aufr33** [comment]
What options do you run demucs with? I just running demucs using the bat file:

> cd /d %~dp0
> python.exe -m demucs.separate -d cuda -n tasnet_extra --dl %1

**Comment by adefossez** [comment]
@Alexxlml  add `-d cpu` to the command line to use the CPU. You're GPU does not have enough memory.

**Comment by Alexxlml** [comment]
> ¿Con qué opciones ejecutas demucs? Acabo de ejecutar demucs usando el archivo bat:
> 
> > cd / d% ~ dp0 
> > python.exe -m demucs.separate -d cuda -n tasnet_extra --dl% 1

I use it with the following command line:
python.exe -m demucs.separate -d cuda --dl

**Comment by Alexxlml** [comment]
> ¿Con qué opciones ejecutas demucs? Acabo de ejecutar demucs usando el archivo bat:
> 
> > cd / d% ~ dp0 
> > python.exe -m demucs.separate -d cuda -n tasnet_extra --dl% 1

I use it with the following command line:
python.exe -m demucs.separate -cuda --dl
