### ISSUE TITLE
Some questions about Demucs  Speech Enhancement Model

### ISSUE THREAD

**Issue by RadioAngurem** [facebookresearch/demucs#124]
Hi, I've recently read your paper about Demucs applied to Spech Enhancement and I very eager to prove it.

Will you release  a Github repository soon?

Have you test the double lost function( L1 and spectogram) to train the MSS Demucs?.

Thanks

**Comment by adefossez** [comment]
Hey,
We are working on releasing the speech enhancement code. It will be a completely different repository.
We did not try the spectrogram loss for music source separation.

**Comment by RadioAngurem** [comment]
Thanks! I´ll be waiting because since Demucs code was published I though that it could be used to speech enhancement.

**Comment by listener17** [comment]
Enhancement model is basically same as the separation model. But, I didn't really understand the **intuition** behind the up- and down-sampling layers. Specifically this sentence:
"we noticed that upsampling the audio by a factor U before feeding it to the encoder improves accuracy. We downsample the output of the model by the same amount."

What is your intuition?

**Comment by LearnedVector** [comment]
@adefossez hey thanks for all the hard work on Demucs! I am also particularly interested in the speech enhancement code. Is there a rough eta?
