### ISSUE TITLE
I think I installed it wrong

### ISSUE THREAD

**Issue by hectormangas** [facebookresearch/demucs#13]
I've been trying for two hours and still get this error
Help please :(

```
(base) ecmac:demucs hectormangasafonso$ conda activate demucs
(demucs) ecmac:demucs hectormangasafonso$ python3 -m demucs.separate --dl /Users/hectormangasafonso/Downloads/malamente.mp3 
Traceback (most recent call last):
  File "/Users/hectormangasafonso/opt/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/hectormangasafonso/opt/anaconda3/envs/demucs/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/hectormangasafonso/demucs/demucs/separate.py", line 143, in <module>
    main()
  File "/Users/hectormangasafonso/demucs/demucs/separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "/Users/hectormangasafonso/opt/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/hectormangasafonso/opt/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/serialization.py", line 620, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 106623639 more bytes. The file might be corrupted.
libc++abi.dylib: terminating with uncaught exception of type c10::Error: owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /Users/distiller/project/conda/conda-bld/pytorch_1573049287641/work/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /Users/distiller/project/conda/conda-bld/pytorch_1573049287641/work/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 135 (0x117580517 in libc10.dylib)
frame #1: c10::intrusive_ptr<c10::intrusive_ptr_target, c10::detail::intrusive_target_default_null_type<c10::intrusive_ptr_target> >::reclaim(c10::intrusive_ptr_target*) + 264 (0x11baa5f48 in libtorch.dylib)
frame #2: THFloatStorage_free + 28 (0x11c34ea0c in libtorch.dylib)
frame #3: THPFloatStorage_dealloc(THPStorage*) + 18 (0x116a72532 in libtorch_python.dylib)
<omitting python frames>
frame #21: start + 1 (0x7fff669dd2e5 in libdyld.dylib)

Abort trap: 6

```

**Comment by adefossez** [comment]
Can you first delete the file `models/demucs.th` and try again ? I think you got an incomplete download of the pre-trained model.

**Comment by hectormangas** [comment]
Great! now it gets completed, but I don't know where the files have been created?

**Comment by hectormangas** [comment]
this is what i get:

```
python3 -m demucs.separate --dl -n tasnet /Users/hectormangasafonso/Downloads/malamente.mp3 
  0%|                                                                                                                             | 0/1 [00:00<?, ?it/s]ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with clang version 4.0.1 (tags/RELEASE_401/final)
  configuration: --prefix=/Users/hectormangasafonso/opt/anaconda3/envs/demucs --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mp3, from '/Users/hectormangasafonso/Downloads/malamente.mp3':
  Metadata:
    title           : MALAMENTE (Cap.1: Augurio) · ROSALÍA
    encoder         : Lavf56.19.100
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
  Duration: 00:02:29.68, start: 0.025057, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc56.21


```

**Comment by SantFdez** [comment]
> this is what i get:
> 
> ```
> python3 -m demucs.separate --dl -n tasnet /Users/hectormangasafonso/Downloads/malamente.mp3 
>   0%|                                                                                                                             | 0/1 [00:00<?, ?it/s]ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
>   built with clang version 4.0.1 (tags/RELEASE_401/final)
>   configuration: --prefix=/Users/hectormangasafonso/opt/anaconda3/envs/demucs --cc=x86_64-apple-darwin13.4.0-clang --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
>   libavutil      56. 31.100 / 56. 31.100
>   libavcodec     58. 54.100 / 58. 54.100
>   libavformat    58. 29.100 / 58. 29.100
>   libavdevice    58.  8.100 / 58.  8.100
>   libavfilter     7. 57.100 /  7. 57.100
>   libavresample   4.  0.  0 /  4.  0.  0
>   libswscale      5.  5.100 /  5.  5.100
>   libswresample   3.  5.100 /  3.  5.100
>   libpostproc    55.  5.100 / 55.  5.100
> Input #0, mp3, from '/Users/hectormangasafonso/Downloads/malamente.mp3':
>   Metadata:
>     title           : MALAMENTE (Cap.1: Augurio) · ROSALÍA
>     encoder         : Lavf56.19.100
>     major_brand     : mp42
>     minor_version   : 0
>     compatible_brands: isommp42
>   Duration: 00:02:29.68, start: 0.025057, bitrate: 192 kb/s
>     Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
>     Metadata:
>       encoder         : Lavc56.21
> ```

./separeted/

**Comment by hectormangas** [comment]
what do you mean?

**Comment by hectormangas** [comment]
the command? python3 `-m demucs.separate --dl -n tasnet`??

**Comment by SantFdez** [comment]
No, sorry. The files created are in ./separated/ directory

**Comment by hectormangas** [comment]
wonderful!!! thank you so much

**Comment by netoreto** [comment]
Hi, I am also stuck in
Metadata:
      encoder         : Lavc56.21
How did you solved that?
It could be because of my slow computer?

thanks!

**Comment by netoreto** [comment]
sorry, it was a matter of time, finally ended, 
thanks!

**Comment by adefossez** [comment]
Hey guys and sorry for my late reply. Glad everything worked out !
I have updated the instructions for Windows to make everything clearer (hopefully as I can't test it myself...), in case you have another problem ;)
https://github.com/facebookresearch/demucs/blob/master/README.md#using-windows
