### ISSUE TITLE
Use venv instead of anaconda

### ISSUE THREAD

**Issue by loretoparisi** [facebookresearch/demucs#131]
Is it possible to add support `venv` instead of `anaconda`?
Thank you.

**Comment by JeffreyCA** [comment]
FYI here's how you can setup `venv` yourself:

1. Create a `requirements.txt` at the project root directory with the following content:
    ```
    torch==1.4.0
    scipy==1.3.1
    tqdm==4.36.1
    lameenc==1.2.2
    musdb==0.3.1
    museval==0.3.0
    requests==2.22
    treetable==0.2.3
    ```
2. `python -m venv env`
3. `source env/bin/activate`
4. `pip install -r requirements`

This works for me for doing separation. If I missed any dependencies let me know!

**Comment by adefossez** [comment]
I'm closing this issue now, as there is official support for using venv, rather than anaconda, at least if you just want to do separation, not training :)

**Comment by loretoparisi** [comment]
Thanks! Any clue about this

https://github.com/xserrat/docker-facebook-demucs/issues/2#issuecomment-829528368

Thanks again!
