### ISSUE TITLE
Instrucción ilegal (`core' generado)

### ISSUE THREAD

**Issue by joseruizsoto** [facebookresearch/demucs#134]
Me sucede cuando ejecuto.

(base) jose@Cyberserver:~/demucs/demucs$ conda activate demucs
(demucs) jose@Cyberserver:~/demucs/demucs$ python -m demucs.separate --dl -n demucs -d cpu /home/jose/demucs/Audio/1.mp3
Separated tracks will be stored in /home/jose/demucs/demucs/separated/demucs
Separating track /home/jose/demucs/Audio/1.mp3
  0%|                                                                                      | 0/210 [00:00<?, ?seconds/s]Instrucción ilegal (`core' generado)
(demucs) jose@Cyberserver:~/demucs/demucs$ 

o

(base) jose@Cyberserver:~/demucs/demucs$ conda activate demucs
(demucs) jose@Cyberserver:~/demucs/demucs$ python3 -m demucs.separate --dl -n demucs -d cpu /home/jose/demucs/Audio/1.mp3
Separated tracks will be stored in /home/jose/demucs/demucs/separated/demucs
Separating track /home/jose/demucs/Audio/1.mp3
  0%|                                                                                      | 0/210 [00:00<?, ?seconds/s]Instrucción ilegal (`core' generado)
(demucs) jose@Cyberserver:~/demucs/demucs$ 

ya no se que hacer, ¿alguien que me pueda ayudar?, ¿que estoy haciendo mal?

**Comment by joseruizsoto** [comment]
Sigo con la duda

**Comment by adefossez** [comment]
Hola @joseruizsoto no puedo te ayduar porque no tengo Windows y es muy difficile reproducir el problemo que tienes.
Puedes intentar installar conda y demucs de nuevo

**Comment by joseruizsoto** [comment]
> Hola @joseruizsoto no puedo te ayduar porque no tengo Windows y es muy difficile reproducir el problemo que tienes.
> Puedes intentar installar conda y demucs de nuevo

Hola, gracias por responder, ya intenté instalar nuevamente todo pero el problema persiste, y yo tampoco tengo windows, tengo Ubuntu 20.04

**Comment by joseruizsoto** [comment]
Ya reinstalé, una vez mas, Anaconda y Demucs pero el problema persiste.

**Comment by joseruizsoto** [comment]
Por cierto instalé python 3.8.5, y tengo python 2 tambien y aun nada. Buscando en internet tambien intenté Downgradeando el Tensorflow y aún así me dice lo mismo, ya no se que hacer. Si me pueden ayudar estaría bastante agradecido.

**Comment by adefossez** [comment]
Puedes hacer:
```
sudo lshw | grep -i -A 3 -B 3 -i cpu
```
y digame el resultatdo?

**Comment by joseruizsoto** [comment]
> sudo lshw | grep -i -A 3 -B 3 -i cpu

tamaño: 64KiB     
          capacidad: 1MiB
          capacidades: pci upgrade shadowing escd cdboot bootselect socketedrom edd int13floppy1200 int13floppy720 int13floppy2880 int5printscreen int9keyboard int14serial int17printer int10video acpi usb ls120boot zipboot biosbootspecification
     *-cpu
          descripción: CPU
          producto: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
          fabricante: Intel Corp.
          id físico: 4
          información del bus: cpu@0
          versión: Pentium(R) Dual-Core  CPU      E5300  @ 2.60GHz
          serie: To Be Filled By O.E.M.
          ranura: PROCESSOR
          tamaño: 1197MHz
          capacidad: 4GHz
          anchura: 64 bits
          reloj: 200MHz
          capacidades: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx x86-64 constant_tsc arch_perfmon pebs bts rep_good nopl cpuid aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr pdcm xsave lahf_lm pti dtherm cpufreq
        *-cache:0
             descripción: L1 caché
             id físico: 5

**Comment by adefossez** [comment]
Yo pienso que tu CPU es demasiado viejo, pero no estoy seguro que es el problemo.
Se puede tambien intentar a installar pytorch 1.7:
```
conda activate demucs
conda install pytorch==1.7.0
```
Finalmente, se puede utilisar Demucs en google colab, con este notebook: https://github.com/facebookresearch/demucs/blob/master/Demucs.ipynb
En colab, https://colab.research.google.com/, se puede enviar tu mp3 en el notebook: https://colab.research.google.com/notebooks/io.ipynb?hl=es

**Comment by joseruizsoto** [comment]
> Yo pienso que tu CPU es demasiado viejo, pero no estoy seguro que es el problemo.
> Se puede tambien intentar a installar pytorch 1.7:
> 
> ```
> conda activate demucs
> conda install pytorch==1.7.0
> ```
> 
> Finalmente, se puede utilisar Demucs en google colab, con este notebook: https://github.com/facebookresearch/demucs/blob/master/Demucs.ipynb
> En colab, https://colab.research.google.com/, se puede enviar tu mp3 en el notebook: https://colab.research.google.com/notebooks/io.ipynb?hl=es

Bien intentare una vez mas, si no, tomare en cuenta lo de colab
