### ISSUE TITLE
Keep custom combination of parts

### ISSUE THREAD

**Issue by JeffreyCA** [facebookresearch/demucs#135]
I'd like to use demucs to remove only a particular part (like drums) from the original song, what's the proper way to do this?

Can I simply add up the value of `source` in the for-loop in `separate.py` for the parts I want to keep, or is there some other necessary clamping I should be aware of?

```py
for source, name in zip(sources, source_names):
            # Sum up 'source'
```

**Comment by adefossez** [comment]
I would do it just before this line https://github.com/facebookresearch/demucs/blob/dd7a77a0b2600d24168bbe7a40ef67f195586b62/demucs/separate.py#L209
For instance, to keep all the instruments and remove the vocal, add this line just before line 209:
```
sources[0] += sources[1] + sources[2]
```
Then the `drums.wav` file will contain everything but the vocals.

**Comment by JeffreyCA** [comment]
That works, thanks!

**Comment by JaeDukSeo** [comment]
amazing thanks!
