### ISSUE TITLE
Environment File Not Found

### ISSUE THREAD

**Issue by maghusg** [facebookresearch/demucs#14]
when i run
conda env update -f environment-cpu.yml

I get this message
EnvironmentFileNotFound: 'C: \ Users \ user \ environment-cpu.yml' file not found
 
I don't know anything about programming, even if the anaconda program I'm using is correct. I want to try this for my musical interests, so I would need some more advanced tutorial to run the program.

**Comment by adefossez** [comment]
Starting from the conda prompt, you should first navigate to the repository root using `cd PATH_TO_REPO`. Then you can run all the commands specified in the `README`.

**Comment by maghusg** [comment]
it says the system cannot find the specified path

**Comment by SantFdez** [comment]
> it says the system cannot find the specified path

In conda prompt you have to go to the directory where you downloaded the code. In my case is:
`C:\Users\UserJohn\Documents\Python Projects\demucs-master`

**Comment by maghusg** [comment]
```
C:\Users\usuario>python.exe -m demucs.separate --dl -n demucs PATH_TO_AUDIO_FILE_1 [PATH_TO_AUDIO_FILE_2 ...]
C:\Users\usuario\Anaconda3\envs\demucs\python.exe: Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')
```
now it says this

**Comment by adefossez** [comment]
@maghusg you need to go to the root of the demucs repository, most likely `cd demucs` in the Anaconda prompt. If this does not work, you can follow the updated instructions in the README and hopefully  that will work: https://github.com/facebookresearch/demucs/blob/master/README.md#using-windows

**Comment by supriya2691** [comment]
Hi, I am facing a similar issue. Can someone please look into it and let me know what should I do to resolve this?

##[debug]Evaluating condition for step: 'Install dependencies'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Install dependencies
##[debug]Loading inputs
##[debug]Loading env
Run conda env update --file environment.yml --name base
  conda env update --file environment.yml --name base
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib
##[debug]/usr/bin/bash -e /home/runner/work/_temp/343194be-ed[2](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:2)8-41a4-8c2b-6ca3b2491f6e.sh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python[3](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:3).12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main.py", line 8[4](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:4), in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main_env_update.py", line 88, in execute
        spec = install_specs.detect(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/specs/__init__.py", line 71, in detect
        if spec.can_handle():
           ^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 173, in from_file
        return from_yaml(yamlstr, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 139, in from_yaml
        data = yaml_safe_load(yamlstr)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/common/serialize.py", line 46, in yaml_safe_load
        return _yaml_safe().load(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/main.py", line 434, in load
        return constructor.get_single_data()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
        node = self.composer.get_single_node()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
        document = self.compose_document()
                   ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
        node = self.compose_node(None, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/parser.py", line 146, in check_event
        self.current_event = self.state()
                             ^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/parser.py", line [5](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:5)98, in parse_block_mapping_key
        if self.scanner.check_token(KeyToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 174, in check_token
        while self.need_more_tokens():
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 211, in need_more_tokens
        self.stale_possible_simple_keys()
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 3[6](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:6)0, in stale_possible_simple_keys
        raise ScannerError(
    ruamel.yaml.scanner.ScannerError: while scanning a simple key
      in "<unicode string>", line 2[7](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:7), column 1:
        https://repo.anaconda.com/pkgs/m ... 
        ^ (line: 27)
    could not find expected ':'
      in "<unicode string>", line 2[8](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:8), column 1:
        https://repo.anaconda.com/pkgs/r ... 
        ^ (line: 28)

`$ /usr/share/miniconda/bin/conda env update --file environment.yml --name base`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=/usr/share/miniconda
               CONDA_ROOT=/usr/share/miniconda
           CURL_CA_BUNDLE=<not set>
      DEPLOYMENT_BASEPATH=/opt/runner
        GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
              GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_0785b43c-5cf8-
                          4771-[9](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:9)22c-0e2e686082f2
          LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.[10](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:10).15/x64/lib
               LD_PRELOAD=<not set>
                     PATH=/usr/share/miniconda/bin:/opt/hostedtoolcache/Python/3.10.15/x64/bin:/
                          opt/hostedtoolcache/Python/3.10.15/x64:/snap/bin:/home/runner/.local/b
                          in:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer
                          /vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/loca
                          l/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lo
                          cal/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
        SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
            SSL_CERT_FILE=<not set>
               SWIFT_PATH=/usr/share/swift/usr/bin
           pythonLocation=/opt/hostedtoolcache/Python/3.10.15/x64

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : 
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.[12](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:12).4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.7.1=0
                          __glibc=2.35=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/share/miniconda/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/6.8.0-10[14](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:14)-azure ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
                UID:GID : 1001:127
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

**Comment by CarlGao4** [comment]
@supriya2691 Are you sure your problem has any relation to this project?

**Comment by supriya2691** [comment]
No, it's not related to this project. I am facing a similar issue and getting stuck. I came across this forum and thought of sharing my issue here. I will greatly appreciate it if you could help me resolve this error. Thank you!
