### ISSUE TITLE
Dockerize the Demucs environment

### ISSUE THREAD

**Issue by xserrat** [facebookresearch/demucs#159]
Hi,

I've created a repository to dockerize this environment in order to be executed in a more easy way. You can check it [here](https://github.com/xserrat/docker-facebook-demucs).

If you're interested in, I can create a pull request to integrate these changes in this repository.

Thanks!!

**Comment by adefossez** [comment]
Hey @xserrat, thanks :) I would rather link to your repo rather than integrating it here, if that is good with you?

**Comment by xserrat** [comment]
Hi @adefossez ,

Yes, of course! If you need, I can create the PR with the link.

Thanks :)

**Comment by adefossez** [comment]
I've added the link to the readme: https://github.com/facebookresearch/demucs/blob/master/README.md#running-in-docker
Thanks for your contribution!

**Comment by xserrat** [comment]
Nice! Thank you so much to add it :)
