### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by xZlic3x** [facebookresearch/demucs#16]
I get this error nonstop. After I figured a lot of things, I could use it but I keep on finding this and I'm confused. I know little to no code.

`Traceback (most recent call last):
  File "C:\Users\kreme\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\kreme\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kreme\Anaconda3\envs\demucs\separate.py", line 17, in <module>
    from .audio import AudioFile
ImportError: attempted relative import with no known parent package`

Why could this be? Any solution?

**Comment by rokimoki** [comment]
Which command are you executing?

**Comment by xZlic3x** [comment]
This is the full command and the results:

`(demucs) C:\Users\kreme>python.exe -m separate --dl -n "C:\Users\kreme\Desktop\eeee\Luminous Avenger iX Music Video IGNITER.wav"
Traceback (most recent call last):
  File "C:\Users\kreme\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\kreme\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kreme\Anaconda3\envs\demucs\separate.py", line 17, in <module>
    from .audio import AudioFile
ImportError: attempted relative import with no known parent package`

I tried with .mp3 and .wav extensions on file
Also, if I tried to literally use the code provided, this happens:

`(demucs) C:\Users\kreme>python.exe -m demucs.separate --dl -n demucs "C:\Users\kreme\Desktop\eeee\Luminous Avenger iX Music Video IGNITER.wav"
C:\Users\kreme\Anaconda3\envs\demucs\python.exe: Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')`

**Comment by rokimoki** [comment]
I saw that common error in other issues, but I don’t know the fix.

If you installed anaconda x64 for python 3.7, installed the dependencies and activated the environment, I don’t know whats wrong.

**Comment by adefossez** [comment]
@xZlic3x you need to run the commands from the root of the repository. Most likely you need to first do `cd demucs` and then it should work :)

**Comment by adefossez** [comment]
Sorry for my late reply btw!

**Comment by xZlic3x** [comment]
`(base) C:\Users\kreme>cd demucs
El sistema no puede encontrar la ruta especificada.`

This happens. How do I run commands from the root of the repository? It's a dumb question.

**Comment by rokimoki** [comment]
> `(base) C:\Users\kreme>cd demucs El sistema no puede encontrar la ruta especificada.`
> 
> This happens. How do I run commands from the root of the repository? It's a dumb question.

Lo que se refiere, es que debes estar ubicado en el directorio raiz de la carpeta donde están los ficheros de `demucs`, para ello debes abrir la consola de anaconda, activar el entorno demucs, situarte en la carpeta (con el comando `cd`) y ejecutar el comando para separar las pistas.

Puedes saber la ruta si abres la carpeta con el explorador de windows, y arriba en la barrita de url tipo navegador, si haces click puedes ver la dirección, pones en la consola de anaconda, `cd esa-direccion` y tendría que ubicarte en la ruta.
