### ISSUE TITLE
ConvTasNet has no attribute samplerate

### ISSUE THREAD

**Issue by musicbby** [facebookresearch/demucs#163]
So this week when I did the "!python -m demucs.separate --dl -n tasnet_extra /content/" step,  I got a random message saying: 

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/demucs/demucs/separate.py", line 226, in <module>
    main()
  File "/content/demucs/demucs/separate.py", line 203, in main
    wav = AudioFile(track).read(streams=0, samplerate=model.samplerate, channels=model.audio_channels).to(args.device)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'ConvTasNet' object has no attribute 'samplerate'

I have absolutely no experience in programming, so I'm not sure what this message means. But when I tried demucs about 2 weeks ago, it worked. I'm not sure how to fix this, please help!

**Comment by adefossez** [comment]
Sorry, could you update the repo and try again ?

**Comment by musicbby** [comment]
How do you update the repo? (I'm using the Google Colab version)
https://github.com/dvschultz/ml-art-colabs/blob/master/Demucs.ipynb
https://colab.research.google.com/github/dvschultz/ml-art-colabs/blob/master/Demucs.ipynb

**Comment by musicbby** [comment]
My bad! I didn't know you had to download the repo in the first place, it works now. Thanks!
