### ISSUE TITLE
error: unrecognized arguments: - - dl

### ISSUE THREAD

**Issue by Sammy0427** [facebookresearch/demucs#173]
## ❓ Questions

(Please ask your question here.)
![16206189820611838588560881798274](https://user-images.githubusercontent.com/83936561/117603958-dde4f300-b119-11eb-9ee4-a32afdb50854.jpg)
I'm having this issue

**Comment by Daniel-Ventura81** [comment]
same here!

**Comment by adefossez** [comment]
The `--dl` flag is no longer used since the last version. See `https://github.com/facebookresearch/demucs/blob/master/docs/windows.md` for up to date instructions.
