### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured

### ISSUE THREAD

**Issue by juliocamarero** [facebookresearch/demucs#18]
I have tried to run this in 2 different laptops (both are MAC) and I always get the same error when executing: `conda activate demucs`

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

```

I have run `conda init bash` since I am using bash, and open a new terminal.
In the new terminal, running the init command shows that I don't need any other change:

```
no change     /usr/local/anaconda3/condabin/conda
no change     /usr/local/anaconda3/bin/conda
no change     /usr/local/anaconda3/bin/conda-env
no change     /usr/local/anaconda3/bin/activate
no change     /usr/local/anaconda3/bin/deactivate
no change     /usr/local/anaconda3/etc/profile.d/conda.sh
no change     /usr/local/anaconda3/etc/fish/conf.d/conda.fish
no change     /usr/local/anaconda3/shell/condabin/Conda.psm1
no change     /usr/local/anaconda3/shell/condabin/conda-hook.ps1
no change     /usr/local/anaconda3/lib/python3.7/site-packages/xontrib/conda.xsh
no change     /usr/local/anaconda3/etc/profile.d/conda.csh
no change     /Users/julio/.bash_profile
No action taken.

```

and I can see the changes in my.bash_profile
```
# !! Contents within this block are managed by 'conda init' !!
...
```

I am using MacOS Mojave 10.14.6

Thanks a lot!

**Comment by adefossez** [comment]
Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.

**Comment by juliocamarero** [comment]
That works! Thank you @adefossez!

**Comment by shyjuwilsonskt** [comment]
I installed Miniforge on Apple Mac M1 (Mac OS Big Sur). I also getting the same error. What to do?

Thank you
Shyju Wilson

> Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.

**Comment by eckartbindewald** [comment]
> I installed Miniforge on Apple Mac M1 (Mac OS Big Sur). I also getting the same error. What to do?
> 
> Thank you
> Shyju Wilson
> 
> > Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.

Same here, running into same error with Mac M1 on OS Big Sur. Followed instructions mentioned here (sourcing the consa.sh script) and others on stackoverflow with various versions of conda init - in all cases leading to the same CommandNotFound error. This is really difficult and needs further documentation

**Comment by shyjuwilsonskt** [comment]
> I installed Miniforge on Apple Mac M1 (Mac OS Big Sur). I also getting the same error. What to do?
> 
> Thank you
> Shyju Wilson
> 
> > Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.


> I installed Miniforge on Apple Mac M1 (Mac OS Big Sur). I also getting the same error. What to do?
> 
> Thank you
> Shyju Wilson
> 
> > Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.

Hi, 
Thank you for the reply. Somehow it was working.

Shyju Wilson

**Comment by Syazvinski** [comment]
I have the same issue, im on mac M1 and I've tried everythng.

**Comment by shyjuwilsonskt** [comment]
> I have the same issue, im on mac M1 and I've tried everythng.

I have tried following steps:

install xcode 12.5.1 from app store
install Command Line Tools for Xcode 12.5.1 from https://developer.apple.com/download/all/

install homebrew refer: https://brew.sh
type at terminal: brew install miniforge
type at terminal: conda init zsh

start new terminal
type at terminal: conda create -n pytorch_env python=3.8

start new terminal 
type at terminal: conda activate pytorch_env
type at terminal: pip install torchvision
(This will install both torch and torchvision) Done !!!

Now go to Python shell and you can try following commands:
import torch
import torchvision

for the experiment with sample code (download the code from https://github.com/pytorch/examples/blob/master/mnist/main.py)
type the command: python main.py

**Comment by proukakis** [comment]
> Hey @juliocamarero , sorry for my late reply, can you try to do first `source /usr/local/anaconda3/etc/profile.d/conda.sh` ? Then you should be able to run `conda activate`.

wow. thanks!
