### ISSUE TITLE
Demucs it's not working :(

### ISSUE THREAD

**Issue by JpJpSoundcloud** [facebookresearch/demucs#181]
## ❓ Questions

Hi, whenever i try to separate a song i get this problem:

ModuleNotFoundError: No module named 'julius'

I asked 2 other firends to run demucs and they get the same problem.

I hope y'all can fix this and i also want to say that i really love working on demucs, it works pretty well.

**Comment by adefossez** [comment]
Run `pip install julius` and it should work

**Comment by JpJpSoundcloud** [comment]
@adefossez thank you for the respond! I added "pip install julius" and now Demucs it's working again for me. I also had to do some other changes to actually get it to work, like "!pip install torchaudio"  "!pip install diffq"  and finally change  "!python -m demucs.separate --dl -n tasnet_extra"  to   " !python -m demucs.separate -n tasnet_extra".

**Comment by adefossez** [comment]
Yes, that is because of the update! sorry about that :) Now a good thing to do in the future in case of issue is `pip install .` after an update and it will install all dependencies.
