### ISSUE TITLE
SDR

### ISSUE THREAD

**Issue by yajashgoplani** [facebookresearch/demucs#184]
## ❓ Questions

(Please ask your question here.)
How to calculate  sdr on test data??

**Comment by adefossez** [comment]
SDR is computed automatically at the end of training. You can use the  `--test_pretrained` command to test a pre trained model for instance model: `./run.py --test_pretrained=demucs_quantized` .

This is going to take a bit of time, as SDR computation is relatively slow. Once it is finished, use the `python result_table.py` script, that will display the SDR for all models that completed the above step.

If you train your own model, just wait for the end of training. see https://github.com/facebookresearch/demucs/blob/master/docs/mdx.md#evaluate-and-export-a-model-before-training-is-over if you want to evaluate before training is over.
