### ISSUE TITLE
unrecognized arguments: [EXTRA_FLAGS]

### ISSUE THREAD

**Issue by KimberleyJensen** [facebookresearch/demucs#187]
## 🐛 Bug Report

I get this error when i try to run the training command

## To Reproduce

python3 run.py --musdb /home/ubuntu/Downloads/musdb [EXTRA_FLAGS]

## Expected behavior

model training

## Actual Behavior

![demucs](https://user-images.githubusercontent.com/84926118/123490141-699fd980-d60b-11eb-9c13-284434477eab.png)

by the way i also get this when i did the pip install -e command i dont know if that means anything
![pip e](https://user-images.githubusercontent.com/84926118/123490153-7290ab00-d60b-11eb-9588-11846af4baee.png)

please can someone help me i am using a nvidia t4 from amazon ec2

**Comment by helloimmatt** [comment]
The [EXTRA_FLAGS] is a placeholder for, uh, extra flags. Since you're not using any, just simply execute `python3 run.py --musdb /home/ubuntu/Downloads/musdb` instead.

As for the second command, you forgot the `.` at the end. So, `pip install -e .`

**Comment by lyndonlauder** [comment]
LOL the one time i am meant to copy the command exact i dont and when i shouldnt i do. So extra flags just means extra commands, Thank you @helloimmatt !!

**Comment by KimberleyJensen** [comment]
oh right so extra_flags just means extra commands lolll. Thank you @helloimmatt !!
