### ISSUE TITLE
The Colab is not working

### ISSUE THREAD

**Issue by circuitcat** [facebookresearch/demucs#188]
The Colab is not working. `separate()` did not work for me. From what I can tell, some changes and leading exclamation points are needed.
e.g. 
`separate()` should be `!python3 -m demucs.separate PATH_TO_AUDIO_FILE_1`
`from_upload()` should be `!from_upload()`
and
`files.download('./separated.zip')` should be `!files.download('./separated.zip')` ???
However, I still see the error:
```
/bin/bash: -c: line 0: syntax error near unexpected token `'./separated.zip''
/bin/bash: -c: line 0: `files.download('./separated.zip')'
```
I was able to download separated.zip from the ... menu near the file name in the file browser.
Note that the file was not at the path /gdrive/MyDrive/demucs_separated/separated.zip
but was at /content/separated.zip instead.

**Comment by helloimmatt** [comment]
If you're using the Colab from the readme, then it's working fine as is. My guess is you forgot to run the "Useful functions" script which is what defines `separate()` and such.
