### ISSUE TITLE
How to speed up model inference on CPU?

### ISSUE THREAD

**Issue by lyghter** [facebookresearch/demucs#191]
Is there a ways to speed up the inference of a pretrained 4-stem model on CPU? I want to separate 1 or 2 stems. I have some experience with Python and PyTorch.

**Comment by adefossez** [comment]
There is no way to speed up inference of the pre-trained 4-stem model for 2 stems extraction. There is no specific path in the model for each stem, except for the last layer, which has a minor cost.
If you want to separate two stems, then you might be able to use a smaller model, but that might not even be that true.
