### ISSUE TITLE
Error during TasNet training

### ISSUE THREAD

**Issue by Hanyu-Meng** [facebookresearch/demucs#193]
## ❓ Questions
I am trying to train the TasNet in a high-performance computer followed by the instruction. I connected to a node and execute the interactive job in a virtual environment created by conda.
<img width="719" alt="Screen Shot 2021-07-06 at 2 22 35 pm" src="https://user-images.githubusercontent.com/74821538/124541852-9d79cb00-de65-11eb-8d10-10a47b7409eb.png">

Then I always got this error that terminates the training process.
Can anyone tell me how to deal with that ?

Cheers,
Hanyu

**Comment by adefossez** [comment]
your version of soundstretch is too old. it needs to be at least. 2.1.2.
You can train without it with `--repitch=0` which anyway doesnt impact tasnet.
