### ISSUE TITLE
Is Demucs training on more tracks than I have in the training folder?

### ISSUE THREAD

**Issue by KimberleyJensen** [facebookresearch/demucs#196]
I am using 58 tracks for training using this command 

!python3 run.py --wav /demucs/musdbe --musdb /demucs/musdbe --is_wav --channels=48 --depth=6 --repitch=0 --samplerate 44100 --samples 44100 --data_stride 44100

Number of training samples adjusted to 49834
Train set and valid set sizes 11613 50
[000] train (1/2):  26%|█████▉                 | 47/182 

It trains fine but shouldn't it show /58 instead of /182?

Some of the 58 tracks i am using for training are from the MUSDB train dataset and for validation i am using all 50 tracks from the MUSDB test set.

**Comment by adefossez** [comment]
The number of batches is not equal to the number of tracks. Each track is splitted into segments of 11 seconds, with a 1 second stride between segments. Then you have to divide that by the batch size and number of gpus used in order to get the epoch length.

**Comment by KimberleyJensen** [comment]
Thank you :)
