### ISSUE TITLE
overloud ragged effect of voices and other

### ISSUE THREAD

**Issue by BitBlueDevStudio** [facebookresearch/demucs#202]
## ❓ Questions

I noticed that in pretrained models (all models) output quality of vocals and "other: some times get ragged, like overloud record, but in moments where simple clean vocal comes. Like if I make some track very loud, so speakers can't take it ))

I can provide a sample file of voice with that effects. Is there any way to overcome this?

Thanks in advance!

**Comment by adefossez** [comment]
Hello, sadly there is no way to overcome this, it is part of the limitations of the model, architecture and training data at the moment.

**Comment by BitBlueDevStudio** [comment]
Thanks for answer
