### ISSUE TITLE
How the F**k do i use the collab?

### ISSUE THREAD

**Issue by JohnSmith2007** [facebookresearch/demucs#203]
## ❓ Questions

No matter what i do, i keep getting this error. What the fuck?

/usr/bin/python3: Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')
Going to separate the files:
/gdrive/MyDrive/demucs/song.flac
With command:  python3 -m demucs.separate -o /gdrive/MyDrive/demucs_separated/ -n demucs_quantized --mp3 --mp3-bitrate=320
Command failed, something went wrong.

**Comment by adefossez** [comment]
Hello @JohnSmith2007,

First I would encourage you not to use any curse words in the future. While I do my best to provide a solution for everyone, I expect communication to always be polite and respectful.

For your issue, did you execute all the statements ? In particular you might be missing the very first one `pip install -U demucs`.

**Comment by JohnSmith2007** [comment]
> Hello @JohnSmith2007,
> 
> First I would encourage you not to use any curse words in the future. While I do my best to provide a solution for everyone, I expect communication to always be polite and respectful.
> 
> For your issue, did you execute all the statements ? In particular you might be missing the very first one `pip install -U demucs`.

Ok, Yeah, i didn't see that at the top of the collab page. thank you for pointing it out. And i apologize for the swearing, it was really getting on my nerves at the time.

However, after i did that step, and mounted my google drive, iexecuted the next step to seperate the audio, only to get this error

NameError                                 Traceback (most recent call last)
<ipython-input-4-fb2d2ba182f8> in <module>()
      2 # This is from google drive! Also, this will separate all the files inside the MyDrive/demucs folder,
      3 # so when you are happy with the results, remove the songs from there.
----> 4 separate()

NameError: name 'separate' is not defined

Now what?

**Comment by JohnSmith2007** [comment]
wait, nevermind. i didn't execute the # Customize the following options! step. It's working now.

**Comment by JohnSmith2007** [comment]
However, i do have one more question. Is there an option to change the output format in the collab? Like, instead of MP3, could it be changed to WAV?

**Comment by adefossez** [comment]
In the section with `Custromize the following options` set `mp3 = False`
