### ISSUE TITLE
 Incompatible

### ISSUE THREAD

**Issue by alex7313** [facebookresearch/demucs#21]
pc: windows 10

(base) C:\Users\alexm>conda env update -f environment-cuda.yml
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining cudatoolkit:   4%|8                    | 3/74 [00:00<00:00, 1500.11it/|
Comparing specs that have this dependency:   0%|            | 0/2 [00:00<?, ?it/s]
Finding shortest conflict path for cudatoolkit[version='>=10.1,<10.2']:  50%|5| 1/2
Examining ninja:  30%|########3                   | 22/74 [00:47<08:18,  9.58s/it/ failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package cudatoolkit conflicts for:
pytorch=1.3.1 -> cudatoolkit[version='>=10.1,<10.2']
cudatoolkit=10.0

**Comment by rokimoki** [comment]
I recommend to use the CPU version instead. It's a quick fix, because some GPU, even 1060gtx is having issues to run with GPU mode.

**Comment by adefossez** [comment]
Hey @alex7313 , if you update your repo, the problem should be fixed now :) Alternatively you can install from `environment-cpu.yml` as @rokimoki suggest :)
