### ISSUE TITLE
Option "-n tasnet" does not work in new release

### ISSUE THREAD

**Issue by mepc36** [facebookresearch/demucs#219]
## 🐛 Bug Report

The new release has broken the "-n tasnet" option.

## To Reproduce

1. Install the new release.
2. Try to run a command with the "-n tasnet" option. This is the specific command that failed for me:

`python '-m demucs.separate -d cpu -n tasnet ./input/54929fb09f6be3e5cbc82ec456e952bea6dd70ac.mp3 -o ./output`

## Expected behavior

The command should separate the input mp3 into a vocals, bass, etc., wav file.

## Actual Behavior

Here is my entire log I got back when trying this command:

```
root@93bbeef08257:/usr/src/app# python -m demucs.separate -d cpu -n tasnet ./input/f884b7fe0188471a4da0bce3c9b9bfdcfa362511.mp3 -o ./output

FATAL: tasnet is neither a single pre-trained model or a bag of models.
```

## Your Environment

I am running demucs with an express server inside a node/python Docker container. I build the container's image using the following `Dockerfile`:

```
FROM nikolaik/python-nodejs:python3.9-nodejs17

# Create app directory
WORKDIR /usr/src/app

RUN apt-get -y update
RUN apt-get -y upgrade

# Install newest ffmpeg via binary build:
RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
RUN wget https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz.md5
RUN tar xvf ffmpeg-git-amd64-static.tar.xz
RUN mv $(pattern="ffmpeg" && for _dir in *"${pattern}"*; do [ -d "${_dir}" ] && dir="${_dir}" && break; done && echo "${dir}")/ffmpeg $(pattern="ffmpeg" && for _dir in *"${pattern}"*; do [ -d "${_dir}" ] && dir="${_dir}" && break; done && echo "${dir}")/ffprobe /usr/local/bin/

# Install vocals separator:
RUN python3 -m pip install demucs --no-cache-dir

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

# Install npm dependencies:
RUN yarn install

# If you are building your code for production:
# RUN npm ci --only=production

# Bundle app source:
COPY . .

EXPOSE 3001
CMD [ "node", "src/express/express.js" ]
```

That Dockerfile above automatically installs the newest version of demucs. This same command was working fine up until this morning; I had gotten split vocals from it as recently as 8 AM EST. 

**Installing the old version of demucs, 2.0.3, made this command work again.**

I did that by replacing this line...

`RUN python3 -m pip install demucs --no-cache-dir`

...with this line:

`RUN python3 -m pip install demucs==2.0.3 --no-cache-dir`

That version change allowed the command with the `-n tasnet` option to be successfully run.

- Python and PyTorch version:

Python version is 3.9; not sure what PyTorch is. If you need it I can get you it later, just wanted to drop this ASAP since the new release went out and is in a state of (presumed) hypercare.

- Operating system and version (desktop or mobile):

MacOS 11.5.1, but, again, this bug got thrown by a python/node build running inside a Docker container. The container's python version is 3.9; the node version is 17. Please see the following image for more info: nikolaik/python-nodejs:python3.9-nodejs17

- Hardware (gpu or cpu, amount of RAM etc.):

**Comment by adefossez** [comment]
Sorry about that, support for Tasnet was dropped in the latest version. This was an very large rewrite and it was too much work to keep backward compatibility.
Feel free to stay at the v2 version if you want to keep using it!

**Comment by mepc36** [comment]
Sorry, didn't see that release note. My fault @adefossez!

I was originally using Tasnet only to b/c my machine was not fast enough to handle the regular model; does release 3 come with any new options that might be able to also save me memory besides the (deprecated) `-n tasnet` option? As you can see, I'm already using `-d cpu` and still hitting my upper limit...

This is a GREAT module by the way! thanks for maintaining it :)

(I will close with comment soon, sounds like this is not really a bug at all!)

**Comment by adefossez** [comment]
No worries, it was in the small prints haha.

So at the moment I dont think anything will be as lightweight in memory as tasnet used to be. It should be possible to improve memory usage though. How much RAM do you have available ?

See also this related issue:
https://github.com/facebookresearch/demucs/issues/218

I'll try to improve memory usage in the coming weeks!

**Comment by mepc36** [comment]
> I'll try to improve memory usage in the coming weeks!

Awesome, thank you!

> How much RAM do you have available ?

I'm actually running demucs inside a docker container on an AWS EC2 t2.large instance. The specs for that instance can be found [here](https://aws.amazon.com/ec2/instance-types/?trkCampaign=acq_paid_search_brand&sc_channel=PS&sc_campaign=acquisition_US&sc_publisher=Google&sc_category=Cloud%20Computing&sc_country=US&sc_geo=NAMER&sc_outcome=acq&sc_detail=%2Bec2%20%2Bcloud&sc_content={ad%20group}&sc_matchtype=b&sc_segment=536455698896&sc_medium=ACQ-P|PS-GO|Brand|Desktop|SU|Cloud%20Computing|EC2|US|EN|Sitelink&s_kwcid=AL!4422!3!536455698896!b!!g!!%2Bec2%20%2Bcloud&ef_id=CjwKCAiAvriMBhAuEiwA8Cs5lYb9cWFMJy8Wffz7JvCiWRRhoKzg3y-hZV0rPr7lI6JA2PcnzmWJmBoCleQQAvD_BwE:G:s&s_kwcid=AL!4422!3!536455698896!b!!g!!%2Bec2%20%2Bcloud), and boil down to this: 2 vCPUs, with memory of 8 GB. I've tried that demucs command on larger instance types (t2.xlarge with 4 vCPU's/16 GB and t2.2xlarge with 8 vCPU's and 32 GB), but still got `ENOMEM` errors.

I think the fact that I'm running demucs on a deployed server makes this firmly a problem for me to solve, and not the library, since it'd be unreasonable to expect the library to support a use case. Any help you could offer would be great though!

One last question: I've read in other comments that demucs takes about 6 GB of emory to run; is this true?

**Comment by adefossez** [comment]
I don't have the exact numbers for how much memory it needs but 6GB seems about right. See the issue I linked above, there are on going discussions on how to reduce that.

Theoretically would should be able to get much lower than that (probably under 2GB).

**Comment by mepc36** [comment]
Great, thanks...closing.
