### ISSUE TITLE
Problem with channels

### ISSUE THREAD

**Issue by francopa04** [facebookresearch/demucs#22]
"RuntimeError: Given groups=1, weight of size 100 2 8, expected input[1, 1, 652628] to have 2 channels, but got 1 channels instead"
I think there is the problem and i dont know what to do, help please

**Comment by adefossez** [comment]
Only stereo input is supported :/ You can first convert to stereo by running:
```bash
ffmpeg -i INPUT_FILE -ac 2 output.wav
```
and then run Demucs on `output.wav`.
