### ISSUE TITLE
Running .bat files in directory instead of Demucs.

### ISSUE THREAD

**Issue by CyberLykan** [facebookresearch/demucs#220]
## 🐛 Bug Report

If there is a .bat file present in the directory where you are running the Demucs command, it just runs that .bat file instead.

## To Reproduce

1. Create a .bat file with `echo Hello world.` as the contents.
1. Run Demucs in the same directory where the .bat file was created. I used `demucs -n mdx_extra --overlap 0.15 -d cpu FILE_HERE`.

## Expected behavior

It successfully runs the Demucs command.

## Actual Behavior

It runs the .bat file instead, disregarding the Demucs command.

## Your Environment

- Python and PyTorch version: Python 3.8.10, PyTorch 1.11.0.dev20211024+cu113
- Operating system and version: Windows 10 Pro 19043.1320
- Hardware: NVIDIA GeForce GTX 1050 Ti, AMD Ryzen 7 2700x, 32GB RAM

**Comment by adefossez** [comment]
Does it do it for any filename for the bat file?

**Comment by CyberLykan** [comment]
> Does it do it for any filename for the bat file?

Hmm, it seems to just be bat files named `Demucs.bat` or `demucs.bat`

**Comment by adefossez** [comment]
Yep that is expected and is just normal behavior for windows.
