### ISSUE TITLE
Default V3 Model vs. Track B MDX Model

### ISSUE THREAD

**Issue by jaolan** [facebookresearch/demucs#226]
## ❓ Questions

Hi @adefossez, thank you for providing v3 and congrats. A few questions:

Is the default used model (quantized mdx_extra) the same as the Track B model used for MDX 2021 that achieved 8.11 SDR? I tried the following signatures using export.py to export the following model sigs from Track B:
- e51eebcc
- a1d90b5c
- 5d2d6c55
- cfa93e08

And it downloaded 4 150MB models. Are these just non quantized mdx_extra models or do they provide better SDR? How does one export models to file similar to the --models flag in Demucs v2?

Many thanks and best of luck at ISMIR 2021 =)

**Comment by adefossez** [comment]
The default model is actually `mdx_extra_q` which is 7.97 dB on MDX, against 8.11 for dB for the non quantized model. The total size is almost 4 times smaller though so I figured the 0.1 dB were acceptable loss to have smaller download and storage.

The `mdx_extra` is the one from Track B.

You can export your own trained model with `https://github.com/facebookresearch/demucs/blob/main/docs/training.md#model-export` if that is the question; but the format wont be compatible with v2 of Demucs.

If you just want to inspect those models, you can do `from demucs import pretrained; pretrained.get_model('5d2d6c55')`.
Not sure if that answers your question !

**Comment by jaolan** [comment]
Definitely answers, many thanks!
