### ISSUE TITLE
No module named Dora

### ISSUE THREAD

**Issue by ProgressiveProgression** [facebookresearch/demucs#227]
## ❓ Questions
Hi. I have another **Module is not found** error about Dora module when separate.py file tries to import fatal from _dora.log_. I exactly followed the instructions for Demucs v3 installation, so I should have all the required environment. Also I tried to install Dora package separately using **pip install dora** but it still does not work when I run _python.exe -m demucs_ command.

**Comment by adefossez** [comment]
You can do ´pip install dora-search ´ !
Sorry it is my fault I will update the conda files.

**Comment by ProgressiveProgression** [comment]
Thank you. I will try this out later. 

I tried to reinstall Demucs as well and faced the another problem: https://github.com/facebookresearch/demucs/issues/228

**Comment by ProgressiveProgression** [comment]
Installing of the dora-search solved the problem. Thank you.

P.S. I tried to get stems from a couple of a deathcore songs and nowadays Demucs gives the best result. Algorythm was able to recognize even extreme vocal :P Brilliant work! Thank you.

**Comment by adefossez** [comment]
Awesome thanks :)
