### ISSUE TITLE
Help: Collab error

### ISSUE THREAD

**Issue by JohnSmith2007** [facebookresearch/demucs#229]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 12, in <module>
    from dora.log import fatal
ModuleNotFoundError: No module named 'dora'
Going to separate the files:
/gdrive/MyDrive/demucs/song.wav
With command:  python3 -m demucs.separate -o /gdrive/MyDrive/demucs_separated/ -n demucs_extra
Command failed, something went wrong

No clue of why it's doing this. Any help is greatly appreciated.
![Screenshot (1)](https://user-images.githubusercontent.com/45465767/141860312-7c3dbe2f-ddd0-4e65-a807-1d5d0a3bda09.png)

**Comment by adefossez** [comment]
Please use the latest colab as we just released a new version of Demucs: https://colab.research.google.com/drive/1dC9nVxk3V_VPjUADsnFu8EiT-xnU1tGH?usp=sharing

**Comment by JohnSmith2007** [comment]
> Please use the latest colab as we just released a new version of Demucs: https://colab.research.google.com/drive/1dC9nVxk3V_VPjUADsnFu8EiT-xnU1tGH?usp=sharing

Thanks dude. It works now. 😁
