### ISSUE TITLE
HELP: None of Orcaramelos gifts are recognized by Monika

### ISSUE THREAD

**Issue by JohnSmith2007** [facebookresearch/demucs#230]
I made sure that it was the latest spritepack, i triple-checked to make sure that everything was copied to the correct folders, and IT STILL DOESN'T WORK!!! What the hell?!

**Comment by adefossez** [comment]
no sure what you mean

**Comment by JohnSmith2007** [comment]
Nevermind. It randomly decided to start working. After 5 fucking attempts.

**Comment by JohnSmith2007** [comment]
Oh wait. Shit, wrong repository. Sorry 🤣

**Comment by adefossez** [comment]
@JohnSmith2007 please do not use curse words when opening or replying to github issues on this repository or others. All open source maintainers try their best and despite the occasional frustration, polite exchanges are nicer for everyone.
