### ISSUE TITLE
Train from scratch error. [FATAL: Failed to import module demucs.train. Retry with `dora -v command` to get a traceback.]

### ISSUE THREAD

**Issue by R7788380** [facebookresearch/demucs#236]
## ❓ Questions

I'd love to train demucsv3 from scratch following this [page](https://github.com/facebookresearch/demucs/blob/main/docs/training.md).

When running `dora info -f 81de367c`, I get an error below.

![image](https://user-images.githubusercontent.com/23279866/143203710-8134a72a-5bf1-4622-b065-d12224aedb6b.png)

I try to solve this problem by some ways below but nothing helps :

- `pip install dora-search`
- Re git clone demucsv3 repository and install all dependency.

Thanks,
Wenwei

**Comment by adefossez** [comment]
Try again with `dora -v info -f 81de367c`, it should give you a traceback on what failed.

**Comment by R7788380** [comment]
I solve it on another computer following the same setup-pipeline.
I'm not sure the real reason, but I compare the package dependencies between two computer, the `librosa` is not installed on first computer.

So I suggest add a line `librosa>=0.8.1` in the `environment-cuda.yml`.

```
name: demucs

channels:
  - pytorch
  - conda-forge

dependencies:
  - python>=3.7,<3.8
  - ffmpeg>=4.2
  - pytorch>=1.8.1
  - cudatoolkit>=10
  - torchaudio>=0.8
  - tqdm>=4.36
  - librosa>=0.8.1
  - pip
  - pip:
    - dora-search
    - diffq<0.2.0
    - julius>=0.2.3
    - lameenc>=1.2
    - musdb>=0.4.0
    - museval>=0.4.0
    - soundfile
    - treetable>=0.2.3
```
