### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by thenormal** [facebookresearch/demucs#239]
## ❓ Questions

Hello to the devs. First and foremost, congratulations on this amazing technology. I have been using Spleeter and Lalal.ai so far, but demucs is way way better on all fronts and also still getting improved continously!

I am no dev and I am currently testing this technology on a Windows machine using Google Colab. It even took me a while to understand how to link Demucs with the latter, but I finally was able to separate tracks with it.

I have two questions, and please bear in mind they come from a noob who knows nothing about coding or Github.

1) When I use Google Colab, I upload an .mp3 file and I see that Demucs converts it into a .wav file, and then processes the stems. Is there a way to upload an .mp3 file and have the system return another processed .mp3 file?

2) I see that Demucs processes a track by isolating it into four different stems (drums, vocals, other, and bass). Would it be possible to have two stems returned, rather than four? For instance, Accompaniment and vocals only, so that we can get a song whereby only the vocals have been extracted?

Thanks for your support and best of luck with this project.

**Comment by CarlGao4** [comment]
I will try my best to help you. 
I only heard about Google Colab and didn’t use it myself, maybe my answer is not correct. 
I assume that you are using command `python3 -m demucs audio.mp3`. If you want to output .mp3, please change it into `python3 -m demucs --mp3 audio.mp3`. 
If you want only two output files, it would be harder for you because it requires coding experience. I can try to write a program to mix the other three output files so you have an audio without vocals.

**Comment by CarlGao4** [comment]
Try running this under output folder (I assume that you have output .mp3):
```python
import numpy as np
import torch
import torchaudio as ta

drums, sr = ta.load('drums.mp3')
other, sr = ta.load('other.mp3')
bass, sr = ta.load('bass.mp3')
sum = drums.numpy() + other.numpy() + bass.numpy()
ta.save('no_vocals.mp3', torch.from_numpy(sum), sr)
```
I’m not sure whether this works, because I typed this on my phone.

**Comment by thenormal** [comment]
> Try running this under output folder (I assume that you have output .mp3):
> 
> ```python
> import numpy as np
> import torch
> import torchaudio as ta
> 
> drums, sr = ta.load('drums.mp3')
> other, sr = ta.load('other.mp3')
> bass, sr = ta.load('bass.mp3')
> sum = drums.numpy() + other.numpy() + bass.numpy()
> ta.save('no_vocals.mp3', torch.from_numpy(sum), sr)
> ```
> 
> I’m not sure whether this works, because I typed this on my phone.

Hello. That's great, I will try to copy and paste your code onto Google Colab and see if it works.

To the developers: Maybe you can also check this out? I think plenty of people would be happy to have this option enabled, that is having Demucs convert a song into its vocals-less version, rather than into 4 different stems

@adefossez

**Comment by CarlGao4** [comment]
This is not so complicated, maybe I can do it later all by myself.

**Comment by adefossez** [comment]
@CarlGao4 feel free to open a PR if you find the time, otherwise I'll do it when I get the time !

**Comment by CarlGao4** [comment]
I would like to do it now, but I need to pass my final exams first😂
