### ISSUE TITLE
ayuda, no entiendo nada

### ISSUE THREAD

**Issue by Argus520** [facebookresearch/demucs#24]
hola, para empezar, nunca usé nada así, sólo vi el video de Jaime Altozano y me dio curiosidad, pero nunca pude hacer que funcione, alguien me puede explicar?

**Comment by jonathangarciacarapia** [comment]
x2

**Comment by rokimoki** [comment]
Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
6.- Luego continuan con "Separating tracks".

Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
Saludos.

**Comment by maghusg** [comment]
a mi me dice que no se encuentra el ordinal 242 en la biblioteca de vínculos dinamicos despues de hacer todo eso

**Comment by rokimoki** [comment]
> a mi me dice que no se encuentra el ordinal 242 en la biblioteca de vínculos dinamicos despues de hacer todo eso

Mira este enlace https://github.com/facebookresearch/demucs/issues/20#issue-534304999 y el enlace que te lleva a otra sección de comentarios...

**Comment by Argus520** [comment]
> Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> 6.- Luego continuan con "Separating tracks".
> 
> Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> Saludos.
> 
> EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)

hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.

**Comment by rokimoki** [comment]
> > Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> > 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> > 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> > 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> > 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> > 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> > 6.- Luego continuan con "Separating tracks".
> > Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> > Saludos.
> > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> 
> hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.

Supongo que instalaste con este comando: `conda env update -f environment-cpu.yml`

Debes activar siempre el entorno emucs en la consola de anaconda cuando vayas a usar la aplicación:
`conda activate demucs`

A continuación pasará de (base) a (demucs), y podrás ejecutar el siguiente comando:
`python.exe -m demucs.separate --dl -n demucs “ruta al archivo de musica” -d cpu`

Intenta dejar las doble comillas para la ruta del archivo de música.

Si surge cualquier otra cosa avisa.

**Comment by Argus520** [comment]
> > > Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> > > 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> > > 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> > > 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> > > 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> > > 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> > > 6.- Luego continuan con "Separating tracks".
> > > Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> > > Saludos.
> > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > 
> > 
> > hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.
> 
> Supongo que instalaste con este comando: `conda env update -f environment-cpu.yml`
> 
> Debes activar siempre el entorno emucs en la consola de anaconda cuando vayas a usar la aplicación:
> `conda activate demucs`
> 
> A continuación pasará de (base) a (demucs), y podrás ejecutar el siguiente comando:
> `python.exe -m demucs.separate --dl -n demucs “ruta al archivo de musica” -d cpu`
> 
> Intenta dejar las doble comillas para la ruta del archivo de música.
> 
> Si surge cualquier otra cosa avisa.

ya en el paso final me aparece esto:RuntimeError: unexpected EOF, expected 157040471 more bytes. The file might be corrupted.

**Comment by rokimoki** [comment]
> > > > Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> > > > 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> > > > 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> > > > 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> > > > 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> > > > 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> > > > 6.- Luego continuan con "Separating tracks".
> > > > Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> > > > Saludos.
> > > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > > 
> > > 
> > > hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.
> > 
> > 
> > Supongo que instalaste con este comando: `conda env update -f environment-cpu.yml`
> > Debes activar siempre el entorno emucs en la consola de anaconda cuando vayas a usar la aplicación:
> > `conda activate demucs`
> > A continuación pasará de (base) a (demucs), y podrás ejecutar el siguiente comando:
> > `python.exe -m demucs.separate --dl -n demucs “ruta al archivo de musica” -d cpu`
> > Intenta dejar las doble comillas para la ruta del archivo de música.
> > Si surge cualquier otra cosa avisa.
> 
> ya en el paso final me aparece esto:RuntimeError: unexpected EOF, expected 157040471 more bytes. The file might be corrupted.

Pon una captura del comando que ejecutas y la salida entera.

**Comment by Argus520** [comment]
![Captura de pantalla (608)](https://user-images.githubusercontent.com/58617606/70382985-80f17600-1944-11ea-8fb7-d7af815cbbac.png)

**Comment by rokimoki** [comment]
Mira este comentario https://github.com/facebookresearch/demucs/issues/34#issuecomment-562894918

**Comment by Argus520** [comment]
> Mira este comentario [#34 (comment)](https://github.com/facebookresearch/demucs/issues/34#issuecomment-562894918)

Muchísimas gracias, no sé que haría sin tí, qué bueno que haya personas como tú por aquí.

**Comment by AlonsoWhistle** [comment]
Hola yo realice los pasos tal cual lo detallas. La primera vez al usar este: "conda env update -f environment-cpu.yml" se puso a actualizar y tomo bastaaaante. Este proceso de actualización basta con hacerlo una sola vez? o tengo qe hacerlo siempre que quiera utilizar la aplicación?
Despues de que se actualizó logre insertar el comando y poner la canción la cual comenzó a cargar pero al momento de llegar al 80% mi PC se quedó freezeado y tuve que reiniciar. Ahora al volver a intentarlo sigo los pasos de antes (incluido el comando de update pero este ahora me dice que los "requirements are already satisfied" y pasa de largo nomas), se demora mucho mas q antes y la canción no pasa del 0% llevando asi mas de 15 minutos. Necesito ayuda para saber que estoy haciendo. Adjunto una foto de lo último que dije.
![imagen](https://user-images.githubusercontent.com/58670640/70398043-1a2c9500-19f6-11ea-86a0-a693ceba9ec5.png)

**Comment by rokimoki** [comment]
> Hola yo realice los pasos tal cual lo detallas. La primera vez al usar este: "conda env update -f environment-cpu.yml" se puso a actualizar y tomo bastaaaante. Este proceso de actualización basta con hacerlo una sola vez? o tengo qe hacerlo siempre que quiera utilizar la aplicación?
> Despues de que se actualizó logre insertar el comando y poner la canción la cual comenzó a cargar pero al momento de llegar al 80% mi PC se quedó freezeado y tuve que reiniciar. Ahora al volver a intentarlo sigo los pasos de antes (incluido el comando de update pero este ahora me dice que los "requirements are already satisfied" y pasa de largo nomas), se demora mucho mas q antes y la canción no pasa del 0% llevando asi mas de 15 minutos. Necesito ayuda para saber que estoy haciendo. Adjunto una foto de lo último que dije.
> ![imagen](https://user-images.githubusercontent.com/58670640/70398043-1a2c9500-19f6-11ea-86a0-a693ceba9ec5.png)

El único comando que debes hacer cuando abres la consola de anaconda es el `conda activate demucs`, y luego ya puedes separar canciones. 

Que no aparezca la barra de progreso es normal, a mi me tarda de 3 a 5 minutos con un i7-3770, puede tardarte hasta 30 minutos dependiendo de la cpu. Normalmente hardware antiguo o de bajo rendimiento no suele ser lo ideal, a pesar de que sea bastante accesible usar estas tecnologías, se necesita hardware más o menos potente para que no tardes un día en separar una canción.

**Comment by AlonsoWhistle** [comment]
Comprendo pero la vez anterior cuando llegó  80 % se demoró aproximadamente unos 4 minutos y en el pantallazo adjuntado ya iba por los 20 minutos o más incluso. Habré estado haciendo algo mal?

**Comment by rokimoki** [comment]
> Comprendo pero la vez anterior cuando llegó 80 % se demoró aproximadamente unos 4 minutos y en el pantallazo adjuntado ya iba por los 20 minutos o más incluso. Habré estado haciendo algo mal?

Mira en procesos si está activo y consumiendo cpu, creo que solo queda esperar, si no volver a intentarlo con otra canción...

**Comment by SantiagoMusic** [comment]
Donde y cómo descargo el Demucs Master (Proyecto ,ZIP) ?

**Comment by rokimoki** [comment]
> Donde y cómo descargo el Demucs Master (Proyecto ,ZIP) ?

En clone or download en la página principal del proyecto, el enlace es: https://github.com/facebookresearch/demucs/archive/master.zip

**Comment by Giova452** [comment]
> 
> 
> > > Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> > > 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> > > 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> > > 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> > > 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> > > 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> > > 6.- Luego continuan con "Separating tracks".
> > > Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> > > Saludos.
> > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > 
> > 
> > hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.
> 
> Supongo que instalaste con este comando: `conda env update -f environment-cpu.yml`
> 
> Debes activar siempre el entorno emucs en la consola de anaconda cuando vayas a usar la aplicación:
> `conda activate demucs`
> 
> A continuación pasará de (base) a (demucs), y podrás ejecutar el siguiente comando:
> `python.exe -m demucs.separate --dl -n demucs “ruta al archivo de musica” -d cpu`
> 
> Intenta dejar las doble comillas para la ruta del archivo de música.
> 
> Si surge cualquier otra cosa avisa.

Disculpa, Rokimoki, tengo una duda, ¿qué función hace `-d cpu´ dentro de la línea de código?
Mi pregunta surge porque, a lo que entendí, Demucs puede utilizar el CPU o mi GPU. Si quiero utilizar mi GPU ¿tengo que sustir `-d cpu´ por `-d gpu´ ? 
Gracias 👍 🥇

**Comment by rokimoki** [comment]
> > > > Hola, me alegra que quieran probarlo gracias a Jaime Altonazo:
> > > > 1.- [Descargar ](https://www.anaconda.com/distribution/) Anaconda para Python 3.7 version.
> > > > 2.- Lo instalan, supongo que será para Windows (yo lo probé en Windows).
> > > > 3.- Van a la búsqueda del SO, buscan Anaconda y la sugerencia de Anaconda Prompt (Anaconda 3) le dan, será una especie de consola de texto.
> > > > 4.- Descargan el proyecto, extraen el ZIP, y ponen la carpeta en el escritorio (por ejemplo), y dentro de la consola tendrán que poner una ruta similar a "cd C:\Users\usuario\Escritorio\demucs-master\demucs-master", sino en la carpeta del proyecto arriba os sale la dirección.
> > > > 5.- Dentro de ahí, escriben los comandos que aparecen en "Requirements" en la descripción de este proyecto.
> > > > 6.- Luego continuan con "Separating tracks".
> > > > Si tienen más dudas sólo tienen que leer detenidamente o volver a preguntar.
> > > > Saludos.
> > > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > > 
> > > 
> > > hola, primeramente le agradezco por ayudarme, logré hacer todo bien hasta el paso 5 pero me perdí bastante y no sé qué poner de la parte "separating tracks", le agradecería su ayuda.
> > 
> > 
> > Supongo que instalaste con este comando: `conda env update -f environment-cpu.yml`
> > Debes activar siempre el entorno emucs en la consola de anaconda cuando vayas a usar la aplicación:
> > `conda activate demucs`
> > A continuación pasará de (base) a (demucs), y podrás ejecutar el siguiente comando:
> > `python.exe -m demucs.separate --dl -n demucs “ruta al archivo de musica” -d cpu`
> > Intenta dejar las doble comillas para la ruta del archivo de música.
> > Si surge cualquier otra cosa avisa.
> 
> Disculpa, Rokimoki, tengo una duda, ¿qué función hace `-d cpu` dentro de la línea de código?
> Mi pregunta surge porque, a lo que entendí, Demucs puede utilizar el CPU o mi GPU. Si quiero utilizar mi GPU ¿tengo que sustir `-d cpu` por `-d gpu` ?
> Gracias 👍 🥇

Para utilizar la GPU debes haber instalado `conda env update -f environment-cuda.yml` y usar el comando sin `-d cpu`. No obstante, he leído que al parecer necesitas una GPU con más de 6gb de memoria, en mi caso con la 1060gtx 6gb se queda sin memoria. No sé si con la última actualización de hace unos días se corrige (usando otras versiones de las librerías de las dependencias).

Saludos.

**Comment by SantiagoMusic** [comment]
Ya descargue el Anaconda pero me aparece disque Anaconda Navigator, tengo que descargar algo de ahí o que más hago

**Comment by SantiagoMusic** [comment]
Cuando ejecuto:
conda env update -f environment-cpu.yml

Recibo este mensaje:
EnvironmentFileNotFound: archivo 'C: \ Users \ user \ environment-cpu.yml' no encontrado 

Que hago 

Tengo lo que descomprimí del archivo Zip que descargue en descargas (demucs-master)

**Comment by rokimoki** [comment]
Hola, probablemente no estés situado en la carpeta de demucs en la consola de anaconda, fíjate en las instrucciones https://github.com/facebookresearch/demucs#using-windows y repítelas si fuese necesario.

**Comment by adefossez** [comment]
Closing this issue now, please reopen individual issues if you still encouter problems :)

**Comment by VictorLazlow** [comment]
Perdón por las molestias que puede ocasionar.
He instalado todo y la primera canción se ha descompuesto bien, pero intento hacerlo otra vez y me salen los siguientes errores de la canción p.mp3
![Sin título-2](https://user-images.githubusercontent.com/62949758/78047948-4b501d00-7379-11ea-87a4-63abc5b2f105.jpg)
 y los siguientes de la otra.
![Sin título-3](https://user-images.githubusercontent.com/62949758/78048004-5efb8380-7379-11ea-95d5-5dc643eb2c14.jpg)


Muchas gracias

**Comment by enzoman123** [comment]
Disculpen no puedo hacer el enviroment en demucs me dice que no lo encuentra

**Comment by enzoman123** [comment]
disculpen cuando uso el codigo conda env update -f environment-cuda.yml el programa no me deja hacer el enviroment

**Comment by julitoxx** [comment]
Hola. Los mayores problemas sobre todo los del principio son por no leer y correr. No hay que usar el cmd o el powershell, debes utilizar la consola del programa que habeis instalado previamente. Y que pone en el menu de inicio (Anaconda Prompt (Anaconda3)). Ese programa ya abre la consola de comandos en los que introducir los datos, Me imagino que por tema de variables de recursos. En cuanto a su uso funciona y bastante bien. Tal y como dice Jaime. Añadir que cuando meteis los comando de inicio lo primero que hace es cargar los modelos que ya tiene predefinidos y entrenados. Esto lo hace solo una vez, tarda un poco, Luego ya los deja cargados y se pondra a desmenuzar los sonidos de los archivos que le digais. Suerte!
