### ISSUE TITLE
IndexError in apply_model when using `mdx_extra`

### ISSUE THREAD

**Issue by keunwoochoi** [facebookresearch/demucs#240]
Depending on the batch size, [this line](https://github.com/facebookresearch/demucs/blob/main/demucs/apply.py#L145) throws an error:

```
IndexError: list index out of range
```

The reason seems clear to me. In this code:
```
        for sub_model, weight in zip(model.models, model.weights):
            out = apply_model(
                sub_model, mix,
                shifts=shifts, split=split, overlap=overlap,
                transition_power=transition_power, progress=progress)
            for k in range(out.shape[0]):
                out[k] *= weight[k]  # <- here 
                totals[k] += weight[k]
            estimates += out
```
it's probably `weight[k]` since `len(weights)` is shorter than `out.shape[0]`, the batch size.

or am I missing something?

in my case, `mix` is a batch; something like `(batch, ch=2, time)`.

**Comment by adefossez** [comment]
Thanks for reporting. I definitely got mixed up with the dimensions (the weights should be over sources not batch entries) when I wrote this code and somehow it is working okay only for a batch size of 1. I'll fix this tomorrow :)
