### ISSUE TITLE
Help in custom training

### ISSUE THREAD

**Issue by johndpope** [facebookresearch/demucs#243]
## ❓ Questions

Background

I’ve been using spleeter for years and it works well. I’m not looking to replace it / but interested in custom training for drum detection / high hat / kick / snare

This training config is very straightforward 

https://github.com/deezer/spleeter/blob/master/configs/musdb_config.json

just point to a training csv
https://github.com/deezer/spleeter/blob/master/configs/musdb_train.csv

And corresponding validation csv
https://github.com/deezer/spleeter/blob/master/configs/musdb_validation.csv

I spent a few minutes looking through this library and got my head up to speed with Dora 

I don’t see something as simple as above example in this repo. 

I’m not interested in hq test dataset will be bringing my own. Just want to provide 
Song-mix.wav song-kick.wav song-snare.wav song-drum.wav in a csv and then point training at it.

Update
For clarity I don’t need / want detection for piano / vocals etc - I only want to use this model for drum stem separation. If you can help me build one - that would be great too. Speaking for everyone.

related 
https://github.com/facebookresearch/demucs/issues/128

**Comment by johndpope** [comment]
found this - https://github.com/Xirzag/TFM-Audio-Dereverberation/issues/1

**Comment by adefossez** [comment]
See https://github.com/facebookresearch/demucs/issues/221 for details on how to do this !

**Comment by johndpope** [comment]
Thank you
