### ISSUE TITLE
Colab Notebook - Not Downloading

### ISSUE THREAD

**Issue by StormProductionsMusic** [facebookresearch/demucs#247]
## ❓ Questions

Hi,
 
I just tried the Demucs Collab Notebook, and the downloading feature doesn’t work. Basically, I uploaded the song, it has been processed, but no downloads after that. 
 
Am I missing something?

Thanks.

**Comment by adefossez** [comment]
Could you share a screenshot of the output from google colab ?

**Comment by StormProductionsMusic** [comment]
I tried processing another song to make a screenshot for you, and another issues popped up: 

![image](https://user-images.githubusercontent.com/86001751/145583919-ff3aa9fe-4431-4cb8-bb57-ee80bced0f93.png)

Is something wrong on my end?

**Comment by adefossez** [comment]
Okay so you did not execute one of the cells above, the one called `Useful functions, don't forget to execute`.
By the way are you using google drive or not ? because if the first function did not execute it means the audio was never actually processed or uploaded. if youare using drive you don't need this part.

**Comment by StormProductionsMusic** [comment]
No, i want to use the manual upload only. The Drive thing doesn't add the Demucs folder to my Drive so I want to use the manual upload instead.

**Comment by StormProductionsMusic** [comment]
Okay, so I managed to process another song again, and here's the output:

![image](https://user-images.githubusercontent.com/86001751/145589562-2d042f8d-b5d0-4386-ad3f-0be0d68dd471.png)

Thanks.

**Comment by adefossez** [comment]
you would have to be patient but eventually the colab tab will offer the download once the zip is created.

**Comment by StormProductionsMusic** [comment]
I did, I'm still on the page I made the screenshot on. And still nothing. I tried on multiple devices and networks so it's not on my end.

**Comment by adefossez** [comment]
can you add a new cell of code after, and type again only `files.download('./separated.zip')` ? you can also browse the local files on the colab on the left, you should be able to see the generated files there.

**Comment by StormProductionsMusic** [comment]
Thanks, fixed through the left files tab, much appreciated!
