### ISSUE TITLE
It will not let me export in wav

### ISSUE THREAD

**Issue by JpJpSoundcloud** [facebookresearch/demucs#249]
Hi, i'm trying to separate a song in hq (wav file) and demucs exports the stems in mp3 i don't know why, can somebody help me to make demucs export the stems in wav so it doesn't lose any quality?
(I'm using demucs in Google Collab btw)

**Comment by adefossez** [comment]
In the options parts set `mp3 = False`

**Comment by JpJpSoundcloud** [comment]
@adefossez thank you so much! it works now :)

**Comment by JpJpSoundcloud** [comment]
btw, i'm really thankful for all of the work that the people behind demucs has done!

**Comment by adefossez** [comment]
thank you for your kind words :) glad it is useful to you ! I will close the issue now.
