### ISSUE TITLE
ayuda con problema ffmpeg y pythorch

### ISSUE THREAD

**Issue by subzero160** [facebookresearch/demucs#25]
ayuda e sale este error

ResolvePackageNotFound: 
- ffmpeg==4.2
- pytorch=1.3.1

**Comment by rokimoki** [comment]
Creo que es porque no has instalado las dependencias, debes situarte con el entorno Anaconda en la carpeta de demucs-master e instalarlos:
`conda env update -f environment-cpu.yml`

**Comment by subzero160** [comment]
ya lo hice, de hecho cuando pongo eso 
**conda env update -f environment-cpu.yml**
es cuando me da ese error

**Comment by subzero160** [comment]
> 
> 
> Creo que es porque no has instalado las dependencias, debes situarte con el entorno Anaconda en la carpeta de demucs-master e instalarlos:
> `conda env update -f environment-cpu.yml`
> 
> EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)

si, ya intente todo eso y me sale lo mismo, sera que el problema es porque mi sistema es 32bits?

**Comment by rokimoki** [comment]
> > Creo que es porque no has instalado las dependencias, debes situarte con el entorno Anaconda en la carpeta de demucs-master e instalarlos:
> > `conda env update -f environment-cpu.yml`
> > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> 
> si, ya intente todo eso y me sale lo mismo, sera que el problema es porque mi sistema es 32bits?

En principio si tu sistema es de 32bits, puedes instalar anaconda para python 3.7 de 32 bits. Puede ser que no existan esas depedencias en python de 32 bits, pero me extraña. Yo lo he probado únicamente en Windows 10 64 bits. Lo siento.

**Comment by subzero160** [comment]
> 
> 
> > > Creo que es porque no has instalado las dependencias, debes situarte con el entorno Anaconda en la carpeta de demucs-master e instalarlos:
> > > `conda env update -f environment-cpu.yml`
> > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > 
> > 
> > si, ya intente todo eso y me sale lo mismo, sera que el problema es porque mi sistema es 32bits?
> 
> En principio si tu sistema es de 32bits, puedes instalar anaconda para python 3.7 de 32 bits. Puede ser que no existan esas depedencias en python de 32 bits, pero me extraña. Yo lo he probado únicamente en Windows 10 64 bits. Lo siento.

si ya investigue bien y es por eso, pytorch no hay para 32bits solo 64bits :(

**Comment by rokimoki** [comment]
> > > > Creo que es porque no has instalado las dependencias, debes situarte con el entorno Anaconda en la carpeta de demucs-master e instalarlos:
> > > > `conda env update -f environment-cpu.yml`
> > > > EDITO: Respuesta encontrada [#8 (comment)](https://github.com/facebookresearch/demucs/issues/8#issuecomment-562715299)
> > > 
> > > 
> > > si, ya intente todo eso y me sale lo mismo, sera que el problema es porque mi sistema es 32bits?
> > 
> > 
> > En principio si tu sistema es de 32bits, puedes instalar anaconda para python 3.7 de 32 bits. Puede ser que no existan esas depedencias en python de 32 bits, pero me extraña. Yo lo he probado únicamente en Windows 10 64 bits. Lo siento.
> 
> si ya investigue bien y es por eso, pytorch no hay para 32bits solo 64bits :(

Qué CPU tienes? y que SO tienes ahora?

**Comment by adefossez** [comment]
@subzero160 , indeed 32bits is not supported by Pytorch :/ I have updated the README to make that clear. Thanks @rokimoki  for helping on all the issues!
