### ISSUE TITLE
how to seperate vocal only

### ISSUE THREAD

**Issue by Liuyang0001** [facebookresearch/demucs#250]
## ❓ Questions

(Please ask your question here.)
I only want to genarate the vocal of every speech，what should i do？
I used cmd line run `python3 -m demucs.separate *.wav  -o sep_out -n mdx_extra -d cpu`, but cost too many time. 
Thanks.

**Comment by adefossez** [comment]
It is not possible to separate vocals only sadly, as the models are trained to separate all sources at once.

**Comment by weirenlan** [comment]
@adefossez 
I have a same situation about separating drum's sound directly.
I tried it by these setting could cause different time spent to separate.

```
from demucs.apply import apply_mode
from demucs import pretrained
model = pretrained.get_model('mdx_extra')
sample_track="input.wav"
wav = separate.load_track(sample_track, 'cpu',model.audio_channels, model.samplerate)
```

- Only pass part of model to apply. According to your default setting, model.models[0] may be for `drums`. If i only pass part of model, I could get the separated result and reduce the time.
```
out = apply_model(model.models[0], wav[None],shifts=1,split=True,overlap=0.25, progress=True)[0]
```
<img width="1093" alt="圖片" src="https://user-images.githubusercontent.com/76981114/147757058-3ccc8d2f-0243-44ec-9ab0-3c7800c4645d.png">

- Pass the total models to apply function
```
out = apply_model(model, wav[None],shifts=1,split=True,overlap=0.25, progress=True)[0]
```
<img width="1107" alt="圖片" src="https://user-images.githubusercontent.com/76981114/147757028-a1868585-f440-4ff6-96fa-f019712b8a6f.png">
