### ISSUE TITLE
Demucs V3 Hybrid Colab "Command failed, something went wrong."

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [facebookresearch/demucs#259]
I recently made a tutorial on how to work with this version of Demucs for users who don't have a beefy PC, and a viewer commented an error happening on their end and I went to try it out myself and it gave me the same error as them.

Saving 03. Born Under a Bad Sign.flac to 03. Born Under a Bad Sign.flac
Going to separate the files:
tmp_in/03. Born Under a Bad Sign.flac
With command:  python3 -m demucs.separate -o separated -n mdx_extra
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/e51eebcc-c1b80bdd.th" to /root/.cache/torch/hub/checkpoints/e51eebcc-c1b80bdd.th
100%|██████████| 160M/160M [00:04<00:00, 34.4MB/s]
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/a1d90b5c-ae9d2452.th" to /root/.cache/torch/hub/checkpoints/a1d90b5c-ae9d2452.th
100%|██████████| 160M/160M [00:04<00:00, 35.0MB/s]
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/5d2d6c55-db83574e.th" to /root/.cache/torch/hub/checkpoints/5d2d6c55-db83574e.th
100%|██████████| 160M/160M [00:12<00:00, 13.9MB/s]
Downloading: "https://dl.fbaipublicfiles.com/demucs/mdx_final/cfa93e08-61801ae1.th" to /root/.cache/torch/hub/checkpoints/cfa93e08-61801ae1.th
100%|██████████| 160M/160M [00:05<00:00, 30.6MB/s]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 142, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 127, in main
    num_workers=args.jobs)[0]
  File "/usr/local/lib/python3.7/dist-packages/demucs/apply.py", line 167, in apply_model
    out = apply_model(sub_model, mix, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/demucs/apply.py", line 202, in apply_model
    future = pool.submit(apply_model, model, chunk, **kwargs)
AttributeError: 'NoneType' object has no attribute 'submit'
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in /content/separated/mdx_extra
Separating track tmp_in/03. Born Under a Bad Sign.flac
Command failed, something went wrong.
updating: separated/ (stored 0%)
  adding: separated/mdx_extra/ (stored 0%)

**Comment by adefossez** [comment]
same as https://github.com/facebookresearch/demucs/issues/258
Sorry about that, should be fixed now if you update with `python.exe -m pip install -U demucs`.

**Comment by OktoberfestThePlayer** [comment]
on which cell line should I put it in?

**Comment by JeffreyCA** [comment]
If you're using the included notebook (Demucs.ipynb), rerunning the first cell should do the trick:

```
!pip install -U demucs
```

**Comment by OktoberfestThePlayer** [comment]
Got it working now, thank you!
