### ISSUE TITLE
No se como continuar 

### ISSUE THREAD

**Issue by Bonilla999** [facebookresearch/demucs#26]
![image](https://user-images.githubusercontent.com/58631292/70376083-7e236080-1905-11ea-83cd-f695fcb1efab.png)

(demucs) C:\Users\user\Desktop\demucs-master>python.exe -m demucs.separate --dl -n demucs C:\Users\user\Desktop\Two Feet - Pink.mp3
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\demucs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Desktop\demucs-master\demucs\separate.py", line 143, in <module>
    main()
  File "C:\Users\user\Desktop\demucs-master\demucs\separate.py", line 122, in main
    model = th.load(model_path).to(args.device)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 426, in to
    return self._apply(convert)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 202, in _apply
    module._apply(fn)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 224, in _apply
    param_applied = fn(param)
  File "C:\Users\user\Anaconda3\envs\demucs\lib\site-packages\torch\nn\modules\module.py", line 424, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 1024.00 MiB total capacity; 548.16 MiB already allocated; 145.83 MiB free; 7.84 MiB cached)

**Comment by KikoLaudero** [comment]
Con respecto a tu problema, entiendo que dice que CUDA (tu gráfica) se quedó sin memoria. Necesita 158Mb en tu caso pero sólo tenía 145mb disponibles. Si no sabes como liberar memoria gráfica Intenta correrlo como CPU.
`conda env update -f environment-cpu.yml`

Yo no he llegado tan lejos, a mí me da un error "MKL FATAL ERROR on load the function mkl_blas_xsdot"
Una pregunta, cómo lo corres tú?

**Comment by rokimoki** [comment]
Escribe así el comando `python.exe -m demucs.separate --dl -n demucs "C:\Users\user\Desktop\Two Feet - Pink.mp3" -d cpu`

Básicamente la dirección del MP3 entre comillas (te sirve arrastrar el mp3 a la consola de comandos), además con el argumento extra `d -cpu` que va a forzar a ejecutarse con la CPU y no con la GPU, yo tengo 6gb de memoria de GPU y también me da error de memoria,imaginate con 1GB.

Si instalaste en entorno GPU no te preocupes, no hace falta instalar nada extra manualmente, lo que te va a descargar a continuación es un fichero demucs.tml de 2,5gb aproximadamente que es un modelo de la red entrenado.

Yo con un i7-3770 me tarda una media de 3,5 minutos en separar las canciones.

Saludos.

**Comment by rokimoki** [comment]
> Con respecto a tu problema, entiendo que dice que CUDA (tu gráfica) se quedó sin memoria. Necesita 158Mb en tu caso pero sólo tenía 145mb disponibles. Si no sabes como liberar memoria gráfica Intenta correrlo como CPU.
> `conda env update -f environment-cpu.yml`
> 
> Yo no he llegado tan lejos, a mí me da un error "MKL FATAL ERROR on load the function mkl_blas_xsdot"
> Una pregunta, cómo lo corres tú?

Pega un pantallazo del comando que ejecutas, y la salida de la consola.

**Comment by Richa312rds** [comment]
Yo he instalado anaconda  desde donde seria mejor correr desde la CMD del windown bajo administrado o mejor correrlo en anaconda y como lo hago gracias..

**Comment by rokimoki** [comment]
> Yo he instalado anaconda desde donde seria mejor correr desde la CMD del windown bajo administrado o mejor correrlo en anaconda y como lo hago gracias..

Ejecuta la consola de anaconda, no necesitarías modo administrador si la ruta del archivo de música está en un directorio del mismo usuario que ejecuta anaconda.

**Comment by Bonilla999** [comment]
me ha funcionado forzandolo con la cpu 
![image](https://user-images.githubusercontent.com/58631292/70389418-47aa1c00-19bf-11ea-8b4d-bb15d7fb4d55.png)

gracias

**Comment by adefossez** [comment]
Sorry for my late reply @Bonilla999 , I have updated the README to make that clear !
