### ISSUE TITLE
time or frequency based

### ISSUE THREAD

**Issue by DiegoLigtenberg** [facebookresearch/demucs#261]
When I read the paper, I get that demucs is inspired from TASNET which operates purely on the waveforms and not on spectrograms,
also in the paper of demucs I thought you guys were copying mostly TASNET, but in this github I see spectrograms?

please help me clear my misunderstanding, are we generating the new sources directly from the original mix or do we still first use the STFT to generate spectrograms?

**Comment by adefossez** [comment]
after our discussion online I will be closing the issue.
