### ISSUE TITLE
Got the following errors while running the Google Colab script

### ISSUE THREAD

**Issue by thenormal** [facebookresearch/demucs#262]
## ❓ Questions

![screenshot-colab research google com-2021 12 24-09_14_47](https://user-images.githubusercontent.com/28772244/147333561-0752dc48-11c8-43ba-9ebf-099bd24e499b.png)

**Comment by halfbrilliant** [comment]
We can’t see the command you issued to get this. Is this your first attempt at running it? It looks like a CUDA error, so you could try disabling that. 
If you haven’t already tried,  `demucs -d cpu {yourfilepath}` performs the task on your CPU only.

**Comment by adefossez** [comment]
is the file you are trying to separate large ? this could be an out of memory error in disguise. Retrying from a clean colab notebook should do the trick (Execution > reset execution environment, or something like that, I have it in French on my end).

**Comment by thenormal** [comment]
Restarting google colab fixed the issue for me

**Comment by adefossez** [comment]
closing now, feel free to reopen if the issue persist.
