### ISSUE TITLE
Can DEMUCS process a 1Gb ?

### ISSUE THREAD

**Issue by zdhernandez** [facebookresearch/demucs#263]
## ❓ Questions

GPU-specific question:
Can DEMUCS process a 1Gb video assuming that a GPU has 16Gb of memory? Does the entire file goes into the GPU memory at processing time or does it segments portions of a video while doing its inference and/or does it saves progress during the process?
What is the mechanism in terms of handling a large video file 1Gb+?

**Comment by adefossez** [comment]
Yes, you can process large files with the latest release of Demucs, be sure to upgrade. This is thanks to @famzah work, but you seem to be aware of that from the other issue you opened. It will not save partial results though, so you must wait for the entire process to complete.
