### ISSUE TITLE
mkl problems

### ISSUE THREAD

**Issue by KikoLaudero** [facebookresearch/demucs#27]
Hi!

It's my first time on this.
I try to run it but I can't

run "anaconda prompt" then update and activate
`(demucs) C: \ Users \ pixel \ demucs> python.exe -m demucs.separate --dl -n demucsC: \ Reptilia.mp3
INTEL MKL ERROR: The operating system cannot execute% 1. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.`

So I tryed replace "mkl_intel_thread.dll" on / Anaconda3 / envs / Demucs / Library / bin / for "mkl_intel_thread.dll" from system32/ and another error:

`(demucs) C: \ Users \ pixel \ demucs> python.exe -m demucs.separate --dl -n demucsC: \ Reptilia.mp3
MKL FATAL ERROR on load the function mkl_blas_xsdot`

I need something?

**Comment by rokimoki** [comment]
Check this link: https://github.com/facebookresearch/demucs/issues/20#issue-534304999 and the link inside to a comment section.

**Comment by KikoLaudero** [comment]
> Check this link: [#20 (comment)](https://github.com/facebookresearch/demucs/issues/20#issue-534304999) and the link inside to a comment section.

Thankyou so much!
