### ISSUE TITLE
Separation is very quick and very bad resulting audio quality

### ISSUE THREAD

**Issue by rocvela27** [facebookresearch/demucs#271]
1 Question

I have been battling for more than 8hours trying to make demucs work, but I don't know what the problem might be. I have read numerous issues and can't still find a solution. I have a MacOS 10.15.17 (i5 16GB); I've tried uninstalling python to a lesser version (3.7.9), reinstalling demucs, using Anaconda...

When I try to separate tracks using the MacOS command as stated in the instructions, I get:

python3 -m demucs -d cpu /Users/catalogmsmt/Downloads/E\ Se\ Domani\ pano.mp3
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in /Users/catalogmsmt/Documents/Track instruments separator/demucs/separated/mdx_extra_q
Separating track /Users/catalogmsmt/Downloads/E Se Domani pano.mp3
dyld: Library not loaded: @rpath/libopenh264.5.dylib
  Referenced from: /Applications/anaconda3/envs/demucs/lib/libavcodec.58.91.100.dylib
  Reason: image not found
  0%|                                                                           100%|█████████████████████████████████████████████████████████████████████████| 100%|█████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 115.03seconds/s]
  0%|                                                                           100%|█████████████████████████████████████████████████████████████████████████| 100%|█████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 174.58seconds/s]
  0%|                                                                           100%|█████████████████████████████████████████████████████████████████████████| 100%|█████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 122.21seconds/s]
  0%|                                                                           100%|█████████████████████████████████████████████████████████████████████████| 100%|█████████████████████████████████████████████████████████████████████████| 33.0/33.0 [00:00<00:00, 159.52seconds/s]

As you'll see the time is incredibly quick, so the resulting tracks are under a second long and sound very weird.

Does anybody know what might be happening? I've tried to use different commands as seen in other threads, but still haven't found a solution.

Is there a way to completely delete everything and make another install, maybe going back to a different version? I've tried doing so but the problem persists... There might be a problem with dependencies.

Thanks in advance!

**Comment by rocvela27** [comment]
I have found the issue! This is very weird: the mp3 I had is somewhat corrupted: I downloaded from a Youtube-to-mp3 website, so the metadata for that file has the "origin/source" and it detects it as illegal, I suppose.

The file cannot be opened with Mac's default Music player (nor imported to DAWs like Logic, I've tried), but the weird thing is, it can be played with the 'preview' player, so it definitely works (I've imported it to online waveform generators and it works well).

Is there a possibility that demucs considers it fraudulent as well so it doesn't separate it? Was this a known issue or have I discovered a bug? I wanted to change the label from question to bug but I want to be sure first.

Thanks for the amazing work! I'm attaching the file in case you want to delve into it further :)

[https://drive.google.com/file/d/1kSeSdvI9qdD_-spUCrMmPEyDpZDirNyr/view?usp=sharing](url)

**Comment by wilxpl300** [comment]
Indeed, the file is damaged and for this reason, demucs could not convert it, I recommend that you download the "original" songs in FLAC and not from "youtube-to-mp3" pages.

A page that I recommend is: https://free-mp3-download.net/

Psdt: sorry for my bad english, I'm using google translator 🥺

**Comment by CarlGao4** [comment]
If you have found that it is a problem have something to do with file type, please try converting it. You can download [FFMpeg build for Mac here](https://evermeet.cx/ffmpeg/ffmpeg-4.4.1.7z) and run `./ffmpeg -i your_file.mp3 out.wav` in your terminal. The output file may be very big, but you can delete it after separating the new wav file. This may help.

**Comment by CarlGao4** [comment]
I converted it for you. Does this file can be separated?
[Mina - E se domani (1967) HQ.wav.zip](https://github.com/facebookresearch/demucs/files/7844933/Mina.-.E.se.domani.1967.HQ.wav.zip)

**Comment by Kwisss** [comment]
I would recommend using Youtube-dl, that way you will enjoy the highest quality and can stay in terminal.
I use
`c:\youtube-dl -f 251 https://www.youtube.com/watch?v=dQw4w9WgXcQ -x --audio-format wav -o c:/%(title)s-%(id)s.%(ext)s `
 and
`python -m demucs -n mdx_extra -d cpu "c:\Downloaded Song.wav" -o "c:/"`

Please do remember that it is probably against YouTube terms to download any other video then your own

**Comment by rocvela27** [comment]
Thank you all for your help and insight!!! :D Amazing stuff, thanks for sharing.

I still find it weird for some .mp3 to have information and sound okay in the preview but still being unable to be opened in DAWs or demucs - but hey! It's all good :)

**Comment by adefossez** [comment]
Thanks a lot everyone for jumping on this issue and solving it !
