### ISSUE TITLE
Gradio demo gives error doesn't work anymore

### ISSUE THREAD

**Issue by vespersland** [facebookresearch/demucs#274]
## 🐛 Bug Report
a few days ago Gradio demo has stopped working, the rendering freezes and gives an error
Any suggestion?i don't know but probably server is too busy

## To Reproduce

1. Upload a track on gradio demo
2. submit for render
3. response error

## Environment https://huggingface.co/spaces/akhaliq/demucs

- Gradio demo for Demucs: Music Source Separation in the Waveform Domain

**Comment by adefossez** [comment]
What is the error you aregetting ? could you upload a screenshot ? cc @AK391

**Comment by AK391** [comment]
@adefossez checking this now, getting a urllib.error.HTTPError: HTTP Error 403: Forbidden, ill look into it

**Comment by AK391** [comment]
might be related to downloading checkpoints from torch hub

**Comment by AK391** [comment]
@adefossez hosting the models on huggingface hub might help with these types of issues, https://huggingface.co/models, I can help with migrating them to hf hub

**Comment by vespersland** [comment]
> What is the error you aregetting ? could you upload a screenshot ? cc @AK391

Thanks in advance

[](url
![screenshot](https://user-images.githubusercontent.com/37030654/150339223-b69b72b4-d290-4f8a-8ed2-d2fb90b30b82.png)
)

**Comment by vitacon** [comment]
I think the whole Huggingface has been "somewhat damaged" for a few days. =P

**Comment by adefossez** [comment]
@AK391 if you have the time to do it that would be awesome, otherwise let me know what are the instructions to follow.

**Comment by AK391** [comment]
@adefossez thanks, I have added the models here https://huggingface.co/akhaliq/Demucs/tree/main

**Comment by adefossez** [comment]
thanks a lot @AK391 !

**Comment by AK391** [comment]
@adefossez the files can be downloaded from the hub using 

`from huggingface_hub import hf_hub_download
`
more here: https://huggingface.co/docs/hub/how-to-downstream
