### ISSUE TITLE
RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

### ISSUE THREAD

**Issue by labilizations79** [facebookresearch/demucs#276]
## ❓ Questions
When i run demucs with commanline "python3 -m demucs.separate -d cpu "./test.mp3" "
The  RuntimeError: min(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument was occurrd. 
![image](https://user-images.githubusercontent.com/97420856/150283627-b7a2a868-6a8c-4515-9247-619c04a2e8d7.png)
how to deal with it? thanks

(Please ask your question here.)

**Comment by labilizations79** [comment]
The same error was occurred when i run the v3. with command "demucs /home/jiangyi/code/demucs/test_mono.mp3"
![image](https://user-images.githubusercontent.com/97420856/150284467-a5b0e9a0-40c5-4ec1-be47-3aa9389952f4.png)

how to deal with it? thanks

**Comment by CarlGao4** [comment]
Though demucs requires at least python3.8, it works better with python3.9. Maybe you can try with python3.9?

**Comment by labilizations79** [comment]
Thanks. I tried with python3.9, But the error is still there. 
![image](https://user-images.githubusercontent.com/97420856/150309928-39b2133d-8863-448b-a9b3-959ff1fad16b.png)

**Comment by labilizations79** [comment]
fine, i got it with conda!

**Comment by flashasdbaksdgi** [comment]
> 

Hi  could u please tell me how u fixed it?

**Comment by labilizations** [comment]
You can setup a environment in windows with Conda, and try it again.

**Comment by flashasdbaksdgi** [comment]
> 

Thanks！

**Comment by ApoorvaSuresh** [comment]
Hi, I have the same error :( Did you find a solution for it? If so, could you please share it?
My environment was setup with conda, but this error is still there.
Thanks in advance :)

**Comment by Wuuu-L** [comment]
> You can setup a environment in windows with Conda, and try it again.

Hi, I have met the same situation like that, could you please share a detailed way, thanks a lot.
