### ISSUE TITLE
Please add a command so all of the audio files included in a given folder will be processed

### ISSUE THREAD

**Issue by thenormal** [facebookresearch/demucs#278]
## ❓ Questions

Hello. I'm currently using Demucs on a Windows machine using the instructions given here: https://github.com/facebookresearch/demucs/blob/main/docs/windows.md

Everything seems to be working so far, but one thing that is a bit annoying to me is the fact that you have to type every single folder path and file name in a queue style, if you want more than one file to be processed. For instance, this is the default command I use:

demucs -d cpu --two-stems vocals --mp3 --mp3-bitrate 320 -n mdx_extra "FOLDER"

So if I wanted to process file test.mp3 located under c:\audio\test.mp3, I would use:

demucs -d cpu --two-stems vocals --mp3 --mp3-bitrate 320 -n mdx_extra "c:\audio\test.mp3"

Ok, but what if I had like 20 audio files in such folder. It would be a lot time consuming to type out every single file, ultimately the command line would be very long as well.

Maybe there is a way to have all of the files within a folder processed, I haven't found one yet.

**Comment by CarlGao4** [comment]
Since you are using Windows, it is unnecessary to add an option like this. Using a `for` command is enough. Such as `for %i in (*.mp3) do (demucs --mp3 %i)`. You can google for further usage of this command. 
Note that you should use `%%i` instead of `%it if you are using the command in a `.cmd` or `.bat` file.

**Comment by thenormal** [comment]
I appreciate the insight and I tried my best to make it work, but I couldn't. How would I modify the following command in order to achieve my goal?

demucs -d cpu --two-stems vocals --mp3 --mp3-bitrate 320 -n mdx_extra "FOLDER"

**Comment by CarlGao4** [comment]
You can try this:
```bash
cd FOLDER
for %i in (*.mp3) do (demucs -d cpu --two-stems vocals --mp3 --mp3-bitrate 320 -n mdx_extra "%i")
```

**Comment by thenormal** [comment]
> You can try this:
> 
> ```shell
> cd FOLDER
> for %i in (*.mp3) do (demucs -d cpu --two-stems vocals --mp3 --mp3-bitrate 320 -n mdx_extra "%i")
> ```

That actually did the trick! Thanks a lot for the insight

**Comment by adefossez** [comment]
I added the command to the windows instructions (https://github.com/facebookresearch/demucs/blob/main/docs/windows.md) thanks a lot @CarlGao4
