### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by palindrome991** [facebookresearch/demucs#28]
After installing demucs using Anaconda without any type of problem everytime I've tried to separate an audio file what I get is the following error:

`(demucs) bash-3.2$ python3 -m demucs.separate --dl /Users/admin/Desktop/7.mp3`
`/Users/admin/opt/anaconda3/envs/demucs/bin/python3: Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')`

I checked and the demucs enviroment in anaconda seems to be installed. I've tried to solve it by reinstalling it (even reinstalling Anaconda to an updated version) but it keeps not working. 

Thanks,

**Comment by rokimoki** [comment]
Try this: `python3 -m demucs.separate --dl -n demucs /Users/admin/Desktop/7.mp3` if it doesn't work, add `-d cpu` at the end like this `python3 -m demucs.separate --dl -n demucs /Users/admin/Desktop/7.mp3 -d cpu`. You missed `-n demucs` in command specification.

**Comment by palindrome991** [comment]
It still doesn't work, the same error message again

**Comment by adefossez** [comment]
Hey @palindrome991 , sorry for my late reply, are you running from the root of the repository? If not, first `cd` into that directory and hopefully it should work!

**Comment by palindrome991** [comment]
Now it works but the performance is terrible, first time the separation process began but when it reached 100% my computer froze so I had to reboot the system I tried again and it froze right when I pressed enter (before even starting to separate).

**Comment by adefossez** [comment]
how much RAM do you have?

**Comment by palindrome991** [comment]
4 GB 1333 MHz DDR3

**Comment by ibeats1music** [comment]
Hi,
I have your initial problem
How did you solve that problem?

![no module named demucs](https://user-images.githubusercontent.com/58677673/70670101-23ac3c00-1c46-11ea-85df-8ffb7e2699c8.jpg)


I want to experiment if the problem is RAM

RAM: 12 GB DDR3

**Comment by rokimoki** [comment]
> Hi,
> I have your initial problem
> How did you solve that problem?
> 
> ![no module named demucs](https://user-images.githubusercontent.com/58677673/70670101-23ac3c00-1c46-11ea-85df-8ffb7e2699c8.jpg)
> 
> I want to experiment if the problem is RAM
> 
> RAM: 12 GB DDR3

Why did you `cd %HOMEPATH%` after installing? thats before `git clone` in order to download in a "safe folder", you are not in the `demucs` path. 
`cd %HOMEPATH%`
`cd demucs`
`python.exe .............`

**Comment by ibeats1music** [comment]
Hi @rokimoki 
Thanks for taking the time to reply to the email. 
Problem solved :)
