### ISSUE TITLE
"--two-stems=vocals" not recognized

### ISSUE THREAD

**Issue by lucellent** [facebookresearch/demucs#280]
I just updated demucs and I've been trying to run this new feature, and placed it in all places possible in my code which I usually use for demucs, and it still continues saying that the argument is unrecognised. I also tried just " --two-stems vocals"

This is the code I usually use:

`demucs -n mdx_extra --overlap 0.15 PATH`

**Comment by CarlGao4** [comment]
This is a new feature added last week, and now it is labeled as alpha version, so it haven't been uploaded to PyPi right now. If you want to use this immediately, you can download the new [`separate.py`](https://github.com/facebookresearch/demucs/demucs/separate.py) and replace the original one under `YOUR_PYTHON_DIR/Lib/site-packages/demucs`.

**Comment by lucellent** [comment]
I did the following but it still looks like it doesn't recognise the argumen
<img width="690" alt="Screenshot_10" src="https://user-images.githubusercontent.com/38135928/150676598-445886a6-ae2c-4424-b2a8-89a4e480e93c.png">
t

**Comment by lucellent** [comment]
I found out the issue. As it shows in the arguments list, it's supposed to be `--two-stems vocals`, not  `--only-two-stems vocals`

**Comment by CarlGao4** [comment]
Congratulations!

**Comment by adefossez** [comment]
sorry about that I have updated the README !
