### ISSUE TITLE
error: unrecognized arguments: --two-stems=vocals

### ISSUE THREAD

**Issue by chigkim** [facebookresearch/demucs#287]
Readme says "If you only want to separate vocals out of an audio, use `--two-stems=vocal` (You can also set to drums or bass)"
When I run "demucs --two-stems=vocals test.wav",
I get "demucs.separate: error: unrecognized arguments: --two-stems=vocals".
demucs 3.0.3 from pip
python 3.9

**Comment by chigkim** [comment]
Installing the latest from git worked.

**Comment by adefossez** [comment]
yes, I haven't released the latest version yet :)
