### ISSUE TITLE
Example train log for "Improved V2 Demucs" and "Hybrid Demucs"

### ISSUE THREAD

**Issue by zbitouzakaria** [facebookresearch/demucs#290]
## ❓ Questions

Hello @adefossez,

First of all, thanks for providing such an invaluable resource for anyone looking to get their hands dirty on source separation.

Would it be possible to share a train log of the improved V2 and hybrid models ? It would tremendously help anyone willing to train demucs without the need of multiple Tesla V100 to replicate your results first.

I'm specifically interested in the plot of the [penalty field](https://github.com/facebookresearch/demucs/blob/main/demucs/solver.py#L242), and was wondering if it follows the same evolution as the singular values depicted in the Figure 4 of the paper [Spectral Norm Regularization for Improving the
Generalizability of Deep Learning](https://arxiv.org/abs/1705.10941), for the models trained by spectral norm regularization.

I don't really know what should I expect as good or bad behaviour for this metric.

Thanks !

**Comment by adefossez** [comment]
here are two logs, the file names are the signatures (https://github.com/facebookresearch/demucs/blob/main/docs/training.md#model-zoo)

i hope this helps !

[9357e12e.log](https://github.com/facebookresearch/demucs/files/8023428/9357e12e.log)
[81de367c.log](https://github.com/facebookresearch/demucs/files/8023426/81de367c.log)

**Comment by zbitouzakaria** [comment]
Yes it's very helpful, thanks a lot !
