### ISSUE TITLE
Problems with MusDB18 HQ Dataset

### ISSUE THREAD

**Issue by EdoGiordani99** [facebookresearch/demucs#295]
## ❓ Questions

Hi guys, 
I want to train a new model of h-demucs from Google Colab: to do that I'm following these instructions: 
https://github.com/facebookresearch/demucs/blob/main/docs/training.md

but when I train I get this error: 
num_samples should be a positive integer value, but got num_samples=0

I understood that I'm not importing well the dataset, but I couldn't figure out why. Does any of you trained the model on Colab? Could you please give me support on that?

**Comment by adefossez** [comment]
you probably haven't download the musdb HQ dataset ? in any case that is probably going to be challenging to do on colab, as the dataset is quite large.

**Comment by adefossez** [comment]
Please open a new issue if you still have an issue.
