### ISSUE TITLE
Module Not Found 

### ISSUE THREAD

**Issue by HistoreLaw** [facebookresearch/demucs#30]
Hi, i have this issue. I'm in Windows 10

(demucs) C:\Users\Admin>python.exe -m demucs.separate --dl -n demucs "C:\Users\Admin\Desktop\Music\01. Ben.mp3" -d cpu
C:\Users\Admin\Documents\Nueva carpeta\envs\demucs\python.exe: Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')

**Comment by viczav** [comment]
Greetings, HistoreLaw.
In the terminal, make sure you're located in the 'demucs-master' folder to be able to run the command.
(In that path, you're in the 'Admin' folder)
______

**Comment by adefossez** [comment]
Thanks @viczav for replying, I have updated the README to make that a bit clearer:
https://github.com/facebookresearch/demucs/blob/master/README.md#using-windows
