### ISSUE TITLE
--float32 command is not recognized

### ISSUE THREAD

**Issue by lucellent** [facebookresearch/demucs#301]
Just downloaded the newest version of demucs and trying to run it with the new --float32, but it says that it's not recognized

Do I have to tweak anything else?

**Comment by adefossez** [comment]
that is weird, it is working properly on my end. If you have multiple versions of pythons installed there can sometime be issues, you can do `python -m pip install -U demucs` and then `python -m demucs --float32 some_file.wav`  to make sure to have the right one.

**Comment by lucellent** [comment]
That seemed to have worked, thank you! Keep up the good work :) hope the models keep improving
