### ISSUE TITLE
TypeError: save() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [facebookresearch/demucs#302]
So I was trying out the new karaoke model for Demucs, and for some reason when I'm demixing a song, it gives me the following traceback.

(demucs) C:\Users\Diego\Documents\demucs>demucs --two-stems=vocals cuandomeenamoro.flac
C:\Users\Diego\anaconda3\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\Diego\Documents\demucs\separated\mdx_extra_q
Separating track cuandomeenamoro.flac
  0%|                                                                                  | 0.0/231.0 [00:00<?, ?seconds/s] 14%|██████████▍                                                              | 33.0/231.0 [00:12<01:13,  2.71seconds/s] 29%|████████████████████▊                                                    | 66.0/231.0 [00:24<01:00,  2.74seconds/s] 43%|███████████████████████████████▎                                         | 99.0/231.0 [00:36<00:48,  2.74seconds/s] 57%|█████████████████████████████████████████▏                              | 132.0/231.0 [00:48<00:35,  2.75seconds/s] 71%|███████████████████████████████████████████████████▍                    | 165.0/231.0 [00:59<00:23,  2.77seconds/s] 86%|█████████████████████████████████████████████████████████████▋          | 198.0/231.0 [01:09<00:11,  2.97seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:10<00:00,  4.28seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:10<00:00,  3.30seconds/s]
  0%|                                                                                  | 0.0/231.0 [00:00<?, ?seconds/s] 14%|██████████▍                                                              | 33.0/231.0 [00:12<01:14,  2.67seconds/s] 29%|████████████████████▊                                                    | 66.0/231.0 [00:24<01:02,  2.66seconds/s] 43%|███████████████████████████████▎                                         | 99.0/231.0 [00:37<00:49,  2.67seconds/s] 57%|█████████████████████████████████████████▏                              | 132.0/231.0 [00:49<00:36,  2.68seconds/s] 71%|███████████████████████████████████████████████████▍                    | 165.0/231.0 [01:01<00:24,  2.67seconds/s] 86%|█████████████████████████████████████████████████████████████▋          | 198.0/231.0 [01:11<00:11,  2.86seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:12<00:00,  4.12seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:12<00:00,  3.19seconds/s]
  0%|                                                                                  | 0.0/231.0 [00:00<?, ?seconds/s] 14%|██████████▍                                                              | 33.0/231.0 [00:12<01:15,  2.64seconds/s] 29%|████████████████████▊                                                    | 66.0/231.0 [00:24<01:02,  2.65seconds/s] 43%|███████████████████████████████▎                                         | 99.0/231.0 [00:37<00:49,  2.65seconds/s] 57%|█████████████████████████████████████████▏                              | 132.0/231.0 [00:49<00:37,  2.65seconds/s] 71%|███████████████████████████████████████████████████▍                    | 165.0/231.0 [01:02<00:24,  2.67seconds/s] 86%|█████████████████████████████████████████████████████████████▋          | 198.0/231.0 [01:12<00:11,  2.86seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:12<00:00,  4.11seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:12<00:00,  3.18seconds/s]
  0%|                                                                                  | 0.0/231.0 [00:00<?, ?seconds/s] 14%|██████████▍                                                              | 33.0/231.0 [00:12<01:12,  2.73seconds/s] 29%|████████████████████▊                                                    | 66.0/231.0 [00:24<01:01,  2.69seconds/s] 43%|███████████████████████████████▎                                         | 99.0/231.0 [00:36<00:48,  2.70seconds/s] 57%|█████████████████████████████████████████▏                              | 132.0/231.0 [00:48<00:36,  2.71seconds/s] 71%|███████████████████████████████████████████████████▍                    | 165.0/231.0 [01:01<00:24,  2.70seconds/s] 86%|█████████████████████████████████████████████████████████████▋          | 198.0/231.0 [01:10<00:11,  2.92seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:11<00:00,  4.20seconds/s]100%|████████████████████████████████████████████████████████████████████████| 231.0/231.0 [01:11<00:00,  3.24seconds/s]
Traceback (most recent call last):
  File "C:\Users\Diego\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Diego\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Diego\anaconda3\Scripts\demucs.exe\__main__.py", line 7, in <module>
  File "C:\Users\Diego\anaconda3\lib\site-packages\demucs\separate.py", line 163, in main
    save_audio(sources.pop(model.sources.index(args.stem)), stem, **kwargs)
  File "C:\Users\Diego\anaconda3\lib\site-packages\demucs\audio.py", line 253, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate,
TypeError: save() got an unexpected keyword argument 'encoding'

**Comment by OktoberfestThePlayer** [comment]
Nevermind, pip uninstall PySoundFile && pip install PySoundFile (in that order) fixed my issue!

**Comment by ObjectInSpace** [comment]
I got a similar error when attempting to run demux on a file the first time. The program generated an empty folder with the name of the track.

C:\Users\Drew\AppData\Local\Programs\Python\Python310\lib\site-packages\torchaudio\backend\utils.py:66: UserWarning: No audio backend is available.
  warnings.warn("No audio backend is available.")
Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in D:\Root\music\Arjen Lucasan\Ayreon - The Human Equation (2004) [CD - FLAC - Lossless] {IOMLTDCD 168}\disc 1\separated\mdx_extra_q
Separating track 02 - Day Two- Isolation.flac
100%|████████████████████████████████████████████████████████████████████████| 528.0/528.0 [05:28<00:00,  1.61seconds/s]
100%|████████████████████████████████████████████████████████████████████████| 528.0/528.0 [05:50<00:00,  1.51seconds/s]
100%|████████████████████████████████████████████████████████████████████████| 528.0/528.0 [05:44<00:00,  1.53seconds/s]
100%|████████████████████████████████████████████████████████████████████████| 528.0/528.0 [05:24<00:00,  1.63seconds/s]
Traceback (most recent call last):
  File "C:\Users\Drew\AppData\Local\Programs\Python\Python310\Scripts\demucs-script.py", line 33, in <module>
    sys.exit(load_entry_point('demucs==3.0.4', 'console_scripts', 'demucs')())
  File "C:\Users\Drew\AppData\Local\Programs\Python\Python310\lib\site-packages\demucs\separate.py", line 159, in main
    save_audio(source, stem, **kwargs)
  File "C:\Users\Drew\AppData\Local\Programs\Python\Python310\lib\site-packages\demucs\audio.py", line 253, in save_audio
    ta.save(str(path), wav, sample_rate=samplerate,
TypeError: save() got an unexpected keyword argument 'encoding'

pip install PySoundFile fixed the problem. Should this be added as a dependency?

**Comment by Ya-jiang** [comment]
Thank you very much!

**Comment by Cantersoft** [comment]
Thanks [ObjectInSpace](https://github.com/ObjectInSpace)! I needed to install PySoundFile.
