### ISSUE TITLE
Cannot make --float32 / --int24 work

### ISSUE THREAD

**Issue by deton24** [facebookresearch/demucs#304]
I'm using a custom version of Demucs 3 Colab with Gdrive integration and some other stuff.
It's perfect, I really recommend it:
https://colab.research.google.com/drive/1yyEe0m8t5b3i9FQkCl_iy6c9maF2brGx?usp=sharing

Unfortunately, when I add --float32 / --int24 anywhere when it's possible in the code, it simply doesn't work, showing errors of syntax due to commands not being recognized by the Demucs.

Could you look at the code, maybe explaining what's going on?

Having 24/32 bit would really help me during mixing some stuff using Demucs.
Regards

**Comment by adefossez** [comment]
could you send an example with the error you get ? by the way, i added it to the main colab in the repo, if you want to check it out.

**Comment by deton24** [comment]
Thank you so much for your reply!
Based on your Colab I added the option to the linked Colab above successfully
https://colab.research.google.com/drive/1Q-mD-ypAoaaTzmt52nMiml10Wz0NgOMT?usp=sharing
