### ISSUE TITLE
demucs.separate: error: the following arguments are required: tracks

### ISSUE THREAD

**Issue by PabloVargas19** [facebookresearch/demucs#31]
demucs.separate: error: the following arguments are required: tracks i have this problem, before this it works but the size of the file was 2GB

**Comment by SantiagomichInlilabongo** [comment]
En el momento que llegas a donde escribis python.exe -m demucs.separate -d cpu --dl AHÍ dejas el espacio y le tiras el archivo encima. Antes de darle enter te tendría que quedar así python.exe -m demucs.separate -d cpu --dl "C://user blabla bla /cancion.mp3   
cuando pegas lo de python NO DAS ENTER. Ahi das espacio y enseguida pones la pista y ahí si das ENTER , intenta con lo anterior

**Comment by SantiagomichInlilabongo** [comment]
En el momento que llegas a donde escribes python.exe -m demucs.separate -d cpu --dl AHÍ dejas el espacio y le tiras el archivo encima. Antes de darle acceso ingrese a tener que quedar así python.exe -m demucs.separate -d cpu --dl "C: // user blabla bla /cancion.mp3
cuando pegas lo de python NO DAS ENTER. Ahi das espacio y enseguida pones la pista y ahí si das ENTER, intenta con lo anterior
