### ISSUE TITLE
Demucs running successfully,but I have a confusion

### ISSUE THREAD

**Issue by HatherP** [facebookresearch/demucs#312]
## ❓ Questions
Hello,this is my first experience with this program.
I run it in anaconda, installed the ffmpeg & demucs.
Demucs running successfully,but there r some error 
![image](https://user-images.githubusercontent.com/63056057/161088069-5ec8114e-dc3b-468a-813b-eb0b7229167a.png)

(Please ask your question here.)
so why and how to solve

**Comment by CarlGao4** [comment]
### The first rectangle
PyTorchAudio can use different audio backends to read and write audio files. The default backend for Windows is `soundfile` and default for mac and Linux is `sox_io`. The Warning just tells you that some of the backends are not available. You neend't to worry about that since you are not using Windows. If you really don't want that to appear, please install `pySoundFile` in Python. 

---

### The second rectangle
This means that some of your packages is not installed correctly. Please reinstall FFMpeg and libopenh264 with your package manager.

**Comment by adefossez** [comment]
it doesn't look like it prevented anything to work in your case though. It probably means that your ffmpeg installation is a bit broken, but it seems good enough for loading audio files.

**Comment by HatherP** [comment]
> ### The first rectangle
> PyTorchAudio can use different audio backends to read and write audio files. The default backend for Windows is `soundfile` and default for mac and Linux is `sox_io`. The Warning just tells you that some of the backends are not available. You neend't to worry about that since you are not using Windows. If you really don't want that to appear, please install `pySoundFile` in Python.
> 
> ### The second rectangle
> This means that some of your packages is not installed correctly. Please reinstall FFMpeg and libopenh264 with your package manager.



> ### The first rectangle
> PyTorchAudio can use different audio backends to read and write audio files. The default backend for Windows is `soundfile` and default for mac and Linux is `sox_io`. The Warning just tells you that some of the backends are not available. You neend't to worry about that since you are not using Windows. If you really don't want that to appear, please install `pySoundFile` in Python.
> 
> ### The second rectangle
> This means that some of your packages is not installed correctly. Please reinstall FFMpeg and libopenh264 with your package manager.

Thank you for your reply.  How cani 

> ### The first rectangle
> PyTorchAudio can use different audio backends to read and write audio files. The default backend for Windows is `soundfile` and default for mac and Linux is `sox_io`. The Warning just tells you that some of the backends are not available. You neend't to worry about that since you are not using Windows. If you really don't want that to appear, please install `pySoundFile` in Python.
> 
> ### The second rectangle
> This means that some of your packages is not installed correctly. Please reinstall FFMpeg and libopenh264 with your package manager.

thank for 

> ### The first rectangle
> PyTorchAudio can use different audio backends to read and write audio files. The default backend for Windows is `soundfile` and default for mac and Linux is `sox_io`. The Warning just tells you that some of the backends are not available. You neend't to worry about that since you are not using Windows. If you really don't want that to appear, please install `pySoundFile` in Python.
> 
> ### The second rectangle
> This means that some of your packages is not installed correctly. Please reinstall FFMpeg and libopenh264 with your package manager.

Thank you for your reply.
Its Very effective.
And,what command do I execute if I just want to separate the audio into human and other sounds?
