### ISSUE TITLE
Unable to train

### ISSUE THREAD

**Issue by inagoy** [facebookresearch/demucs#317]
File "/content/demucs/demucs/train.py", line 14, in <module>
    from dora import hydra_main
ImportError: cannot import name 'hydra_main' from 'dora' (/usr/local/lib/python3.7/site-packages/dora/__init__.py)
FATAL: Failed to import module demucs.train.

I'm getting that error when i'm trying to train the model

**Comment by KimberleyJensen** [comment]
@inagoy type pip install -r requirements.txt

**Comment by inagoy** [comment]
Thanks!
