### ISSUE TITLE
Training: DDP is only available on GPU error

### ISSUE THREAD

**Issue by landboat** [facebookresearch/demucs#323]
## ❓ Questions

I am super new to AIs so I'm hoping my issue is something simple and obvious to people better versed than me.

I have set up my demucs environment and am attempting to train using one of the preexisting XPs as a baseline (81de367c to be exact). I followed all the instructions for the general setup, and I'm able to run the demucs command with the pretrained model on local files just fine. I am also able to run `dora info..` on the included XPs and have dealt with various package dependency kinks I had up till there.

When I try to execute `dora run -d -f 81de367c`, however,  I get the following error:
`FATAL: DDP is only available on GPU. Make sure GPUs are properly configured with cuda.`

I have tried looking up other people dealing with this error without luck. DDP seems to be a pytorch thing and I'm not sure if I need to address this by changing something about the demucs or pytorch config.

I think I have ruled out hardware/driver issues. I have freshly installed my driver and successfully run some of the CUDA examples from NVIDIA's github so CUDA itself seems to be working properly.

My setup is an AMD 5800X, 32GB RAM, Quadro RTX A4000 running Ubuntu 18.04

Would be very grateful if anyone can help me find the error in my ways!!

**Comment by heungky** [comment]
your error means no GPU is detected. Either you have installed the wrong pytorch version or the CUDA version is not correct.
Could I know your torch version? 
I had this error before, my solution is uninstalling torch and install again via https://pytorch.org [Compute Platform: CUDA] 
version of torch would be : 
torch                  1.11.0+cu113
torchaudio         0.11.0+cu113
torchvision         0.12.0+cu113

Hope it helps!

**Comment by landboat** [comment]
Thanks a bunch, Pytorch seems to have been the issue indeed.
I uninstalled it and then used the conda installer command from the link you sent and now we are all hunky dory!
