### ISSUE TITLE
Demucs Separate error

### ISSUE THREAD

**Issue by EANACORP** [facebookresearch/demucs#326]
(demucs) C:\Users\Oski\Desktop\demucs-main>python.exe -m demucs.separate -d cpu --dl C:\Users\Oski\Desktop\Pale_Yellow.mp3
usage: demucs.separate [-h] [-s SIG | -n NAME] [--repo REPO] [-v] [-o OUT] [-d DEVICE] [--shifts SHIFTS]
                       [--overlap OVERLAP] [--no-split | --segment SEGMENT] [--two-stems STEM] [--int24 | --float32]
                       [--clip-mode {rescale,clamp}] [--mp3] [--mp3-bitrate MP3_BITRATE] [-j JOBS]
                       tracks [tracks ...]
demucs.separate: error: unrecognized arguments: --dl

I have this problem, how can I fix it?
When I type: python.exe -m demucs.separate --dl C:\Users\Oski\Desktop\Song.mp3

**Comment by CarlGao4** [comment]
Use this:
`python.exe -m demucs.separate -d cpu C:\Users\Oski\Desktop\Pale_Yellow.mp3`

**Comment by EANACORP** [comment]
It works! thanks
