### ISSUE TITLE
A process in the process pool was terminated abruptly while the future was running or pending

### ISSUE THREAD

**Issue by ReyraV** [facebookresearch/demucs#344]
## ❓ Questions

Hello! I run python3 -m tools.automix as instructed. This error is raised. Do you know what it could be related to? I am using musdbhq dataset.

100%|█████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 182281.79it/s]
  0%|                                                                                            | 0/86 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/demucs/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/demucs/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/music/demucs/tools/automix.py", line 343, in <module>
    main()
  File "/home/music/demucs/tools/automix.py", line 312, in main
    spec, track = pending.result()
  File "/opt/conda/envs/demucs/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/opt/conda/envs/demucs/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by adefossez** [comment]
See https://github.com/facebookresearch/demucs/issues/343, do you have a full anaconda env setup with the anaconda env ? (not just the requirements.txt).

**Comment by adefossez** [comment]
Can you try reducing the number workers ? https://github.com/facebookresearch/demucs/blob/main/tools/automix.py#L298 replace by 1 for debugging.

**Comment by ReyraV** [comment]
@adefossez Yes, i installed env using environment-cuda.yml and also tried reducing the number of workers but that didn't help.

**Comment by adefossez** [comment]
Can you try removing the pool.submit call ? i.e. change this line https://github.com/facebookresearch/demucs/blob/main/tools/automix.py#L300 with 
`analyse_track(dset, index)`

**Comment by adefossez** [comment]
Also can you try exporting the env variable `export NUMBA_NUM_THREADS=1` before running ?

**Comment by ReyraV** [comment]
Thanks, this worked for me!

**Comment by adefossez** [comment]
Awesome, I changed the instructions to always include that env variable.
