### ISSUE TITLE
New Demucs graphical interface app

### ISSUE THREAD

**Issue by iffyloop** [facebookresearch/demucs#346]
Not a bug, just wanted to announce a new app powered by Demucs that lets you search, download, and split any song in one click. Wondered if this might be appropriate to add to the "Graphical interface" section of the readme...

GitHub Repo: [https://github.com/stemrollerapp/stemroller](https://github.com/stemrollerapp/stemroller)
Website: [https://www.stemroller.com/](https://www.stemroller.com/)

Both of these - especially the website - will be greatly expanded upon in the coming weeks. I'm planning to release a macOS version as soon as I can get Demucs packaged with pyinstaller for that platform.

Hope this might help someone! Thanks to all of you Demucs developers for making the best stem separation utility I've used so far - I'm impressed!

**Comment by Mathiasjustin** [comment]
How do I go about this I can barely understand any of the terms used here am new and I would love to learn
