### ISSUE TITLE
Demucs experiment shows both true and false for the same hyper-parameter

### ISSUE THREAD

**Issue by lyndonlauder** [facebookresearch/demucs#352]
Hi i am using XP 3d21764b to train a model, the model trains good but i am confused by the hyper-parameters as you see below it shows both hdemucs.cac=False and hdemucs.cac=True, hdemucs.norm_starts=999 and hdemucs.norm_starts=4, as these both cannot be true please could you explain me which one is being used?

`Parser Injecting argv ['hdemucs.norm_starts=999', 'hdemucs.cac=False', 'test.split=True', 'valid_apply=True', 'model=hdemucs', 'hdemucs.dconv_lstm=4', 'ema.epoch=[0.9, 0.95]', 'ema.batch=[0.9995, 0.9999]', 'hdemucs.hybrid=True', 'hdemucs.cac=True', 'dset=extra44', 'seed=44', 'hdemucs.norm_starts=4', 'hdemucs.norm_groups=4', 'svd=base', 'svd.penalty=1e-05', 'svd.dim=100', 'svd.convtr=True'] from sig 3d21764b`

Also when i run dora run -d -f 3d21764b the checkpoint and model is saved to XP 5783f93a as you see here `[demucs.train][INFO] - For logs, checkpoints and samples check /demucs/outputs/xps/5783f93a` , this is no issue but i will write it just to make sure.

**Comment by adefossez** [comment]
It is possible for one hyper parameter to be repeated and in that case the last value is the true one.

Regarding the change in signature that might be due to the fact that you have changed some of the config files. With a fresh clone of the repo it should keep the exact same signature.
