### ISSUE TITLE
FAILED TEMPO, failed drums, failed bass always when executing code tools/automix.py

### ISSUE THREAD

**Issue by ReyraV** [facebookresearch/demucs#353]
There are many failures in the execution of the process. What might it depend on? What does that have to do with training? I am using dataset Musdb HQ.
For example:

> failed drums tensor(0.) tensor(0.0457)
> failed bass tensor(0.) tensor(0.0603)
> ...
> -0.8090909090909091 93.96306818181819 123.046875 FAILED TEMPO
> -0.6863636363636363 93.96306818181819 74.89809782608695 FAILED TEMPO
> -0.85 93.96306818181819 156.60511363636363 FAILED TEMPO

**Comment by adefossez** [comment]
this is expected. The first failures are just because there is no drum or bass. Then FAILED TEMPO just means it couldn't match the two candidates stems because the BPM was too far appart. Just let it run and it should eventually complete :)

**Comment by ReyraV** [comment]
Thanks for the answer!

**Comment by adefossez** [comment]
I added a message in the instruction to say this was normal :)
