### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by akalankasakalasooriya** [facebookresearch/demucs#356]
## ❓ Questions

I run this command "demucs ./fimename.mp3" inside WSL . then it shows me an error 

RuntimeError: CUDA out of memory. Tried to allocate 358.00 MiB (GPU 0; 2.00 GiB total capacity; 835.54 MiB already allocated; 192.43 MiB free; 974.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by CarlGao4** [comment]
Please see document [here](https://github.com/facebookresearch/demucs#memory-requirements-for-gpu-acceleration)
Use `demucs -d cpu audio`

**Comment by CarlGao4** [comment]
If your problem is solved, please close this issue.

**Comment by daryltucker** [comment]
For anybody coming here in the future, you can also try running `demucs` by adjusting `max_split_size_mb` for `pytorch`:

```
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
demucs /tmp/ID.mp3
```

**Comment by AkiKagura** [comment]
@daryltucker Hello, is this method suitable for Mac?🥺

**Comment by CarlGao4** [comment]
macOS can't use CUDA.

**Comment by AkiKagura** [comment]
> 

Yes, I mean I am trying to use mps to replace coda. But I am wondering where and how should I change the code.
