### ISSUE TITLE
wav bit (16/24/32)

### ISSUE THREAD

**Issue by BitBlueDevStudio** [facebookresearch/demucs#359]
Hello! Thanks for greate work at first!

I have a question, is it means something for training process, if training data has different wave bit?
For example one song saved in 24bit, another in 16bit, etc.
Or what if training dataset is 24bit, but finetuning dataset is 16bit, or vise versa?

Does this somehow affects training process or model quality?

Thanks in advance!

**Comment by adefossez** [comment]
The training set is 16bit. This is unlikely to affect the model quality as the precision at 16bits is more than enough. Deep learning models are not "fine" enough that they would leverage differences between 16 and 24 bits.

**Comment by BitBlueDevStudio** [comment]
Thanks!
