### ISSUE TITLE
How to separate an entire folder in Google Colab?

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [facebookresearch/demucs#365]
## ❓ Questions

I am trying since the beginning of this day to separate some `.flac` files in a parent folder, yet I don't know how to convert the Windows format of the loop:

> cd FOLDER
> for %i in (*.flac) do (demucs -d cpu "%i")

to the Linux format or Google Colab format using these settings:
```python
! demucs -n "mdx_extra" --shifts "20" --overlap "0.75" --two-stems=vocals --clip-mode rescale -d cuda
```

**Comment by CarlGao4** [comment]
Run these codes in a cell:
```python
import os
os.chdir('path')
os.system('demucs -n "mdx_extra" --shifts "20" --overlap "0.75" --two-stems=vocals --clip-mode rescale -d cuda "' + '" "'.join(os.listdir()) + '"')
```

**Comment by MohammedMehdiTBER** [comment]
> Run these codes in a cell:
> 
> ```python
> import os
> os.chdir('path')
> os.system('demucs -n "mdx_extra" --shifts "20" --overlap "0.75" --two-stems=vocals --clip-mode rescale -d cuda "' + '" "'.join(os.listdir()) + '"')
> ```

It took me time to view your reply. 
Anyway, after deep hard research on Google I constructed this command which is also recursive and processing the file alphabetically:
```python
!find . -type f -name "*.flac" | sort | tr '\n' '\0' | xargs -0 demucs -n "mdx_extra" -n "mdx" --two-stems=vocals --clip-mode rescale -d cuda --segment 120 {}
```
What do you think of it ?
