### ISSUE TITLE
Unable to use TPU in Google Colab 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [facebookresearch/demucs#366]
## 🐛 Bug Report

Unable to use TPU in Google Colab 
RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone device type at start of device string: tpu

## To Reproduce

```! demucs -n "mdx_extra" --shifts "20" --overlap "0.75" --two-stems=vocals --clip-mode rescale  -d tpu -j 20 -o "/content/drive/MyDrive" *.flac```

## Expected behavior
Not crashing at the beginning 

## Actual Behavior

 

> Traceback (most recent call last):
>    File "/usr/local/bin/demucs", line 8, in <module>
>      sys.exit(main())
>    File "/usr/local/lib/python3.7/dist-packages/demucs/separate.py", line 155, in main
>     num_workers=args.jobs)[0]
>    File "/usr/local/lib/python3.7/dist-packages/demucs/apply.py", line 142, in apply_model
>     device = th.device(device)
>  RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, ort, mps, xla, lazy, vulkan, meta, hpu, privateuseone device type at start of device string: tpu

## Your Environment

Google Colab (TPU mode)

- Python and PyTorch version: Python 3.7 and PyTorch 1.8.1
- Operating system and version (desktop or mobile): Google Colab Desktop
- Hardware: TPU

**Comment by CarlGao4** [comment]
Please use GPU instead. I remember that demucs can’t use TPU. The parameter is `-d cuda`

**Comment by MohammedMehdiTBER** [comment]
> Please use GPU instead. I remember that demucs can’t use TPU. The parameter is `-d cuda`

Yes I know GPU mode
Sadly but they say TPU is faster than GPU

**Comment by CarlGao4** [comment]
But GPU can do more things than TPU, so if a program want to shift from CPU to GPU, almost nothing is needed to be changed, but using TPU would be more difficult.

**Comment by adefossez** [comment]
By the way you should checkout https://colab.research.google.com/github/pytorch/xla/blob/master/contrib/colab/getting-started.ipynb
Anyway, I'll be closing the issue as I am not planning on officially supporting TPU.

**Comment by jie-chen** [comment]
Hi, it seems TPU support now seems much easier with XLA https://pytorch.org/xla/release/2.1/index.html . Does anyone know the minimal modifications of code to train with TPU?
