### ISSUE TITLE
Retaining all separation models locally on drive?

### ISSUE THREAD

**Issue by Dyslexicon** [facebookresearch/demucs#378]
## ❓ Questions

mdx_extra_q is the default model; but in order to use larger data size models, when I call upon them, apparently I must have my computer connected to the internet and re-download these larger model data sets each time?

I called upon -n mdx_extra while my computer was offline, and got the "not found" script, even after I had utilized that model previously and the four 160MB model data sets were downloaded.

Is there a way to permanently store all models locally on my hard drive?
My main demucsing machine is offline most of the time.

Thanks, sorry if I've overlooked something obvious.

Secondary question - is there a table showing the SDR values of the mdx_extra_q model?
The **mdx_extra** model is significantly better than **mdx_extra_q.**
Would love to see some numerical values on the quantized version if they have been measured, for comparison purposes.
Thanks

**Comment by CarlGao4** [comment]
For your first question, please see #367

**Comment by Dyslexicon** [comment]
Thank you seems to be working now offline.
