### ISSUE TITLE
How to do the command for 32float + use mdx_extra on Mac?

### ISSUE THREAD

**Issue by BeverlyLaurelBLVD** [facebookresearch/demucs#388]
## ❓ Questions

Hi, I'm trying to figure out how to type out what I want.

32 float WAV + the mdx_extra model + I want to use my CPU, not GPU.

How would I type all this together?

I'm really new to terminal

**Comment by CarlGao4** [comment]
```bash
python3 -m demucs -n mdx_extra --float32 -d cpu file1.mp3 file2.wav
```

**Comment by BeverlyLaurelBLVD** [comment]
> ```shell
> python3 -m demucs -n mdx_extra --float32 -d cpu file1.mp3 file2.wav
> ```

Thank you very much!
