### ISSUE TITLE
Ayuda!  ResolvePackageNotFound: pytorch y ffmpeg

### ISSUE THREAD

**Issue by trust97** [facebookresearch/demucs#39]
todo al pie de la letra hice, pero no funciona en cmd, habia leido en una pag en ingles (yo no se ingles pero entiendo algo ) que decia usa "anaconda navigator" lo hice y wow! funciona pero PERO..
cuando pongo:  conda env update -f environment-cpu.yml 
me  dice esto .. tanto en cmd como en anaconda navigator sale lo mismo y  no puedo seguir tengo todo instalado pero al parecer falta algo que hago? 
![esto nada que ver ayuda](https://user-images.githubusercontent.com/58658258/70390005-95198f80-19a5-11ea-91b5-8bc818822fa4.PNG)

**Comment by Gringo541** [comment]
tenes que abrir la ventana de comandos de anaconda

**Comment by onsoho** [comment]
¿Ya instalaste las dependencias de pytorch y ffmpeg? Si las instalaste en tu sistema base no podrán ser encontradas ya que estas corriendo base un environmnent aparte.

**Comment by trust97** [comment]
> tenes que abrir la ventana de comandos de anaconda

Hace lo mismo de cualquiera de los 2 da los mismos errores

**Comment by trust97** [comment]
> ¿Ya instalaste las dependencias de pytorch y ffmpeg? Si las instalaste en tu sistema base no podrán ser encontradas ya que estas corriendo base un environmnent aparte.

Lei por ahi que tengo que hacer eso pero desconozco como hacerlo, ya que no entendi muy bien como hacerlo, aclaro que estoy usando 32 bits, tienes idea como se hace?

**Comment by Gringo541** [comment]
trust97 tienes discord? te ayudo agregame    @DjGringo#5449

**Comment by onsoho** [comment]
> > ¿Ya instalaste las dependencias de pytorch y ffmpeg? Si las instalaste en tu sistema base no podrán ser encontradas ya que estas corriendo base un environmnent aparte.
> 
> Lei por ahi que tengo que hacer eso pero desconozco como hacerlo, ya que no entendi muy bien como hacerlo, aclaro que estoy usando 32 bits, tienes idea como se hace?

Definitivamente no creo que puedas correrlo en 32 bits, eso debe ser consultado con el desarrollador.

**Comment by adefossez** [comment]
@trust97, Pytorch is not supported on 32bits system :/
