### ISSUE TITLE
Downloading pre-trained models manually?

### ISSUE THREAD

**Issue by thetechguy-cpu** [facebookresearch/demucs#391]
## ❓ Questions

Is there a way for me to download the pre-trained models manually? I can't seem to find where to get them. Also, where do I place them once downloaded? I'm on windows.

**Comment by adefossez** [comment]
You can find the signatures for each bag of models inside demucs/remote/nameofbag.yaml

Then the corresponding file name is the only one that start with this signature.

**Comment by CarlGao4** [comment]
Please see #367 .

**Comment by thetechguy-cpu** [comment]
Thanks for the responses. I was able to download the pre-trained models at the provided link :)
