### ISSUE TITLE
-d cpu in ht/v4

### ISSUE THREAD

**Issue by cewatkins** [facebookresearch/demucs#397]
## ❓ Questions
https://github.com/facebookresearch/demucs/blob/ht/README.md
Uh, so -d cpu does basically 1 to 1.5 seconds to a second. (takes about as long as to play song.)
without v3.7  capability CUDA or better I get the finger about it & it claims incapable kernel, (yeah, nice CUDA errors).
But I am therefor then unclear on your statement about it needing CUDA code as you call it through python & the quality seems to compare.   Also, the automix is quite nice, making it do custom trained stuff is quite enjoyable listening to it's results, but it never selects over another, tempo, etc.  I realize it can't vote/feel/report quality of them yet, but 20 trained songs makes alot of results and a lovely amount of diskspace. ;)
(Please ask your question here.)
As Hybrid Transformer Demucs is brand new, it is not activated by default, you can activate it in the usual commands described hereafter with -n htdemucs_ft. The single, non fine-tuned model is provided as -n htdemucs, and the retrained baseline as -n hdemucs_mmi. The sparse kernels require custom CUDA code that is not ready for release yet.
Uh, so -d cpu does basically 1 to 1.5 seconds to a second. (takes about as long as to play song.) or htdemucs_ft with CUDA?

**Comment by adefossez** [comment]
The statement on sparse CUDA kernels was for a specific version of the model that we haven't released. the main `htdemucs` and `htdemucs_ft` (this one will takes 4 times longer to evaluate) models work perfectly with CUDA :)

Note that the `ht` branch was a development branch not intended for public use. things should be clearer now in the main branch.
