### ISSUE TITLE
"htdemucs_ft is neither a single pre-trained or a bag of models"

### ISSUE THREAD

**Issue by lucellent** [facebookresearch/demucs#398]
Trying to run the new HT model, installed everything correctly but I'm hit with this

<img width="635" alt="Screenshot_1" src="https://user-images.githubusercontent.com/38135928/199623302-9c84877f-776f-4919-9df8-1b83013d77cb.png">

**Comment by dillfrescott** [comment]
I haven't heard of this model. Is it listed somewhere?

**Comment by dillfrescott** [comment]
Nevermind I found it haha! Ill give it a try and see if it works for me!

**Comment by dillfrescott** [comment]
Ok. Its working for me. Make sure you downloaded or checkout the ht branch, and run a `pip install -e .` in the directory. That should work!

**Comment by lucellent** [comment]
> 

I have the branch downloaded and ran` pip install -e . ` but it seems like it's still giving the same error, can't figure out what I've missed

**Comment by dillfrescott** [comment]
I think somehow it might be still on the main branch. Just a hunch. What you can do is switch to ht on github and specifically only download the ht code and run pip install -e . On that

**Comment by lucellent** [comment]
Got it working now! What I did was move all the files from the ht branch (I downloaded the whole thing as .zip) to the folder of regular demucs. Not sure if that's the same thing as you suggested I got the idea from that, thank you!

**Comment by dillfrescott** [comment]
Awesome!

**Comment by lucellent** [comment]
A side note, do you experience the issue of stems having inconsistent audio levels? I posted this issue while ago but no fix has been made yet, each stem has different audio levels. For example the drums mostly get quieter by 2 or 3 db, and the vocals by 1db (something close to that)

**Comment by dillfrescott** [comment]
Hmmm. I haven't noticed but, yet again, I never really paid attention to it. Sorry I'm not much help with that question :/

**Comment by jarredou** [comment]
> A side note, do you experience the issue of stems having inconsistent audio levels? I posted this issue while ago but no fix has been made yet, each stem has different audio levels. For example the drums mostly get quieter by 2 or 3 db, and the vocals by 1db (something close to that)

As stated in the main readme :
"_It can happen that the output would need clipping, in particular due to some separation artifacts. Demucs will automatically rescale each output stem so as to avoid clipping. This can however break the relative volume between stems. If instead you prefer hard clipping, pass --clip-mode clamp. You can also try to reduce the volume of the input mixture before feeding it to Demucs._"

**Comment by lucellent** [comment]
> > A side note, do you experience the issue of stems having inconsistent audio levels? I posted this issue while ago but no fix has been made yet, each stem has different audio levels. For example the drums mostly get quieter by 2 or 3 db, and the vocals by 1db (something close to that)
> 
> As stated in the main readme : "_It can happen that the output would need clipping, in particular due to some separation artifacts. Demucs will automatically rescale each output stem so as to avoid clipping. This can however break the relative volume between stems. If instead you prefer hard clipping, pass --clip-mode clamp. You can also try to reduce the volume of the input mixture before feeding it to Demucs._"

Thank you, I've missed that part. Though this happens only if I run Demucs myself, it doesn't happen if I use a third party GUI or a website version of Demucs (with the same song and model)
