### ISSUE TITLE
Fail to run on read_audio mismatching with subprocess 

### ISSUE THREAD

**Issue by AppleHolic** [facebookresearch/demucs#4]
I got fail for running separation of test audio. 

- line of failed function :  https://github.com/facebookresearch/demucs/blob/8acff8df46073b7a824f6cc3993ec7b981d5bfac/demucs/audio.py#L16

Run function of subprocess has not 'capture_output' argument under python 3.7 (My environment is 3.6).

It would be better 'getoutput' function to support other versions of python3. (I will make PR and reference it on comment) And repository should specify the version of python.

**Comment by adefossez** [comment]
Should be solved now, closing the issue, and thanks for your pull request!
