### ISSUE TITLE
donde queda el resultado??

### ISSUE THREAD

**Issue by klauz996** [facebookresearch/demucs#40]
(demucs) C:\Users\Chrisitan\demucs-master>python.exe -m demucs.separate --dl -n demucs "C:\Users\Chrisitan\Desktop\Musica\A Fuego Lento (2º Version).mp3" -d cpu
  0%|                                                                                                                                                                                       | 0/1 [00:00<?, ?it/s]ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --disable-static --enable-shared --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, mp3, from 'C:\Users\Chrisitan\Desktop\Musica\A Fuego Lento (2┬║ Version).mp3':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf58.28.100
  Duration: 00:04:09.38, start: 0.023021, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 48000 Hz, stereo, fltp, 320 kb/s
    Metadata:
      encoder         : Lavc58.53
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [8:58:09<00:00, 32289.11s/it]

supuestamente termino de hacerlo pero no encuentro la carpeta separated que tendria que estar en la carpeta de demucs

**Comment by Gringo541** [comment]
hola, tu solucion,,, 
.\demucs-master\models

**Comment by klauz996** [comment]
> hola, tu solucion,,,
> .\demucs-master\models

no hay nada adentro de separated

**Comment by Gringo541** [comment]
no es en la carpera separado. es en la carpeta models

**Comment by Gringo541** [comment]
models*

**Comment by onsoho** [comment]
> hola, tu solucion,,,
> .\demucs-master\models

Esa es la carpeta de los pre-trained models, la carpeta de resultados se almacena en `./separated/MODEL_NAME` o dependiendo de su salida al patch-out.

**Comment by adefossez** [comment]
Lo siento por mi respueta tardia, gracias @onsoho por la respueta correcta :)
