### ISSUE TITLE
Files not appearing in output folder

### ISSUE THREAD

**Issue by beezi411** [facebookresearch/demucs#401]
## ❓ Questions
After the files have separated the files aren't showing up in the output folder. Any help would be appreciated. Thanks 
 
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/118085979/201499857-dc1cf982-4829-474c-8bea-9619a754ff52.png">
<img width="838" alt="2" src="https://user-images.githubusercontent.com/118085979/201499858-4c458f04-4005-4383-b848-50dc8dae45f0.png">

**Comment by CarlGao4** [comment]
Please run:
```cmd
explorer C:\Users\gtheg\separated\mdx_extra_q
```

**Comment by beezi411** [comment]
@CarlGao4 Thank you! It's showing now. My firewall put it in sandbox mode.
