### ISSUE TITLE
How to update to Demucs4?

### ISSUE THREAD

**Issue by OktoberfestThePlayer** [facebookresearch/demucs#404]
Hello!

I have Demucs3 currently installed on my PC but idk how to update it to Demucs4, and I really would like to try out the htdemucs_ft model with CPU settings, thank you!

**Comment by deton24** [comment]
Maybe try opening PowerShell and run:
`!pip install git+https://github.com/facebookresearch/demucs.git@ht`

**Comment by OktoberfestThePlayer** [comment]
Got it working now! Just had to reinstall Anaconda3 again
