### ISSUE TITLE
Can't get GPU acceleration

### ISSUE THREAD

**Issue by stephandue** [facebookresearch/demucs#411]
## ❓ Questions

First off, thanks to everyone who contributed to demucs. Excellent work. Now my question:
Is there anything specific that needs to be done to run the separation on the GPU? I used demucs on a cloud computer from a docker image. Clearly this was working on the CPU and was therefor really slow. Now I got a PC with a GeForce 3090 with 24GB memory in hopes that demucs would run faster.
I have ubuntu 22.10 installed on the PC as the main OS. Then I have docker installed and created a docker image also using ubuntu 22.10. I have PyTorch 1.13.0 as well as Nvidia-cuda-dev and Nvidia-cuda-toolkit installed. When I type "nvcc -V" in my docker container I get: "Cuda compilation tools, release 11.5, V11.5.119.." So cuda seems to be installed correctly.
I have try to split an mp3 from the shell with:
demucs revolution.mp3
I also tried different models like:
demucs -n mdx revolution.mp3

But the usage of my graphic card which I monitor with the Nvidia settings stays low. Almost no memory is in use (only 900MB which is also in use before I start the process).

Also if I add the flag -d cpu the process takes exactly the same time.

What am I missing here? How can I get demucs to use the GPU?

Many Thanks
Stephan

**Comment by CarlGao4** [comment]
How did you installed Demucs? (conda or pip)
`nvcc` isn't required.

**Comment by CarlGao4** [comment]
Please uninstall torch, torchaudio, torchvision. Then choose your system and your package manager. Remember to choose CUDA. Then run the command below.

**Comment by stephandue** [comment]
Here is my Dockerfile:

`FROM ubuntu:22.10

USER root
ENV TORCH_HOME=/data/models

RUN apt-get update && apt-get install -y ffmpeg nvidia-cuda-dev nvidia-cuda-toolkit python3-pip
RUN pip3 install torch==1.13.0+cu117 torchvision==0.14.0+cu117 -f https://download.pytorch.org/whl/torch_stable.html

# Install Git
RUN apt install -y git

# Install Facebook Demucs
RUN mkdir -p /lib/demucs

WORKDIR /lib/demucs

RUN git clone -b main --single-branch https://github.com/facebookresearch/demucs /lib/demucs

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN python3 -m pip install -e .

RUN python3 -m demucs.separate -d cpu test.mp3 # Trigger model download
RUN rm -r separated  # cleanup

VOLUME /data/input
VOLUME /data/output
VOLUME /data/models

WORKDIR /usr/src/app

COPY . ./

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]`

**Comment by stephandue** [comment]
When I enter "nvidia-smi" in the docker I get "Failed to initialize NVML: Unknown Error".
I guess I can't use to GPU in the container just like that. I just read about Nvidia Container Toolkit for Docker.

**Comment by CarlGao4** [comment]
> When I enter "nvidia-smi" in the docker I get "Failed to initialize NVML: Unknown Error". I guess I can't use to GPU in the container just like that. I just read about Nvidia Container Toolkit for Docker.

That's true. What I'm using is wsl2 on Win11, which can pass nvidia graphics inside.

**Comment by stephandue** [comment]
Thanks for your help so far. Maybe I'll try wsl2 on windows.

**Comment by CarlGao4** [comment]
P.S. You can simply use your main OS to run demucs.

**Comment by stephandue** [comment]
I got it working in the docker container. Installing the Nvidia docker toolkit did the trick for me:
https://github.com/NVIDIA/nvidia-docker

A 10 Minute song is now splittet in 14 seconds on my GeForce 3090. Amazing!

**Comment by AnshulJ999** [comment]
I have an NVIDIA GTX 3050ti and I'm running demucs on Windows. But I've tried everything and my GPU isn't being used during the processing. Any newbie troubleshooting help please?

**Comment by CarlGao4** [comment]
@AnshulJ999  Please provide more information like your command and what you've done.

**Comment by AnshulJ999** [comment]
Nevermind, I was using the wrong flag. Just had to use '-d cuda-, and now it's working brilliantly. 20s/s. Thanks! This thread was super helpful.
