### ISSUE TITLE
dora: error: argument command: invalid choice: 'train' (choose from 'grid', 'run', 'launch', 'info')

### ISSUE THREAD

**Issue by turian** [facebookresearch/demucs#416]
## 🐛 Bug Report

[Training instructions](https://github.com/facebookresearch/demucs/blob/hybrid/docs/training.md) do not work, because `dora train` is not a valid command.

```
dora: error: argument command: invalid choice: 'train' (choose from 'grid', 'run', 'launch', 'info')
```

## To Reproduce

1. git clone demucs master
1. `pip3 install -r requirements.txt`
1. `dora train -d variant=default`

## Expected behavior

Training should work without an error.

## Actual Behavior

```
dora: error: argument command: invalid choice: 'train' (choose from 'grid', 'run', 'launch', 'info')
```

This is using `dora-search==0.1.11`

**Comment by seth814** [comment]
I think the documentation is out of date. Replace train with run.

**Comment by adefossez** [comment]
Sorry about that, I fixed the doc !
