### ISSUE TITLE
I can't install Demucs v. 4 (Bleeding Edge Command)

### ISSUE THREAD

**Issue by KatieBelli** [facebookresearch/demucs#419]
## ❓ Questions

I used this code to install Demucs 4 (I use Windows 10):

`python -m pip install -U https://github.com/facebookresearch/demucs#egg=demucs`

But this error always appears:

> Collecting demucs
  Cloning https://github.com/facebookresearch/demucs to c:\users\...\appdata\local\temp\pip-install-ud5yt1ut\demucs_e43be7194e3644f08f6d3870474ce3f5
  ERROR: Error [WinError 2] Das System kann die angegebene Datei nicht finden while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

How can I solve this issue?
I already used Demucs 3 a few times.

**Comment by matiaszanolli** [comment]
It looks like either you don't have Git installed, or you don't have it on your `PATH` environment variable.

Please be sure to double check on that by running `git` on your command line and see what happens,

**Comment by CarlGao4** [comment]
You can simply [download zip](https://github.com/facebookresearch/demucs/archive/refs/heads/main.zip), extract it, then chdir to the extracted directory, then run `pip install -e .`

**Comment by CarlGao4** [comment]
Besides, your command should be `python3 -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs` if you want to use `git`.

**Comment by KatieBelli** [comment]
Ok, that was weird:

I copied the command line from the code website, removed the number 3 from it (like before), and it worked. Strange.
And now I realize, I forgot to add "git+". So, of course it can't work.

Thank y'all for helping.
