### ISSUE TITLE
Frozen loading bar during song decompilation

### ISSUE THREAD

**Issue by slenderman020** [facebookresearch/demucs#42]
### The loading bar freezes when I try to process a song
Log:
```
  0%|                                                     | 0/1 [00:00<?, ?it/s]ffprobe version 4.2 Copyright (c) 2007-2019 the FFmpeg developers
  built with gcc 7.3.0 (crosstool-NG 1.23.0.449-a04d0)
  configuration: --prefix=/root/anaconda3/envs/demucs --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1566210161358/_build_env/bin/x86_64-conda_cos6-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, wav, from '/root/Escritorio/soltera-remix.wav':
  Metadata:
    encoder         : Lavf58.35.100
  Duration: 00:04:25.24, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
```

**As you can see the estimated waiting time shows a (?) symbol
I'm running in Kali.**

**Comment by onsoho** [comment]
Hey, are you using cpu or gpu environment?

**Comment by adefossez** [comment]
The loading bar only shows how many tracks have been processed so far so it is normal it is not updated when separating a single track. It should take roughly the same time as the duration of the song when separating on CPU.

**Comment by Richa312rds** [comment]
> The loading bar only shows how many tracks have been processed so far so it is normal it is not updated when separating a single track. It should take roughly the same time as the duration of the song when separating on CPU.

that is not the barr progress it's a picture. why still freezes the pc., and after the progress there ere not any separated single track

**Comment by adefossez** [comment]
If you did not get any error, the separated tracks will be in `DEMUCS_FOLDER \ separated \ demucs \ TRACK_NAME`. If you followed the instructions from the README, `DEMUCS_FOLDER` should be `demucs` under your home folder `C:\Users\YOUR_USERNAME`.
