### ISSUE TITLE
Where can I find documentation for writing python scripts?

### ISSUE THREAD

**Issue by hungLink** [facebookresearch/demucs#425]
I would like to write some scripts so that I can automate my workflow. The problem is, I cannot find any documentation!

Where can I find a list of available functions, what they do, and how to use them?

**Comment by CarlGao4** [comment]
You can just read the codes of `separate.py` `apply.py` `audio.py`. After understanding the process of one successful separating, you can write your own scripts.

**Comment by CarlGao4** [comment]
The most important steps are: 
1. https://github.com/facebookresearch/demucs/blob/main/demucs/pretrained.py#L89
2. https://github.com/facebookresearch/demucs/blob/main/demucs/separate.py#L141-L142
3. https://github.com/facebookresearch/demucs/blob/main/demucs/separate.py#L159-L166
4. https://github.com/facebookresearch/demucs/blob/main/demucs/separate.py#L180-L185

You can expand the third step so you can use your own parameters at https://github.com/facebookresearch/demucs/blob/main/demucs/apply.py#L123-L242

**Comment by hungLink** [comment]
Hmm. That seems like it may be overkill for my purposes. All I want is to make a python script that removes the drums.

In order to do this with demucs, do I have to understand how separation works to do that?

**Comment by CarlGao4** [comment]
So you can just use `subprocess` to call cli.

**Comment by hungLink** [comment]
Thanks!
