### ISSUE TITLE
Why the suffix of model file is .th？

### ISSUE THREAD

**Issue by 843853472** [facebookresearch/demucs#428]
I'm a novice of Pytorch and I'm trying to read the code .Why the suffix of model file is .th ,as I know it should be .pth?

<img width="207" alt="2023-01-09 114019" src="https://user-images.githubusercontent.com/17305376/211237559-b100b9cd-f375-46df-ab57-80729534a6eb.png">

**Comment by adefossez** [comment]
Who said it should .pth? There is no standard for torch pickle file extension.

**Comment by 843853472** [comment]
> Who said it should .pth? There is no standard for torch pickle file extension.
Then why ModuleNotFoundError occured when I tried to load .th?
I don't see hdemucs in demucs.
![image](https://user-images.githubusercontent.com/17305376/211372344-336dfef4-dbe1-4506-81db-9d51ffd33d81.png)
