### ISSUE TITLE
ModuleNotFoundError: No module named 'demucs.hdemucs'; 'demucs' is not a package

### ISSUE THREAD

**Issue by 843853472** [facebookresearch/demucs#429]
## 🐛 Bug Report

ModuleNotFoundError: No module named 'demucs.hdemucs'; 'demucs' is not a package

## To Reproduce

For learning, I tried to run __main__.py by terminal 
![image](https://user-images.githubusercontent.com/17305376/211520465-7fc9f954-b346-48a3-9fe9-89d3443d7788.png)

It comes all .module couldn't import, so I deleted the dots.
![image](https://user-images.githubusercontent.com/17305376/211521368-3f5e311e-26eb-432f-83e7-e8c1c420b34c.png)

## Expected behavior

Separate track successful, using mdx_extra.

## Actual Behavior

Can't load models.
![image](https://user-images.githubusercontent.com/17305376/211522007-3f328411-16c0-4840-8be0-ed2d5c4f8814.png)
![image](https://user-images.githubusercontent.com/17305376/211522201-5c91c316-fe89-4199-8cdf-42140b94a3b3.png)

## Your Environment

 Python 3.8.2 and PyTorch 1.13.1+cpu, Windows 10 desktop

**Comment by CarlGao4** [comment]
How did you download demucs? It seems that you modified some of the codes.

**Comment by 843853472** [comment]
> How did you download demucs? It seems that you modified some of the codes.

 I used pip install,  then copied the folder from site_packages

**Comment by CarlGao4** [comment]
It seems that demucs can't be used outside the package? Please try using `python -m demucs ...` instead. 
Besides, does the output of `python -m pip list` includes demucs?

**Comment by 843853472** [comment]
> It seems that demucs can't be used outside the package? Please try using `python -m demucs ...` instead. Besides, does the output of `python -m pip list` includes demucs?

It worked, Thank you! Btw what makes it must launch as a module?

**Comment by CarlGao4** [comment]
> > It seems that demucs can't be used outside the package? Please try using `python -m demucs ...` instead. Besides, does the output of `python -m pip list` includes demucs?
> 
> It worked, Thank you! Btw what makes it must launch as a module?

I guess that the problem comes from https://github.com/facebookresearch/demucs/pull/368 
In this PR, HDemucs has been added to torchaudio, so maybe torch will directly call the module instead the user's codes? 
(They are all assumption, I don't exactly know why)

**Comment by 843853472** [comment]
Okay, I'll keep learning on it, thanks again!
