### ISSUE TITLE
No module named demucs

### ISSUE THREAD

**Issue by ola-k-ase** [facebookresearch/demucs#43]
hola, me aparece el siguiente error:
 Error while finding module specification for 'demucs.separate' (ModuleNotFoundError: No module named 'demucs')
necesito ayuda para saber como solucionarlo
¿Alguien me puede explicar?

**Comment by adefossez** [comment]
Hola,
Agregué instrucciones para utilizar Windows: https://github.com/facebookresearch/demucs/blob/master/README.md#using-windows

Puede hacer lo y digame si functiona ?

**Comment by maghusg** [comment]
no me funciona a mi y tenía el mismo problema

**Comment by rokimoki** [comment]
Sigan las instrucciones, léanlas detenidamente.

**Comment by ola-k-ase** [comment]
hola. el error se me ha solucionado gracias

**Comment by shoegazerstella** [comment]
I am having a similar issue, I am on macOS and I just splitted the code for model loading and inference like:
```
def load_demucs_model(model_name='demucs'):

    model_path = Path(MODEL_PATH) / f"{model_name}.th"

    sha256 = PRETRAINED_MODELS.get(model_name)

    if not model_path.is_file():
        if sha256 is None:
            return Exception("No pretrained model: " + str(model_name))

    if sha256 is not None:
        verify_file(model_path, sha256)

    model = load_model(model_path).to(device)

    return model
```

While everything works fine when I execute from command line, if I execute the new file.py I get this:

```
  File "separate_demucs.py", line 143, in <module>
    model = load_demucs_model()
  File "separate_demucs.py", line 99, in load_demucs_model
    model = load_model(model_path).to(device)
  File "/Users/stella/Desktop/demucs_repo/demucs/utils.py", line 160, in load_model
    klass, args, kwargs, state = th.load(path, 'cpu')
  File "/Users/stella/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/Users/stella/anaconda3/envs/demucs/lib/python3.7/site-packages/torch/serialization.py", line 613, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'demucs'
```
I have set the correct model path, and I just cloned the repo today and downloaded the new version of the models as suggested in the documentation. Also, everything works fine when i do:
```
python3 -m demucs.separate --dl -n demucs -d cpu PATH_TO_AUDIO_FILE_1
```

**Comment by Fulanito0** [comment]
saludos, hermano ya he hecho de todo y no me funciona y siempre me da el mismo error de (No module named 'demucs'), hablaste de como solucionar el problema en windows pero que dices sobre las mac como asignas la direccion especifica ?
hazte un mini tutorial de como resolver ese problema para las dos plataformas o una captura a parte que detalle bien la soclucion del problema por favor responde lo mas pronto posible.
