### ISSUE TITLE
Odd error: File 33 does not exist

### ISSUE THREAD

**Issue by visusys** [facebookresearch/demucs#434]
## 🐛 Bug Report

I ran the following command:
`demucs -segment 33 "Archetype (Wav).wav"`

The file I specified exists in the working directory, so the command is fine.

Before separation occurs, there is a warning in the console output: 

`File 33 does not exist. If the path contains spaces, please try again after surrounding the entire path with quotes "".`

See this screenshot:

![pwsh_5I4QILF6XA](https://user-images.githubusercontent.com/33441569/213922772-995f08fa-b24a-4e06-bae4-136ee59bc884.png)

However despite the warning, separation occurs correctly (I think?). All stems are generated and sound good. 

But ultimately I'm confused as to where this error is originating from. I don't like errors. :( And the real mystery is... what is File 33? Why doesn't it exist?

## To Reproduce

1. Open the Anaconda PowerShell Prompt.
2. Activate the demucs environment (In my case, the command is `conda activate demucs`)
3. Change the working directory to one that contains the audio you want to separate. In my case: `cd C:\Users\futur\Desktop\2022\`
4. Run the following command: `demucs -segment 33 "Archetype (Wav).wav"` (Archetype (Wav).wav exists in the 2022 directory).
5. Observe the output: 

```
Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\futur\Desktop\2022\separated\htdemucs
File 33 does not exist. If the path contains spaces, please try again after surrounding the entire path with quotes "".

Separating track Archetype (Wav).wav
100%|██████████████████████████████████████████████| 222.29999999999998/222.29999999999998 [00:05<00:00, 37.91seconds/s]
```

## Expected behavior

Demucs should not throw a warning that an arbitrary file doesn't exist.

## Actual Behavior

Again, Demucs warns: `File 33 does not exist. If the path contains spaces, please try again after surrounding the entire path with quotes "".`

## Your Environment

```
Conda Version: 22.11.1
Python Version: 3.10.8.final.0
virtual packages: 
    __archspec=1=x86_64
    __cuda=12.0=0
    __win=0=0
base environment: C:\Python\miniconda3
user-agent: conda/22.11.1 requests/2.28.1 CPython/3.10.8 Windows/10 Windows/10.0.19045

pytorch version: 1.13.1
pytorch build: py3.10_cuda11.7_cudnn8_0
pytorch-cuda version: 11.7

GPU: NVIDIA GeForce RTX 2080 Ti (11GB VRAM)
CPU: Intel Core i9-9900KF CPU @ 3.60GHz
RAM: 64 GB
```

Here's a screenshot of all conda packages:

![conda_packages](https://user-images.githubusercontent.com/33441569/213924674-dd5c388e-e33b-46b5-8206-4e9bc93f8714.png)

Hopefully that's enough info to help identify what the issue is. If there is anything else I can provide to help narrow down the source of this error please let me know.

Any help or guidance would be greatly appreciated!

**Comment by visusys** [comment]
OK. I am completely stupid and apologize for this. The cause is because I forgot to add an additional dash to the `--segment` parameter. Closing the issue.

**Comment by adefossez** [comment]
No worries ! Honestly I'm surprised it didn't reject the command line from the start. What was happening was really confusing !
