### ISSUE TITLE
Demucs says my file doesn't exist, when it clearly does. I've enclosed the file in quotes and it's fully qualified.

### ISSUE THREAD

**Issue by visusys** [facebookresearch/demucs#443]
## ❓ Questions

I wrote a powershell wrapper around Demucs. It was working fine until I upgraded to the latest version of PowerShell 7. Now Demucs is telling me that my files don't exist... when they do.

Here is console output (I have the script printing various variables so I can more easily see what's happening):

```
$DFile:          C:\Users\futur\Desktop\Test\looperman-l-4103422-0276162-5-am-in-ny-clb-drake-melody.wav
$DFileBase:     looperman-l-4103422-0276162-5-am-in-ny-clb-drake-melody
$DFileFolder:   C:\Users\futur\Desktop\Test
$DTime:         02-21-2023 04-12-13
$DOutFolder:    -o C:\Users\futur\Desktop\Test\Extracted
$DOutFilename:  --filename (02-21-2023 04-12-13-MDX-Shifts 1) {track} - {stem}.{ext}
$DOutFull:      -o C:\Users\futur\Desktop\Test\Extracted\mdx\(02-21-2023 04-12-13-MDX-Shifts 1) looperman-l-4103422-0276162-5-am-in-ny-clb-drake-melody - Drums.wav
$DModel:        -n mdx
$DStems:        --two-stems=drums
$DBitDepth:     --int24
$DSegment:      --segment 88
$DUseCPU:       -d cuda
$DShifts:       --shifts 1

Selected model is a bag of 4 models. You will see that many progress bars per track.
Separated tracks will be stored in C:\Users\futur\Desktop\Test\Extracted\mdx
File "C:\Users\futur\Desktop\Test\looperman-l-4103422-0276162-5-am-in-ny-clb-drake-melody.wav" does not exist. If the path contains spaces, please try again after surrounding the entire path with quotes "".
```

So unfortunately, the file DOES exist. I know it exists because I can run it by just typing & 'C:\Users\futur\Desktop\Test\looperman-l-4103422-0276162-5-am-in-ny-clb-drake-melody.wav'

What am I missing? Can someone please help me?

**Comment by CarlGao4** [comment]
I noticed that your printed variable `$DFile` has a space before it. Can you check whether the space is actually in the quotes?

**Comment by visusys** [comment]
I solved the problem. The latest PowerShell changed how arguments are handled when passed to invoked executables. All I had to do (counter-intuitively) was delete the parentheses and all works again.
