### ISSUE TITLE
Calling the `demucs/separate.py` script from another python file

### ISSUE THREAD

**Issue by miguelfs** [facebookresearch/demucs#448]
## ❓ Questions

Hi, y'all. Thanks for creating and maintaining this amazing library. 🙂 

I'm new to this package. I'm writing a python code that, in one of its steps, will perform the source separation task with demucs.

From the documentation, I've read the usage of the source separation utility is by the CLI program.

My questions are:
- By calling the source separation utility from a python script, the correct way to do it is by calling the CLI directly like below?
```python
 import subprocess;
 subprocess.run("demucs PATH_TO_AUDIO_FILE_1 [PATH_TO_AUDIO_FILE_2 ...]")
```
- by reading the `demucs/separate.py` file, I've seen the CLI program basically calls the `load_track(...)` and the `apply_model(...)` functions, with some logic attached to the main program related to the arguments. Is there a "python function interface" that does something similar with the source separation task in demucs?

Thanks :)

**Comment by mepc36** [comment]
Hey @miguelfs, how did you end up running demucs from another python file? Did you use a subprocess?
