### ISSUE TITLE
![image](https://user-images.githubusercontent.com/16576445/70383598-12fe7c00-194f-11ea-86d2-2764e1302fa4.png)

### ISSUE THREAD

**Issue by JulianTierno** [facebookresearch/demucs#46]
![image](https://user-images.githubusercontent.com/16576445/70383598-12fe7c00-194f-11ea-86d2-2764e1302fa4.png)
estoy teniendo este error

 RuntimeError: CUDA out of memory. Tried to allocate 1.53 GiB (GPU 0; 4.00 GiB to tal capacity; 2.34 GiB already allocated; 568.58 MiB free; 29.77 MiB cached

Mi pc:
PROCESADOR: Intel I3 6100
VIDEO: Nvidia GeForce 1050 Ti 4gb Overlooked EVGA
RAM: 12GB
DISCO: 1 TB

AIUDAAAA

_Originally posted by @Kadaryan in https://github.com/facebookresearch/demucs/issues/8#issuecomment-562908376_

Mismo problema, ya he probado con GPU y CPU con identico resultado.

**Comment by adefossez** [comment]
Can you try adding `-d cpu` after `-m demucs.separate` ? this should solve the problem. 4GB is not enough to run on GPU sadly.

**Comment by JulianTierno** [comment]
Now with -d cpu, begin process but get freeze at 0%.
![imagen](https://user-images.githubusercontent.com/6537228/70525348-6cc99680-1b47-11ea-8d45-2cff3f0133fd.png)

**Comment by rokimoki** [comment]
Se toma un tiempo, ten paciencia, has podido separar?

**Comment by adefossez** [comment]
@JulianTierno , this progress bar initially did not show progress within one track, just how many tracks have been processed so far. I have changed that as it was counter intuitive! If you update your repo, the progress bar will update as it separates the track. On my laptop, it takes roughly the same time as the duration of the track to separate.

**Comment by Jordan326** [comment]
he tenido el mismo problema , agregando "-d cpu" logro solucionar el problema ?

**Comment by adefossez** [comment]
@Jordan326 , I'm going to close this issue, if you use `-d cpu`, there should be no problem. If you do encounter a problem you can open a new issue.
