### ISSUE TITLE
Process got killed when evaluating on the test set

### ISSUE THREAD

**Issue by gold90123** [facebookresearch/demucs#465]
This is the situation when my process got killed.
![圖片](https://user-images.githubusercontent.com/76434705/231691084-507e3762-9460-4384-9e25-e514074685f6.png)
I have attempted multiple times, but it gets stuck at this stage each time
I'm training ht-demucs with musdbHQ on a RTX3090, and I have decreased the batch size to 4 and the epoch to 23 to ensure the model has the same numbers of iterations as the original.
I suspect that the process was terminated because I did not reduce the batch size of the evaluation stage, but I don't know how to do so, also, or if that is the cause of the issue.
Thanks for anyone's help!!

**Comment by adefossez** [comment]
Can you try with test.workers=0 
You might want to edit conf/config.yaml to add "test.workers" to the `dora.ignore` list, as otherwise this will restart training from scratch!

**Comment by gold90123** [comment]
I attempted to train the model using "dora.ignore" and set "test.workers=0", I even restarted the training from the beginning.
But unfortunately, it was still terminated at the same stage.
Nonetheless, I'm still grateful for your assistance, @adefossez 
![圖片](https://user-images.githubusercontent.com/76434705/232046987-15ed853b-c1a0-44f6-b73b-baba37fd8204.png)

**Comment by bogdanteleaga** [comment]
I had this problem recently and got around it by changing this ProcessPoolExecutor to a ThreadPoolExecutor in [this file](https://github.com/facebookresearch/demucs/blob/main/demucs/evaluate.py#L99).

Hope it helps!

**Comment by gold90123** [comment]
Thanks, @bogdanteleaga 
After I changed the ProcessPoolExecutor to a ThreadPoolExecutor, the process won't got killed anymore.
But! There's another problem occurred, I will post the new problem at another page.
The new problem is at #469
