### ISSUE TITLE
Automix script error

### ISSUE THREAD

**Issue by RavenV-tiff** [facebookresearch/demucs#470]
## ❓ Questions
This is my first attempt at demucs training with a custom dataset. I followed the current guide using the Musdb HQ to get familiar with the automix script however I am running into an issue. I modified the scripts to point to the directories with the datasets. I am using a fresh install of Ubuntu WSL on Windows 10 using Linux Anaconda and running in the demucs env.
```python
(demucs) raven@DESKTOP-38LQ83R:/mnt/c/Users/raven/demucs$ export NUMBA_NUM_THREADS=1; python3 -m tools.automix
100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1545.78it/s]
  0%|                                                                                            | 0/86 [00:05<?, ?it/s]
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/raven/anaconda3/envs/demucs/lib/python3.9/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/mnt/c/Users/raven/demucs/tools/automix.py", line 81, in analyse_track
    tempo, events = beat_track(drums.numpy(), units='time', sr=SR)
TypeError: beat_track() takes 0 positional arguments but 1 positional argument (and 2 keyword-only arguments) were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/raven/anaconda3/envs/demucs/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/raven/anaconda3/envs/demucs/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/raven/demucs/tools/automix.py", line 343, in <module>
    main()
  File "/mnt/c/Users/raven/demucs/tools/automix.py", line 312, in main
    spec, track = pending.result()
  File "/home/raven/anaconda3/envs/demucs/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/raven/anaconda3/envs/demucs/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
TypeError: beat_track() takes 0 positional arguments but 1 positional argument (and 2 keyword-only arguments) were given
``` 
beat_track() is in the librosa package which when I reinstalled did not change the error.

**Comment by adefossez** [comment]
can you git pull and try again?

**Comment by RavenV-tiff** [comment]
> can you git pull and try again?

I went ahead and removed the old env and redid the demucs environment setup process. I did not encounter this error again after. That may have been my own error, so apologies for that. I did encounter another error. librosa installed incorrectly the first time using the usual pip install method and I encountered ModuleNotFoundError: No module named 'numba.decorators' running automix.py. This was solved by `pip3 uninstall --yes librosa` and `pip3 install librosa --force-reinstall`.

I do still encounter another issue, and this may be me not having the configure file correctly setup, but the script seems to hang after a random percentage. It will drop down a line in the terminal an do nothing afterwards. This is with the newest script and with the old one with the commits removed.
`(demucs) raven@DESKTOP-38LQ83R:/mnt/c/Users/raven/demucs$ export NUMBA_NUM_THREADS=1; python3 -m tools.automix
100%|███████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 1501.50it/s]
 41%|█████████████████████████████████▊                                                 | 35/86 [00:27<00:40,  1.26it/s]`
I'll keep looking into what might be causing it but the issue I opened with was likely my own error.
