### ISSUE TITLE
Python API?

### ISSUE THREAD

**Issue by boxabirds** [facebookresearch/demucs#472]
# ❓How do I use demucs in Python directly?

I'm trying to run demucs as part of my python programme. 

Apologies if this seems naive but try as I might I can't find out how to use demucs from python directly. I have the pip package installed ok (I think) but it's literally as simple as me not knowing how to call the methods. Normally when you've installed a python package the autocomplete methods provide guidance for what the methods are but `demucs` doesn't. 

For example this doesn't work -- the `separate` method isn't found. nor is `separate_into_files` etc etc. 

```
from demucs import demucs 
demucs.separate(input_filename, sources=['vocals'], out_dir='output', suffix='vocals')
```
with error
`separate: unknown`

Alternatively I tried
```
from demucs import demucs
model = demucs.Demucs('demucs', 2)
model.separate(input_filename, sources=['vocals'], out_dir='output', suffix='vocals')

```

with error `AttributeError: 'Demucs' object has no attribute 'separate'`

**Comment by CarlGao4** [comment]
There is no API of demucs. I'll add one.
