### ISSUE TITLE
Should i change group_size to 2? Using 4 24gb GPUs batch size 8

### ISSUE THREAD

**Issue by lyndonlauder** [facebookresearch/demucs#481]
I am training your transformer demucs with 4 24gb gpus, total batch size=8.
I read in your paper that remixing the sources is good for performance, since i am using batch size 8 (batch size 2 per gpu) would you recommend i change the group_size to 2 in this setting or keep it at 4?

remix:
   proba: 1
   group_size: 4

I hope you can answer this message.

**Comment by adefossez** [comment]
In my experience 2 will highly increase the chance that two stems from the same track are still together after shuffling. This has an impact on the final performance. If you can fit in 3 with a batch size of 12 for instance and set it to 3 that would be better!
