### ISSUE TITLE
non-filesystem usage of API

### ISSUE THREAD

**Issue by davies-w** [facebookresearch/demucs#488]
## ❓ Questions

I'm excited that you added an API call so we dont need to sub-process it anymore, but I was wondering if it's possible to avoid the filesystem altogether. I have a pipeline where the songs are already read in from MP3s and I'd like to have them go from wav array to wav array (or aac, np, you know what I mean).  Maybe it's already there, but it's not obvious to me how to make this happen.

TIA,
 Winton

**Comment by CarlGao4** [comment]
You can close this issue since you’ve figured it out

**Comment by davies-w** [comment]
Thanks Carl, I'll follow-up in the other thread regarding not being able to reproduce the same quality separation.
