### ISSUE TITLE
It's possible in iOS

### ISSUE THREAD

**Issue by juasbhu28** [facebookresearch/demucs#49]
In the Readme talks about the Windows SO and Linux but I have a Mac, maybe it's possible in a Mac?

**Comment by rokimoki** [comment]
Yes, you can run in MacOSX.

1.- Download Anaconda 3.7 64 bits for MacOS: https://www.anaconda.com/distribution/#download-section
2.- Open Anaconda Prompt in MacOSX: https://docs.anaconda.com/anaconda/user-guide/getting-started/#open-nav-mac
3.- Follow this commands:
`cd ~
conda install git
git clone https://github.com/facebookresearch/demucs
cd demucs
conda env update -f environment-cpu.yml
conda activate demucs
python3 -m demucs.separate --dl -n demucs PATH_TO_AUDIO_FILE_1 [PATH_TO_AUDIO_FILE_2 ...] # for Demucs`

You can drag the .mp3 file to the console and it will paste the mp3 path.

**Comment by juasbhu28** [comment]
Thanks you, I'm going to try and then I tell you that happened.
