### ISSUE TITLE
device=cpu, Too high memory usage when processing long audio

### ISSUE THREAD

**Issue by comienzo2093** [facebookresearch/demucs#498]
```
-d cpu -n htdemucs --two-stems vocals
```

When processing audio that is about 1 hour long, the memory usage is about 7 GB. 
However, when processing audio that is 4 hours long, the memory usage exceeds 34 GB.

- Operating system and version (desktop or mobile): macOS 13.4
- Hardware: cpu, M1 MBP14 16GB
- Model: htdemucs

**Comment by CarlGao4** [comment]
The comments you've found have already been used in the latest codes. These only optimise GPU RAM, but has not effect on system memory.

**Comment by CarlGao4** [comment]
I tried to calculate the memory requirements here: https://github.com/facebookresearch/demucs/issues/463#issuecomment-1501137787
You can see if it matches your situation

**Comment by CarlGao4** [comment]
Then, about 7GiB is required when separating an audio that is about 1hr long, 28GiB is required when separating an audio that is about 4hr long

**Comment by comienzo2093** [comment]
I have reopened the issue as it appears there is something else going on.

On an hour-long audio, the process reliably uses only about 7GB of RAM from start to finish.

However, when working with longer lengths of audio, around 4 hours, the system RAM usage (including swap) continues to increase until the job is complete. It even exceeds 55 GB.

I understand that memory usage can vary depending on the length of the audio, but the constant increase in ram usage only during long audio tasks seems problematic.

Translated with www.DeepL.com/Translator (free version)

**Comment by CarlGao4** [comment]
Can you help me find out which codes require so much memory? What you need to do is that installing my modified codes: `pip install -U git+https://github.com/CarlGao4/demucs@trace-memory`
Then separate your audio and upload the outputs here

**Comment by comienzo2093** [comment]
> Can you help me find out which codes require so much memory? What you need to do is that installing my modified codes: `pip install -U git+https://github.com/CarlGao4/demucs@trace-memory`
> Then separate your audio and upload the outputs here

Memory info before loading model: pfullmem(rss=231292928, vms=419702210560, pfaults=24733, pageins=3396, uss=172539904)
Memory info after loading model: pfullmem(rss=487997440, vms=419861561344, pfaults=41593, pageins=3451, uss=349585408)
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /Users/hoon/Documents/dev/S-Whisper/separated/htdemucs
Separating track /Volumes/ssd10/jellyfin/AV/SSIS-721/hhd800.com@SSIS-721.wav
Memory info after loading track: pfullmem(rss=739966976, vms=425080356864, pfaults=759755, pageins=3476, uss=677543936)
Memory info after separating offset 0 out of 5.85: pfullmem(rss=3063726080, vms=456363114496, pfaults=4454711, pageins=3480, uss=2387197952)
Memory info after separating offset 257985 out of 5.85: pfullmem(rss=3004203008, vms=456364163072, pfaults=4552384, pageins=3480, uss=2271412224)
Memory info after separating offset 515970 out of 5.85: pfullmem(rss=3071393792, vms=456364163072, pfaults=4647774, pageins=3480, uss=2282946560)
Memory info after separating offset 773955 out of 5.85: pfullmem(rss=3088515072, vms=456364163072, pfaults=4739099, pageins=3480, uss=2294333440)
Memory info after separating offset 1031940 out of 5.85: pfullmem(rss=3108175872, vms=456364163072, pfaults=4831586, pageins=3480, uss=2305720320)
Memory info after separating offset 1289925 out of 5.85: pfullmem(rss=3136012288, vms=456364163072, pfaults=4923562, pageins=3480, uss=2317041664)
Memory info after separating offset 1547910 out of 5.85: pfullmem(rss=3009396736, vms=456364163072, pfaults=5015879, pageins=3480, uss=2207318016)
Memory info after separating offset 1805895 out of 5.85: pfullmem(rss=3034497024, vms=456364163072, pfaults=5107689, pageins=3480, uss=2218655744)
Memory info after separating offset 2063880 out of 5.85: pfullmem(rss=3045867520, vms=456364163072, pfaults=5199670, pageins=3480, uss=2229993472)
Memory info after separating offset 2321865 out of 5.85: pfullmem(rss=3063070720, vms=456364163072, pfaults=5290999, pageins=3480, uss=2241347584)
Memory info after separating offset 2579850 out of 5.85: pfullmem(rss=3074473984, vms=456364163072, pfaults=5382983, pageins=3480, uss=2252750848)
Memory info after separating offset 2837835 out of 5.85: pfullmem(rss=3000123392, vms=456364163072, pfaults=5473963, pageins=3480, uss=2188591104)
Memory info after separating offset 3095820 out of 5.85: pfullmem(rss=3019866112, vms=456364163072, pfaults=5566455, pageins=3480, uss=2199945216)
Memory info after separating offset 3353805 out of 5.85: pfullmem(rss=3033006080, vms=456364163072, pfaults=5657535, pageins=3480, uss=2211282944)
Memory info after separating offset 3611790 out of 5.85: pfullmem(rss=2935996416, vms=456364163072, pfaults=5749851, pageins=3480, uss=2120843264)
Memory info after separating offset 3869775 out of 5.85: pfullmem(rss=2960883712, vms=456364163072, pfaults=5841648, pageins=3480, uss=2132180992)
Memory info after separating offset 4127760 out of 5.85: pfullmem(rss=2977103872, vms=456364163072, pfaults=5933925, pageins=3480, uss=2143617024)
Memory info after separating offset 4385745 out of 5.85: pfullmem(rss=2996879360, vms=456364163072, pfaults=6025411, pageins=3480, uss=2154987520)
Memory info after separating offset 4643730 out of 5.85: pfullmem(rss=2998321152, vms=456364163072, pfaults=6118757, pageins=3480, uss=2162884608)
Memory info after separating offset 4901715 out of 5.85: pfullmem(rss=3016671232, vms=456364163072, pfaults=6210155, pageins=3480, uss=2174222336)
Memory info after separating offset 5159700 out of 5.85: pfullmem(rss=3015016448, vms=456364163072, pfaults=6303111, pageins=3480, uss=2185560064)
Memory info after separating offset 5417685 out of 5.85: pfullmem(rss=3031203840, vms=456364163072, pfaults=6394377, pageins=3480, uss=2197045248)
Memory info after separating offset 5675670 out of 5.85: pfullmem(rss=2999074816, vms=456364163072, pfaults=6488274, pageins=3480, uss=2166980608)
Memory info after separating offset 5933655 out of 5.85: pfullmem(rss=3023470592, vms=456364163072, pfaults=6580041, pageins=3480, uss=2178318336)
Memory info after separating offset 6191640 out of 5.85: pfullmem(rss=2906783744, vms=456364163072, pfaults=6673799, pageins=3480, uss=2061631488)
Memory info after separating offset 6449625 out of 5.85: pfullmem(rss=2783297536, vms=456364163072, pfaults=6773187, pageins=3480, uss=1948254208)
Memory info after separating offset 6707610 out of 5.85: pfullmem(rss=2803990528, vms=456364163072, pfaults=6865791, pageins=3480, uss=1959165952)
Memory info after separating offset 6965595 out of 5.85: pfullmem(rss=2789982208, vms=456364163072, pfaults=6956978, pageins=3480, uss=1970520064)
Memory info after separating offset 7223580 out of 5.85: pfullmem(rss=2495692800, vms=456364163072, pfaults=7050210, pageins=3480, uss=1747730432)
Memory info after separating offset 7481565 out of 5.85: pfullmem(rss=2576154624, vms=456364163072, pfaults=7145400, pageins=3480, uss=1758789632)
Memory info after separating offset 7739550 out of 5.85: pfullmem(rss=2590228480, vms=456364163072, pfaults=7237611, pageins=3480, uss=1770127360)
Memory info after separating offset 7997535 out of 5.85: pfullmem(rss=2602156032, vms=456364163072, pfaults=7328618, pageins=3480, uss=1781383168)
Memory info after separating offset 8255520 out of 5.85: pfullmem(rss=2615689216, vms=456364163072, pfaults=7420730, pageins=3480, uss=1792737280)
Memory info after separating offset 8513505 out of 5.85: pfullmem(rss=2492514304, vms=456364163072, pfaults=7511702, pageins=3480, uss=1724219392)
Memory info after separating offset 8771490 out of 5.85: pfullmem(rss=2539208704, vms=456364163072, pfaults=7605839, pageins=3480, uss=1735573504)
Memory info after separating offset 9029475 out of 5.85: pfullmem(rss=2474065920, vms=456364163072, pfaults=7697317, pageins=3480, uss=1673199616)
Memory info after separating offset 9287460 out of 5.85: pfullmem(rss=2480848896, vms=456364163072, pfaults=7789297, pageins=3480, uss=1679998976)
Memory info after separating offset 9545445 out of 5.85: pfullmem(rss=2456010752, vms=456364163072, pfaults=7881654, pageins=3480, uss=1657798656)
Memory info after separating offset 9803430 out of 5.85: pfullmem(rss=2449522688, vms=456364163072, pfaults=7975652, pageins=3480, uss=1654210560)
Memory info after separating offset 10061415 out of 5.85: pfullmem(rss=2287271936, vms=456364163072, pfaults=8074319, pageins=3480, uss=1497317376)
Memory info after separating offset 10319400 out of 5.85: pfullmem(rss=2165637120, vms=456364163072, pfaults=8171425, pageins=3480, uss=1384759296)
Memory info after separating offset 10577385 out of 5.85: pfullmem(rss=2187100160, vms=456364163072, pfaults=8263399, pageins=3480, uss=1396097024)
Memory info after separating offset 10835370 out of 5.85: pfullmem(rss=1933705216, vms=456364163072, pfaults=8357103, pageins=3480, uss=1196359680)
Memory info after separating offset 11093355 out of 5.85: pfullmem(rss=1995096064, vms=456364163072, pfaults=8451129, pageins=3480, uss=1207730176)
Memory info after separating offset 11351340 out of 5.85: pfullmem(rss=1992572928, vms=456364163072, pfaults=8543181, pageins=3480, uss=1209188352)
Memory info after separating offset 11609325 out of 5.85: pfullmem(rss=2009694208, vms=456364163072, pfaults=8634505, pageins=3480, uss=1220542464)
Memory info after separating offset 11867310 out of 5.85: pfullmem(rss=2021048320, vms=456364163072, pfaults=8726485, pageins=3480, uss=1231896576)
Memory info after separating offset 12125295 out of 5.85: pfullmem(rss=2034827264, vms=456364163072, pfaults=8817604, pageins=3480, uss=1243250688)
Memory info after separating offset 12383280 out of 5.85: pfullmem(rss=2051129344, vms=456364163072, pfaults=8909886, pageins=3480, uss=1254604800)
Memory info after separating offset 12641265 out of 5.85: pfullmem(rss=2066694144, vms=456364163072, pfaults=9001115, pageins=3480, uss=1265958912)
Memory info after separating offset 12899250 out of 5.85: pfullmem(rss=1942306816, vms=456364163072, pfaults=9093379, pageins=3480, uss=1146486784)
Memory info after separating offset 13157235 out of 5.85: pfullmem(rss=1955037184, vms=456364163072, pfaults=9184435, pageins=3480, uss=1157840896)
Memory info after separating offset 13415220 out of 5.85: pfullmem(rss=1967718400, vms=456364163072, pfaults=9276496, pageins=3480, uss=1169195008)
...
...
...
Memory info after separating offset 633353175 out of 5.85: pfullmem(rss=2807250944, vms=456364163072, pfaults=231301573, pageins=3480, uss=1997733888)
Memory info after separating offset 633611160 out of 5.85: pfullmem(rss=2789031936, vms=456364163072, pfaults=231394827, pageins=3480, uss=1992572928)
Memory info after separating offset 633869145 out of 5.85: pfullmem(rss=2820210688, vms=456364163072, pfaults=231487010, pageins=3480, uss=2003927040)
Memory info after separating offset 634127130 out of 5.85: pfullmem(rss=2785460224, vms=456364163072, pfaults=231580580, pageins=3480, uss=1993211904)
Memory info after separating offset 634385115 out of 5.85: pfullmem(rss=2812592128, vms=456364163072, pfaults=231672515, pageins=3480, uss=2004566016)
Memory info after separating offset 634643100 out of 5.85: pfullmem(rss=2773237760, vms=456364163072, pfaults=231765610, pageins=3480, uss=1984577536)
Memory info after separating offset 634901085 out of 5.85: pfullmem(rss=2800910336, vms=456364163072, pfaults=231857578, pageins=3480, uss=1995898880)
Memory info after separating offset 635159070 out of 5.85: pfullmem(rss=2814132224, vms=456364163072, pfaults=231949672, pageins=3480, uss=2006990848)
Memory info after separating offset 635417055 out of 5.85: pfullmem(rss=2821816320, vms=456364163072, pfaults=232040303, pageins=3480, uss=2014380032)
run.sh: line 6:  7087 Killed: 9               pipenv run python ./main.py
/Users/hoon/.pyenv/versions/3.10.11/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by CarlGao4** [comment]
I’m quite confused that why psutil can’t receive the correct memory it uses. According to the logs, it is using 390GiB of memory, of course it can’t.

**Comment by CarlGao4** [comment]
According to this issue https://github.com/giampaolo/psutil/issues/1908, I need to find another way to get the correct memory usage ...

**Comment by CarlGao4** [comment]
I’ve changed some `print` into `input`. Please update it using the same command (pip).
When the program stops, please retrieve the memory info in top or something like that and input it. It won’t save the value, but just for me to see.

**Comment by comienzo2093** [comment]
> I’ve changed some `print` into `input`. Please update it using the same command (pip).
> When the program stops, please retrieve the memory info in top or something like that and input it. It won’t save the value, but just for me to see.

감사합니다. 그러나 아래와 같은 에러가 발생합니다.

**Comment by CarlGao4** [comment]
Ahh, my problem. Please try again now.

**Comment by CarlGao4** [comment]
Please remember to input `Virtual Memory` like this:
|PID|USER|PR|NI|VIRT|RES|SHR|S|%CPU|%MEM|TIME+|COMMAND|
|-|-|-|-|-|-|-|-|-|-|-|-|
|1213|root|20|0|**<u>2576</u>**|1740|1572|S|0.0|0.0|0:00.96|sh|

**Comment by CarlGao4** [comment]
I'm trying this on Windows since Windows provides an API that can get `peak_pagefile` so it will be easier to track allocations

**Comment by CarlGao4** [comment]
<details>
<summary>An audio that is 24min long</summary>

```
Memory info before loading model: pfullmem(rss=345473024, vms=779448320, num_page_faults=85315, peak_wset=345473024, wset=345473024, peak_paged_pool=8797152, paged_pool=8796952, peak_nonpaged_pool=51648, nonpaged_pool=51520, pagefile=779448320, peak_pagefile=779448320, private=779448320, uss=217362432)
Memory info after loading model: pfullmem(rss=527036416, vms=958930944, num_page_faults=169928, peak_wset=603783168, wset=527036416, peak_paged_pool=8797160, paged_pool=8796952, peak_nonpaged_pool=64168, nonpaged_pool=59136, pagefile=958930944, peak_pagefile=1035829248, private=958930944, uss=396201984)
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in separated\htdemucs
Separating track xxx.flac
Memory info after loading track: pfullmem(rss=1037238272, vms=1469829120, num_page_faults=419722, peak_wset=1547137024, wset=1037238272, peak_paged_pool=8797848, paged_pool=8796952, peak_nonpaged_pool=69264, nonpaged_pool=59272, pagefile=1469829120, peak_pagefile=1980743680, private=1469829120, uss=907169792)
Memory info after separating offset 0.0 out of 1450.8: pfullmem(rss=3272806400, vms=7591854080, num_page_faults=2140271, peak_wset=4058677248, wset=3272806400, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=95584, nonpaged_pool=95584, pagefile=7591854080, peak_pagefile=7591854080, private=7591854080, uss=3050242048)
Memory info after separating offset 5.85 out of 1450.8: pfullmem(rss=3283382272, vms=7592652800, num_page_faults=2153102, peak_wset=4058677248, wset=3283382272, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=95856, nonpaged_pool=95584, pagefile=7592652800, peak_pagefile=7603740672, private=7592652800, uss=3060072448)
Memory info after separating offset 11.7 out of 1450.8: pfullmem(rss=3289579520, vms=7592652800, num_page_faults=2164863, peak_wset=4058677248, wset=3289579520, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=95856, nonpaged_pool=95584, pagefile=7592652800, peak_pagefile=7603740672, private=7592652800, uss=3066265600)
Memory info after separating offset 17.55 out of 1450.8: pfullmem(rss=3295768576, vms=7592652800, num_page_faults=2176622, peak_wset=4058677248, wset=3295768576, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=95856, nonpaged_pool=95584, pagefile=7592652800, peak_pagefile=7603740672, private=7592652800, uss=3072454656)
Memory info after separating offset 23.4 out of 1450.8: pfullmem(rss=3301969920, vms=7592652800, num_page_faults=2188384, peak_wset=4058677248, wset=3301969920, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=95856, nonpaged_pool=95584, pagefile=7592652800, peak_pagefile=7603740672, private=7592652800, uss=3078656000)

...

Memory info after separating offset 1433.25 out of 1450.8: pfullmem(rss=3723452416, vms=7592566784, num_page_faults=5261134, peak_wset=4058677248, wset=3723452416, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=96128, nonpaged_pool=95176, pagefile=7592566784, peak_pagefile=7603838976, private=7592566784, uss=3498041344)
Memory info after separating offset 1439.1 out of 1450.8: pfullmem(rss=3732303872, vms=7592566784, num_page_faults=5273543, peak_wset=4058677248, wset=3732303872, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=96128, nonpaged_pool=95176, pagefile=7592566784, peak_pagefile=7603838976, private=7592566784, uss=3506892800)
Memory info after separating offset 1444.95 out of 1450.8: pfullmem(rss=3737808896, vms=7592566784, num_page_faults=5284626, peak_wset=4058677248, wset=3737808896, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=96128, nonpaged_pool=95176, pagefile=7592566784, peak_pagefile=7603838976, private=7592566784, uss=3512397824)
Memory info after separation: pfullmem(rss=2221170688, vms=6992281600, num_page_faults=7552939, peak_wset=4260069376, wset=2221170688, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=101840, nonpaged_pool=101704, pagefile=6992281600, peak_pagefile=9381560320, private=6992281600, uss=2227146752)
Memory info after saving drums: pfullmem(rss=729501696, vms=6993297408, num_page_faults=9462504, peak_wset=5188354048, wset=729501696, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=101976, nonpaged_pool=101704, pagefile=6993297408, peak_pagefile=11080486912, private=6993297408, uss=728059904)
Memory info after saving bass: pfullmem(rss=1106870272, vms=6993297408, num_page_faults=9929692, peak_wset=5188354048, wset=1106870272, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=101976, nonpaged_pool=101704, pagefile=6993297408, peak_pagefile=11080486912, private=6993297408, uss=1106890752)
Memory info after saving other: pfullmem(rss=1540227072, vms=6993297408, num_page_faults=10411592, peak_wset=5188354048, wset=1540227072, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=101976, nonpaged_pool=101704, pagefile=6993297408, peak_pagefile=11080486912, private=6993297408, uss=1540247552)
Memory info after saving vocals: pfullmem(rss=2053804032, vms=6993334272, num_page_faults=10913099, peak_wset=5188354048, wset=2053804032, peak_paged_pool=8902416, paged_pool=8902416, peak_nonpaged_pool=102112, nonpaged_pool=101840, pagefile=6993334272, peak_pagefile=11080486912, private=6993334272, uss=2051784704)
```
</details>

**Comment by CarlGao4** [comment]
As you can see here, the memory usage is alwayse below 7.1GiB while separating, with only increases that can be ignored (`vms` is all allocated memory)
Only the save process require much memory

**Comment by comienzo2093** [comment]
> As you can see here, the memory usage is alwayse below 7.1GiB while separating, with only increases that can be ignored (`vms` is all allocated memory)
> Only the save process require much memory

I see, thank you. I've gotten similar results with short audio, so can you confirm that for very long audio (like hours), the ram increase during the operation is negligible?

**Comment by CarlGao4** [comment]
But I don't want to ruin my SSD - I only have 8GB RAM, so separating an audio that is 25min long has already used 10GB extra swap file (or about 0.05TBW)

**Comment by comienzo2093** [comment]
> But I don't want to ruin my SSD - I only have 8GB RAM, so separating an audio that is 25min long has already used 10GB extra swap file (or about 0.05TBW)

Anyway, thanks for your help. I have temporarily solved the problem by splitting long wav files and then using demucs.

**Comment by CarlGao4** [comment]
I've checked your comment https://github.com/facebookresearch/demucs/issues/498#issuecomment-1562202177 again and found that the separation process has already finished, it's the starting of writing files caused the crash. I've fixed the codes and opened a PR. 
Can you try installing my update by `pip install -U git+https://github.com/CarlGao4/demucs@4.0.1a2` and separate it again? 
P.S. You can add `--flac` to your command to use FLAC format as output which can save your disk without harming the quality of audio.

**Comment by thhung** [comment]
@CarlGao4 Did your code handle the problem with RAM? I have a long audio, about 41 mins. But it consumes all the RAM in the free colab. It seems because of some optimizations on the GPU parts at the expense of RAM.

**Comment by CarlGao4** [comment]
All the stems in full length will be stored in memory before writing to disk. You may split your file into shorter chunks before passing to demucs.
