### ISSUE TITLE
Issue with `rescale_conv` ?

### ISSUE THREAD

**Issue by npinto** [facebookresearch/demucs#505]
Hello, 

I'm curious if there is an implementation issue with the weight rescaling trick used in `rescale_conv`. I was expecting that if one already rescales the weights once, further calls would basically not change the weights further. However the simple test below shows otherwise.

```
import numpy as np
np.random.seed(42)
arr1 = 2*np.random.randn(100)
std1 = arr1.std()

def rescale(x, ref=0.1):
    val = x.std()
    scale = (val / ref) ** 0.5
    x /= scale
    return x

arr2 = rescale(arr1)
std2 = arr2.std()

arr3 = rescale(arr2)
std3 = arr3.std()
print(std1, std2, std3)
```

Outputs: `1.8072323532892591 0.42511555526577227 0.20618330564470355`

If the goal is to rescale the weights so that the *variance* (as the `**0.5`, i.e. sqrt implies), then we should use `val = x.var()` instead. If however one wants to fix the std, then we should use `scale = (val / ref)`.

Thoughts ?

**Comment by adefossez** [comment]
the original behavior is meant. Using 1/alpha would exactly correct the standard deviation, but that's not what we want. We only want to partially correct the original weight initialization which is known to be very good.

![Capture d’écran 2023-06-18 à 19 00 11](https://github.com/facebookresearch/demucs/assets/1990078/6692b52a-456d-4801-9cc7-716fb429b814)

**Comment by npinto** [comment]
Thanks for the clarification!

**Comment by vasanthzoh** [comment]
Hi @adefossez, thank you very much for your wonderful contributions to the research. I have a query regarding your statement.

> We only want to partially correct the original weight initialization which is known to be very good.

Is the original weight initialization chosen to be the Kaiming scheme? In the Demucs codebase, Kaiming initialization is not used and it is left to the default initialization used by PyTorch (which is the same as LeCun initialization as mentioned [here](https://github.com/pytorch/pytorch/issues/15314)). These weights initialized with the LeCun scheme are then rescaled using the proposed method.

Would rescaling after initializing with the Kaiming scheme result in a different behaviour?
