### ISSUE TITLE
Include Models in commercial products?

### ISSUE THREAD

**Issue by mattjacksonAI** [facebookresearch/demucs#508]
## ❓ Questions
I noticed that the models are trained on some data that is not allowed for academic or commercial use (Mixing Secrets).
"Can I use these multitracks as part of a research project?

While I’m inclined to feel that this does fall within the general spirit of ‘educational use’, it hasn’t been specifically agreed with contributors to the library. So please contact the relevant contributors directly to agree proper terms of usage in this case, especially if your research is for commercial purposes."
Have the relevant contributors been contacted?
Is it ok to use the trained models in commercial products? I See the the Demurs code is MIT, but what about the weights and biases in the model (htdemucs v4)?

**Comment by adefossez** [comment]
Weights are provided for research purpose!
