### ISSUE TITLE
Extracting voice only (single file output)

### ISSUE THREAD

**Issue by samuelbradshaw** [facebookresearch/demucs#511]
## ❓ Questions

Hi! Is it possible to extract the voice only, and discard the rest of the audio file?

I understand that it's possible to generate two output files – vocals and no_vocals – using the `--two-stems=vocals` option. This is great for some use cases. However, for my use case (preparing audio for speech to text transcription), I only need the vocals file. Skipping the no_vocals part seems like it could speed up the process.

**Comment by samuelbradshaw** [comment]
If I understand correctly, the "mixing" mentioned in the quoted documentation is mixing the `drums`, `base`, and `other` stems into a combined `no_vocals` track. If I wanted a `no_vocals` track, it makes sense that I would need to wait for `drums`, `base`, and `other`.

However, in my case, I don't need a `no_vocals` track. I only need the `vocal` stem. I don't think the vocal track has any mixing after extraction.

**Comment by CarlGao4** [comment]
The Demucs model will always extract all the stems defined in the model (Actually, other is not simply the rest, but also a stem generated like vocals and drums, etc.). `--two-stem` only save the stem you selected and add up the other stem and save it, so as long as you didn't use `--mp3` (mp3 encoders are very slow), saving the `no_vocals` stem will not cost too much time.

**Comment by adefossez** [comment]
Yep as CarlGao4 mentioned, anyway the model will separate all the stems. You will have to wait for a bit for it to write to disk but that seems acceptable. will close the issue!
