### ISSUE TITLE
conversion to mp3 extremely slow?

### ISSUE THREAD

**Issue by nicollegah** [facebookresearch/demucs#517]
Hi,

what an awesome library, thank you so much.

I am running this command demucs.separate.main(["--mp3", "-n", "mdx", filename]) and the last bit, where the .wav files get converted to .mp3s (?) takes 5 minutes or so. Without the mp3 flag it is much faster. It is the same if I do it outside python and it is the same on another machine. The instances running on Google Cloud.

Installed it like so: pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs

Any idea what the reason could be?

**Comment by CarlGao4** [comment]
You can try other mp3 encoders, it's the speed of encoding MP3.

**Comment by nicollegah** [comment]
I'm doing wav export and a manual ffmpeg call afterwards now, thanks.

**Comment by HoaAnDuong** [comment]
In theorically, call apply_model(model, waveform, num_workers=4, device="cuda") for running the model in GPU with 4 workers, but they accidentally forgot to add num_workers in kwargs. You can see my solution here:
https://github.com/facebookresearch/demucs/issues/528

**Comment by CarlGao4** [comment]
@HoaAnDuong encoding MP3 is not a part of apply_model

**Comment by CarlGao4** [comment]
I've found the reason. I'll fix that as soon as possible.

**Comment by iErcann** [comment]
Same issue here, for me it's faster to convert them to mp3 after with ffmpeg instead of using --mp3
