### ISSUE TITLE
Remote models are not available anymore

### ISSUE THREAD

**Issue by jarredou** [facebookresearch/demucs#518]
## 🐛 Bug Report

Models can't be download anymore:
for example, https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/04573f0d-f3cf25b2.th leads to error:
![image](https://github.com/facebookresearch/demucs/assets/6044199/8ea926b5-dc79-4439-b17b-e3df90f43fa8)

## To Reproduce

Try to access to remote models : https://dl.fbaipublicfiles.com/demucs/hybrid_transformer/04573f0d-f3cf25b2.th

## Expected behavior

Donwload model

## Actual Behavior

Link is dead

## Your Environment

not relevant.

**Comment by adefossez** [comment]
Models are still available on my end. Are you sharing IP address ? you might be rate limited.
