### ISSUE TITLE
License of dependency (GPLv3 lameenc)

### ISSUE THREAD

**Issue by rsxdalv** [facebookresearch/demucs#519]
## ❓ Questions

I'm installing this with audiocraft, so even though audiocraft and demucs are both MIT, I get a GPL dependency. Now I'm pretty sure I don't actually need lameenc to run audiocraft's musicgen, so the question is - what are the options to remove it?

pip show lameenc
Name: lameenc
Version: 1.4.2
Summary: LAME encoding bindings
Home-page: https://github.com/chrisstaite/lameenc
Author: Chris Staite
Author-email: chris@yourdreamnet.co.uk
License: GPLv3
Location: c:\users\admin\desktop\one-click-installers-tts-main\installer_files\env\lib\site-packages
Requires:
Required-by: demucs

**Comment by rsxdalv** [comment]
Relates to:
https://github.com/rsxdalv/tts-generation-webui/issues/47

**Comment by adefossez** [comment]
you can run `pip uninstall lameenc` and it shouldn't crash, although having it installed in the first place might already be a problem.

Good point anyway I should find a way to sort that out but I'm not sure how. Making it an optional dependency would be one possibility, but the terms of the GPL are not really accurate on what can and cannot be done and whether it would be enough.

For instance I could just write a small separate program that provides `lameenc` features through the command line, and rely on it being installed. As command line usage are not covered by the GPL then it would kind of work... It just feels like losing time for nothing. I remember software like Audacity asking to manually load some DLL that they couldn't bundle... 

Anyway I also asked upstream if a release under the LGPL license would be acceptable:https://github.com/chrisstaite/lameenc/issues/21

**Comment by adefossez** [comment]
Okay so lameenc is now LGPL, which removes all issues with using Demucs and Audiocraft as MIT.
Note that it might take a bit of time before this is reflected in PyPI, although legal risk seems clearly negligible now. Feel free to pre-install lameenc from directly from their repo if you do want the latest LGPL version :)

**Comment by rsxdalv** [comment]
That's awesome!
