### ISSUE TITLE
Missing of num_workers in kwargs in apply_model() (in apply.py), which results in NOT ABLE TO USE THE MODEL IN GPU

### ISSUE THREAD

**Issue by HoaAnDuong** [facebookresearch/demucs#528]
## 🐛 Bug Report
apply_model() (in apply.py) will get error if device = "cuda" and num_workers > 0 (aka if you want to use RUN THE MODEL IN GPU)
because you JUST FORGOT TO ADD "num_workers" IN DICT "kwargs" IN apply model() (at line 152 of apply.py):

kwargs = {
        'shifts': shifts,
        'split': split,
        'overlap': overlap,
        'transition_power': transition_power,
        'progress': progress,
        'device': device,
        'pool': pool,
        'num_workers':num_workers #here what you're missing
}
which is result in sub apply_model()(s) recursively called by their parent will NOT HAVE "num_workers" parameter, for example (from line 162 to line 182):

if isinstance(model, BagOfModels):
        estimates = 0
        totals = [0] * len(model.sources)
        for sub_model, weight in zip(model.models, model.weights):
            original_model_device = next(iter(sub_model.parameters())).device
            sub_model.to(device)
            out = apply_model(sub_model, mix, **kwargs) #HERE is where sub apply_model()(s) called
            sub_model.to(original_model_device)
            for k, inst_weight in enumerate(weight):
                out[:, k, :, :] *= inst_weight
                totals[k] += inst_weight
            estimates += out
            del out
        for k in range(estimates.shape[1]):
            estimates[:, k, :, :] /= totals[k]
        return estimates

which is result in the sub apply_model()(s) have to use num_workers = 0, which means the sub apply_model()(s) have to use a pool running in CPU(not GPU), which result in error when user try to run in GPU. Or if it work, it will run on CPU, which is take lots of time(ohh my 20 mins of life):

if pool is None:
        if num_workers > 0 and device.type == 'cpu':
            pool = ThreadPoolExecutor(num_workers)
        else:
            pool = DummyPoolExecutor()

In Short, the Missing of just a Paramters(num_workers) in called sub recursively apply_model() will result in a quite big consequence, which is make the user cannot RUN THE MODEL ON THE GPU(WHICH MAKES MISERABLE USERS HAVE TO RUN THE MODEL IN CPU AND LOST A LOT OF TIME)

p/s: Don't worry to me, I don't mind that much.

## How to fix that

Just add num_workers in kwargs in apply_model()'s code (in apply.py)

kwargs = {
        'shifts': shifts,
        'split': split,
        'overlap': overlap,
        'transition_power': transition_power,
        'progress': progress,
        'device': device,
        'pool': pool,
        'num_workers':num_workers #here what you're missing
}

## Your Environment

I use Colab for running the model and Install demucs via: ! pip install -U demucs

- Python and PyTorch version:
Python: 3.10.6
torch: 2.0.1+cu118
torchaudio: 2.0.2+cu118
- Operating system and version (desktop or mobile): Linux
- Hardware (gpu or cpu, amount of RAM etc.): GPU, Main RAM: 12.7 GB, GPU RAM: 15.0 GB

**Comment by CarlGao4** [comment]
In my opinion, it isn't a mistake. In the docstring of apply_model, you can see that multiple jobs using GPU is not supported. It seems that separating on GPU is not thread-safe, so this operation is disabled.

Besides, this is also useless as PyTorch can use all the GPU/CPU resources so using multiple jobs could actually slow down the operation unless you have more than one GPU. And when you achieve this, you will need to run the program multiple times to use different GPU.

**Comment by HoaAnDuong** [comment]
It's actually an error bro. The model isn't work on GPU just because sub apply_model() is called without num_workers passed on kwargs(which i mentioned in my bug report)
, which result in having to use default num_workers = 0 and the pool used is running on CPU. The error will occured when you trying to use GPU

The solution is so simple, just find the kwargs in def apply_model() in apply.py and add num_workers = num_workers:

kwargs = {
'shifts': shifts,
'split': split,
'overlap': overlap,
'transition_power': transition_power,
'progress': progress,
'device': device,
'pool': pool,
'num_workers':num_workers #here what you're missing
}

p/s: If you use CPU, It will take a lot of time (approximately 15 mins, fcking long) to run. When i fixed the bugs and run on GPU(with 4 workers), it take only 22 sec (just 22 sec trust me)

**Comment by CarlGao4** [comment]
It actually works as long as you set device to CUDA. In fact, using multiple threads will make it slower. You can try all by yourself or read the codes. 
Feel free to ask questions if you encounter any problem. But I'm sure that the codes here have no error. Maybe you can tell me how you used this program?

**Comment by HoaAnDuong** [comment]
I did clone Decums.ipynb and run it on colab: https://colab.research.google.com/drive/1Xud-wUYTOUAATK3KmzBYceUsO62Hd16Y#scrollTo=kOjIPLlzhPfn
In this colab, i install demucs from PyPi: 
!pip install -U demucs

Next, i chose default device(which is cuda) and import the pretrained model:

import torch
device = "cuda" if torch.cuda.is_available() else "cpu"

from demucs import pretrained
model = pretrained.get_model('mdx')
model = model.to(device)

Then, I create waveform tensor from mp3 file:

import torch
import torchaudio
name = "[YT2mp3.info] - MONO - Em Là (Official Music Video) (320kbps)"
waveform, sample_rate = torchaudio.load(f"/content/{name}.mp3")
waveform.to(device)
print(waveform.shape,sample_rate)
print(waveform)

After that, i make it generate output using apply_model(), with num_workers = 4 and device = "cuda"

from demucs.apply import apply_model
x = waveform.reshape(1,waveform.shape[0],waveform.shape[1])
print(x)

out = apply_model(model, x,num_workers=4,device=device)[0]
for name, source in zip(model.sources, out):
    print(name, source.std() / x.std())

And then, the error occurred because of Tensors differences(CPU and GPU at the same time)

After fixing that bug (just added num_workers on dict kwargs on apply_model()'s code in apply.py), i did generate outputs from a 4-mins song in just 22 secs (in opposite of 15 mins when running on CPU)

Maybe it's run fast in cmd, but a bug appeared in Python program(which make a large model not able to run on GPU) is still a big deal(it's actually not so big but really annoying for people who didn't know the bug)

**Comment by HoaAnDuong** [comment]
p/s: I'm a big fan of MONO(a newborn star in Vietnam :v), and I'm researching this model for creating more output channel(not just default 4 channels like other,vocal,drum,bass)(i want to extract more channels like synth instrument, nature instrument,etc.)

**Comment by CarlGao4** [comment]
If you are running demucs in an interactive python shell (like colab), using the API is suggested. 

https://github.com/CarlGao4/demucs

To install, replace `pip install demucs` with `pip install -U git+ https://github.com/CarlGao4/demucs #egg=demucs`

**Comment by adefossez** [comment]
Thanks for the detailed report. Happy to accept a PR on this.

**Comment by adefossez** [comment]
> I did clone Decums.ipynb and run it on colab: https://colab.research.google.com/drive/1Xud-wUYTOUAATK3KmzBYceUsO62Hd16Y#scrollTo=kOjIPLlzhPfn In this colab, i install demucs from PyPi: !pip install -U demucs
> 
> Next, i chose default device(which is cuda) and import the pretrained model:
> 
> import torch device = "cuda" if torch.cuda.is_available() else "cpu"
> 
> from demucs import pretrained model = pretrained.get_model('mdx') model = model.to(device)
> 
> Then, I create waveform tensor from mp3 file:
> 
> import torch import torchaudio name = "[YT2mp3.info] - MONO - Em Là (Official Music Video) (320kbps)" waveform, sample_rate = torchaudio.load(f"/content/{name}.mp3") waveform.to(device) print(waveform.shape,sample_rate) print(waveform)
> 
> After that, i make it generate output using apply_model(), with num_workers = 4 and device = "cuda"
> 
> from demucs.apply import apply_model x = waveform.reshape(1,waveform.shape[0],waveform.shape[1]) print(x)
> 
> out = apply_model(model, x,num_workers=4,device=device)[0] for name, source in zip(model.sources, out): print(name, source.std() / x.std())
> 
> And then, the error occurred because of Tensors differences(CPU and GPU at the same time)
> 
> After fixing that bug (just added num_workers on dict kwargs on apply_model()'s code in apply.py), i did generate outputs from a 4-mins song in just 22 secs (in opposite of 15 mins when running on CPU)
> 
> Maybe it's run fast in cmd, but a bug appeared in Python program(which make a large model not able to run on GPU) is still a big deal(it's actually not so big but really annoying for people who didn't know the bug)

You are not moving the waveform to cuda. for tensor, `.to` is not inplace, it returns a new tensor object.

**Comment by adefossez** [comment]
Also please use code blocks in issues using triple backquote, it is impossible to read otherwise.
Closing the issue!
