### ISSUE TITLE
Phase left out of the model?

### ISSUE THREAD

**Issue by Lucasjuv** [facebookresearch/demucs#529]
## ❓ Questions

Congratulations for the good work. I understand that using the spectrogram makes a lot of sense to identify sound sources but why did you leave the phase out? I mean for most of us phase data could be considered irrelevant but I believe it holds valuable data about the timber of a sound. It also should be available when you process the spectrogram with an FFT. Is there any reason to leave out the phase data out of the model?

**Comment by adefossez** [comment]
The model contains both a waveform and a spectrogram branch, so phase is always in the waveform. Anyway the spectrogram one is using the complex spectrogram so the phase is in, although it does not make much difference with just using masking when combined with the waveform branch.

**Comment by Lucasjuv** [comment]
Oh, thanks 😅. I didn't see that part.
