### ISSUE TITLE
When using a python program to loop through demucs.separate.main, there seems to be a memory leak bug. (Especially the mdx_q model)

### ISSUE THREAD

**Issue by haotlong** [facebookresearch/demucs#535]
## 🐛 Bug Report

(A clear and concise description of what the bug is)

## To Reproduce

(Write your steps here:)

1. Step 1...
1. Step 2...
1. Step 3...

## Expected behavior

(Write what you thought would happen.)

## Actual Behavior

(Write what happened. Add screenshots, if applicable.)

## Your Environment

- Python and PyTorch version:
- Operating system and version (desktop or mobile):
- Hardware (gpu or cpu, amount of RAM etc.):

**Comment by CarlGao4** [comment]
(You can close this issue now)

**Comment by haotlong** [comment]
thank you
