### ISSUE TITLE
[Request] 22GBytes GPU memory parameter settings

### ISSUE THREAD

**Issue by flipflop98** [facebookresearch/demucs#54]
I have small GPU memory problem with my V40 Nvidia GPU (22GBytes).

Could you give me the parameter settings ? 
Originally, the default parameters maybe related with the GPU memeory are as follows;
"batch_size = 16", "num_channels = 64" and etc... 

If there are proper parameters to fit to the 22 GBytes GPU memeory, please let me know the 
parameters and setting values.

Thank you in advance.

**Comment by adefossez** [comment]
You can use batch size = 4 and hopefully it should work
