### ISSUE TITLE
[Request] Separation by specified segments

### ISSUE THREAD

**Issue by Infinitay** [facebookresearch/demucs#544]
Would it be possible to add support to specify one or more timestamps alongside a given file to only isolate the audio sources within that segment?

Some parameter examples
- For a single segment `--start 1:00:00 --end 1:05:00`
- For multiple segments `--segments 1:00:00-1:05:00,2:00:00-2:05:00` or something similar

Adding support for even one segment would be appreciate too and we could just loop through the timestamps ourselves

**Comment by adefossez** [comment]
You can already do that using ffmpeg, which should be installed if you followed the instructions:
```
ffmpeg -i INPUT_AUDIO_FILE.mp3 -ss 120 -t 30 segment_1.wav
```
This will extract starting at second 120 and keep 30 seconds. `ffmpeg` supports all input format, not just mp3s used here for the example.

The goal is to keep things as simple as possible here, so anything that can be done with ffmpeg should be done with ffmpeg :)

**Comment by Infinitay** [comment]
> The goal is to keep things as simple as possible here, so anything that can be done with ffmpeg should be done with ffmpeg :)

Fair enough, I will go ahead and rely on ffmpeg again. Thanks for the response.
