### ISSUE TITLE
part of the sound is lost

### ISSUE THREAD

**Issue by zyk-mjzs** [facebookresearch/demucs#548]
## 🐛 Bug Report

Part of the sound is missing after a song is detached

## To Reproduce

Use `兰音Reine - 神魂颠倒.mp3` as a test case

Lanyin Reine - Fascinated.mp3

## Expected behavior

Split out multiple audio tracks

## Actual Behavior

The number of tracks matches the number of settings, but parts of the sound are missing

**Comment by CarlGao4** [comment]
What is your command?

**Comment by zyk-mjzs** [comment]
demucs -n htdemucs_6s {file_name} --overlap 0.6

Most of the songs are fine, only this one has a problem

**Comment by CarlGao4** [comment]
Can you send a sample file?

**Comment by zyk-mjzs** [comment]
https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/20230907184937.mp3




---Original---
From: "Weiqi ***@***.***&gt;
Date: Thu, Sep 7, 2023 18:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/demucs] part of the sound is lost (Issue #548)




 
Can you send a sample file?

**Comment by CarlGao4** [comment]
I used the same command as yours, and the outputs are correct. Maybe you can provide a sample of your separated audio?

**Comment by zyk-mjzs** [comment]
[vocal](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/vocals.mp3)
[bass](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/bass.mp3)
[drums](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/drums.mp3)
[guitar](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/guitar.mp3)
[piano](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/piano.mp3)
[others](https://test-1258029632.cos.ap-guangzhou.myqcloud.com/test/other.mp3)

Six audio tracks are playing at the same time, and it is found to be inconsistent with the source audio

**Comment by CarlGao4** [comment]
> parts of the sound are missing

I finally understand what you mean, I thought about that length of the audio could not match with the input file

Actually, `other` is also separated like other stems, but not simply using the whole audio minus separated stems, so you can't get the original audio by adding up all the stems including `other`

**Comment by zyk-mjzs** [comment]
Yes, so I would like to provide feedback




---Original---
From: "Weiqi ***@***.***&gt;
Date: Thu, Sep 7, 2023 20:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [facebookresearch/demucs] part of the sound is lost (Issue #548)




  
parts of the sound are missing
  
I finally understand what you mean, I thought about that length of the audio could not match with the input file
 
Actually, other is also separated like other stems, but not simply using the whole audio minus separated stems, so you can't get the original audio by adding up all the stems including other

**Comment by zyk-mjzs** [comment]
thanks, i got it

**Comment by CarlGao4** [comment]
In my opinion, this isn't a bug as it is designed to extract a specific instrument but not the rest.
