### ISSUE TITLE
Segmentation fault (crash) on ROCm 5.6.1 on Radeon RX 6700 XT

### ISSUE THREAD

**Issue by kode54** [facebookresearch/demucs#556]
## 🐛 Bug Report

demucs crashes when attempting to split a track using ROCm on an RX 6700 XT.

## To Reproduce

1. On Arch, install ROCm: `pacman -S rocm-opencl-runtime`
2. Install miniconda3
3. `conda create -n py39 python=3.9`
4. `conda activate py39`
5. `pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.6`
6. `pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs`
7. `demucs <path to track 7 of Funeral by Arcade Fire, Wake Up>`

## Expected behavior

demucs should split the track using my GPU.

## Actual Behavior

demucs loads the track, then segfaults.

## Your Environment

- Python and PyTorch version: Python 3.9, torch 2.1.0+rocm5.6
- Operating system and version (desktop or mobile): Arch Linux, linux-cachyos 6.5.7, or linux-drm-next-git 6.6 rc2
- Hardware (gpu or cpu, amount of RAM etc.): AMD Ryzen 7 2700, Radeon RX 6700 XT 12GB

Backtrace:
https://gist.github.com/kode54/1a318cfe6bd2c947a2cc287e5d5d6ac9

**Comment by CarlGao4** [comment]
What does python output?

**Comment by kode54** [comment]
```
% demucs /mnt/storage/fat/Music/Shared/Arcade\ Fire/Funeral/07\ -\ Wake\ Up.flac
Selected model is a bag of 1 models. You will see that many progress bars per track.
Separated tracks will be stored in /home/chris/separated/htdemucs
Separating track /mnt/storage/fat/Music/Shared/Arcade Fire/Funeral/07 - Wake Up.flac
zsh: segmentation fault (core dumped)  demucs /mnt/storage/fat/Music/Shared/Arcade\ Fire/Funeral/07\ -\ Wake\ Up.fla
```

**Comment by CarlGao4** [comment]
Then it's an exception caused by PyTorch, not deluxe
