### ISSUE TITLE
entrenamiento de demucs

### ISSUE THREAD

**Issue by excel77** [facebookresearch/demucs#56]
buenas con todos.....
Acabo de instalar demus en mi pc pero tengo una duda como puedo entrenar a la inteligencia artificial para que pueda mejorar al sacar las pistas de audio...gracias de antemano

**Comment by rokimoki** [comment]
@adefossez he may answers your question

**Comment by adefossez** [comment]
@excel77 training a new model is quite technical. Unless you already have experience with Pytorch and deep learning in general, I would not try to do it. It also requires one or multiple GPUs with 16 to 32GB of RAM.
