### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by mathpopo** [facebookresearch/demucs#560]
when i pip install -U demucs, my torch version is 2.0.1,but i hope it using 1.12,how can i do ? i try to force to install torch 1.12, model cannot match

**Comment by CarlGao4** [comment]
You can run this after installing demucs (only run one of these) (this is for Windows and Linux, not macOS):
```bash
# CUDA 11.6
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116
# CUDA 11.3
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
# CUDA 10.2
pip install torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu102
# CPU only
pip install torch==1.12.1+cpu torchvision==0.13.1+cpu torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cpu
```

**Comment by mathpopo** [comment]
# CUDA 11.6
pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116  
with 

https://github.com/facebookresearch/demucs/blob/main/requirements_minimal.txt

**Comment by CarlGao4** [comment]
What do you mean?

**Comment by mathpopo** [comment]
[environment-cuda.yml](https://github.com/facebookresearch/demucs/blob/main/environment-cuda.yml)   this need ?i mean can i use the [minimal.txt](https://github.com/facebookresearch/demucs/blob/main/requirements_minimal.txt) install?

**Comment by CarlGao4** [comment]
You can install torch first and then install demucs requirements then it won't be upgraded

**Comment by mathpopo** [comment]
thanks ,  i will try

**Comment by CarlGao4** [comment]
requirements.txt or environment.yml are for training demucs

**Comment by mathpopo** [comment]
@CarlGao4 ok, do it.
