### ISSUE TITLE
Using --two-stems with the new API

### ISSUE THREAD

**Issue by UknownGino** [facebookresearch/demucs#567]
## ❓ Questions

Is it possible to use the `--two-stems vocals` option with the new `demucs.api` API?

**Comment by CarlGao4** [comment]
I have no intention to add this feature. Since you could get the separated tensors, you can just do something like this:
```python
origin, separated = separator.separate_tensor(wav)
vocals = separated["vocals"]
no_vocals = origin - vocals
```

**Comment by CarlGao4** [comment]
I just made an example, separating audio file is same as separating tensor

**Comment by UknownGino** [comment]
Thank you, it works! I have just another question, how can I get a progress percentage from the callback dict?

**Comment by CarlGao4** [comment]
You should calculate yourself
A sample is here: https://github.com/CarlGao4/Demucs-Gui/blob/261479139b4357801a8de8574a00333fa34f74a8/GUI/separator.py#L200

**Comment by UknownGino** [comment]
I've been looking at the example since yesterday but I have no clues on what segments, overlap or shifts are... What are the default values I should use?

**Comment by CarlGao4** [comment]
They are the parameters of the separator. Default values of `segment` is defined by model, `shifts` and `overlap` are 0 and 0.25.
You can use these codes to avoid overlap and segment and this won't return `progress=1` when separation finishes which you can implement yourself:
```python
progress = Fraction(0)
progress_per_model = Fraction(1, progress_dict["models"])
progress_per_shift = Fraction(1, max(1, shifts))
progress += progress_per_model * progress_dict["model_idx_in_bag"]
progress_model = Fraction(0)
progress_model += progress_per_shift * progress_dict["shift_idx"]
progress_shift = Fraction(progress_dict["segment_offset"], progress_dict["audio_length"])
progress_shift = min(Fraction(1, 1), progress_shift)
progress_model += progress_per_shift * progress_shift
progress += progress_model * progress_per_model
```

**Comment by UknownGino** [comment]
Thank you so much, it works!
