### ISSUE TITLE
RuntimeError: unexpected EOF, expected 139157335 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by pepe291** [facebookresearch/demucs#57]
Cada vez que trato de usar el comando, me salta este error, y me esta poniendo de los nervios
![Captura](https://user-images.githubusercontent.com/30422621/71015815-83965d00-20f4-11ea-9e1c-9f6182c5a678.PNG)
Añado: Ya lo consegui arreglar, habia que borrar una carpeta, aunque yo he borrado toda la carpeta demucs de la carpeta del usuario

**Comment by Jordan326** [comment]
He tenido el mismo error por varios días, podrías indicar cual carpeta fue la que borraste para que se solucionara?

**Comment by adefossez** [comment]
Can you try deleting `models/demucs.th` and trying again? I should add a fix for that...

**Comment by pepe291** [comment]
> Can you try deleting `models/demucs.th` and trying again? I should add a fix for that...

Don't worry pal, I figured out it was only because the pretrained models failed to download
