### ISSUE TITLE
No module named 'demucs.api'; 'demucs' is not a package

### ISSUE THREAD

**Issue by gillbates** [facebookresearch/demucs#576]
## 🐛 Bug Report

it seemed we cannot import demucs in our own python code?

## To Reproduce

(Write your steps here:)

1. init a new conda env with
```
conda create --name mydemucs python=3.9 -y
```
2, activate conda env
```
conda activate mydemucs
```

3, install the edge version with 
```
python3 -m pip install -U git+https://github.com/facebookresearch/demucs#egg=demucs
```

4, using the following code
```
import demucs.api

if __name__ == '__main__':
     separator = demucs.api.Separator()

```

it shows
```
ModuleNotFoundError: No module named 'demucs.api'; 'demucs' is not a package
```
## Expected behavior

we could import and use demucs api correctly ...

## Actual Behavior

it shows
```
ModuleNotFoundError: No module named 'demucs.api'; 'demucs' is not a package
```

## Your Environment

- Python and PyTorch version:
- python 3.9

- Operating system and version (desktop or mobile):
ubuntu 22.04

- Hardware (gpu or cpu, amount of RAM etc.):
gpu

**Comment by gillbates** [comment]
@CarlGao4 did u ever meet this?

**Comment by CarlGao4** [comment]
1. The official repo is [adefossez/demucs](/adefossez/demucs) now
2. Please run `pip show demucs` and see whether it's correctly installed

**Comment by gillbates** [comment]
@CarlGao4 
```
pip show demucs

Name: demucs
Version: 4.1.0a2
Summary: Music source separation in the waveform domain.
Home-page: https://github.com/facebookresearch/demucs
Author: Alexandre Défossez
Author-email: defossez@fb.com
License: MIT License
Location: /home/xxx/miniconda3/envs/mydemucs/lib/python3.9/site-packages
Requires: dora-search, einops, julius, lameenc, openunmix, pyyaml, torch, torchaudio, tqdm
Required-by: 

```

**Comment by CarlGao4** [comment]
That's so interesting... I can't reproduce. Maybe can you run `ls /home/xxx/miniconda3/envs/mydemucs/lib/python3.9/site-packages/demucs`?

**Comment by gillbates** [comment]
> 

```
ls /home/xxx/miniconda3/envs/mydemucs/lib/python3.9/site-packages/demucs

api.py    audio.py    demucs.py   ema.py       hdemucs.py   __init__.py  pretrained.py  py.typed  repitch.py  separate.py  spec.py    svd.py    transformer.py  wav.py
apply.py  augment.py  distrib.py  evaluate.py  htdemucs.py  __main__.py  __pycache__    remote    repo.py     solver.py    states.py  train.py  utils.py        wdemucs.py

```

it seemed everything is included already.

**Comment by CarlGao4** [comment]
Are you sure you've activated the environment before running your script?

**Comment by gillbates** [comment]
> Are you sure you've activated the environment before running your script?

yes .... already several times ... it could be found even in site-packages in pycharm ...

![CleanShot 2023-12-11 at 23 16 39@2x](https://github.com/facebookresearch/demucs/assets/783547/60ff56e5-fc19-45d8-9a47-b629400c7132)

**Comment by CarlGao4** [comment]
Can you run this:
```Python
import sys
print("\n".join(sys.path))
```

**Comment by gillbates** [comment]
```

Python 3.9.18 (main, Sep 11 2023, 13:41:44)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print("\n".join(sys.path))

/home/xxx/miniconda3/envs/mydemucs/lib/python39.zip
/home/xxx/miniconda3/envs/mydemucs/lib/python3.9
/home/xxx/miniconda3/envs/mydemucs/lib/python3.9/lib-dynload
/home/xxx/miniconda3/envs/mydemucs/lib/python3.9/site-packages
/home/xxx/miniconda3/envs/mydemucs/lib/python3.9/site-packages/proglog-0.1.10-py3.9.egg
```

**Comment by CarlGao4** [comment]
Maybe... You can try importing it like this:
```Python
import demucs
import demucs.api
if __name__ == "__main__":
   ...
```

**Comment by gillbates** [comment]
@CarlGao4 I fixed this by re-install conda instead of miniconda ... thx !!!
