### ISSUE TITLE
Download different Pretrained model

### ISSUE THREAD

**Issue by pepe291** [facebookresearch/demucs#58]
Not a real issue, just I don't know how to download a different env, like extra

**Comment by adefossez** [comment]
What do you mean a different env? A different conda env ?

**Comment by pepe291** [comment]
> What do you mean a different env? A different conda env ?

A different pre trained model, and how to use it, sorry, my bad

**Comment by adefossez** [comment]
Just add `-n demucs_extra` to the command line. For instance if you are using windows
`python.exe -m demucs.separate --dl -n demucs_extra -d cpu "PATH_TO_AUDIO_FILE"`

**Comment by adefossez** [comment]
Closing this issue as it is likely resolved. Feel free to open a new one if you have any problem.
