### ISSUE TITLE
torch version error and not working.

### ISSUE THREAD

**Issue by Len-D** [facebookresearch/demucs#590]
## ❓ Questions

This is my first time using Github. Sorry if my English is poor.

I want to use Hybrid Demucs from Colab, but when I run all three, nothing is output.
When I first ran the first one, I got an error message that the torch version was low, so that may have something to do with it,
When I reloaded the page and re-ran it, there was no error.
Since I don't know Python, I don't know what to do if I download PyTorch 2.2.1.
Can someone please tell me what to do?

```
初めてGithubを使います。英語が拙かったらすみません。

Hybrid Demucs from Colabを使用したいのですが、3つすべてを実行しても何も出力されません。
最初に1つ目の実行をした時、torchのバージョンが低いとエラー文が出たのでそれが関係していそうですが、
ページをリロードして再実行するとエラーは出ませんでした。
Pythonがわからないため、PyTorch2.2.1をダウンロードしてもどうしたらいいのかわかりません。
どなたか教えていただけませんか。
```

**Comment by CarlGao4** [comment]
If you are not familiar with coding, you can use [Demucs-GUI](https://github.com/CarlGao4/Demucs-Gui)

**Comment by Len-D** [comment]
Thanks to you we were able to carry it out!
I really appreciate it, thank you.
