### ISSUE TITLE
Audio Configuration for Optimal Results

### ISSUE THREAD

**Issue by csetanmayjain** [facebookresearch/demucs#592]
## ❓ Audio Configuration for Optimal Results

I used to have audio with different sample rates and channels. I would like to know the best configuration that I should set to get the best results, such as the number of channels, sample rate, and bit rate. Do you have any suggestions on this, and does considering it make a difference in the results or not? 
Thanks.

**Comment by CarlGao4** [comment]
Unless you train your own model, official models will only output dual channels, 44100Hz.
It is suggested to input dual-channel audio only.

**Comment by csetanmayjain** [comment]
Thanks. 
Also, would it be advisable to upsample/downsample the audio to 44100 Hz to get the best results, or can we expect the same results with a different sample rate?

**Comment by CarlGao4** [comment]
It will resample the audio to match the model before separating

**Comment by csetanmayjain** [comment]
Thanks :)
