### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by ThanhPham1987** [facebookresearch/demucs#6]
Hi fb,
Can I use python python 3.6 for this code?
Best regards,
PeterPham

**Comment by adefossez** [comment]
Hi @ThanhPham1987,
I justed merged a pull request from @AppleHolic in order to support Python3.6. Can you try to use the code and let me know if you have any error with your version of Python?

**Comment by ThanhPham1987** [comment]
Hi @adefossez ,
Thank you very much
Best regards,
PeterPham
