### ISSUE TITLE
How can I uninstall the dependencies?

### ISSUE THREAD

**Issue by fritoni** [facebookresearch/demucs#62]
I ran out of space on my hd and the files get corrupted, now when i try to use the conda env update -f environment-cpu.yml again i get 
CondaVerificationError: The package for pytorch located at C:\Users\x\Anaconda3\pkgs\pytorch-1.3.1-py3.7_cuda101_cudnn7_0
appears to be corrupted. The path 'Scripts/convert-onnx-to-caffe2.exe'
specified in the package manifest cannot be found.
I think I just need to re-install but I don't know how, I'm new to conda

**Comment by fritoni** [comment]
I can run activate demucs but when I try to separate i get 
![imagen](https://user-images.githubusercontent.com/24925398/71552362-30a88980-29c1-11ea-9462-13a758130c05.png)

**Comment by Fakenez** [comment]
Did you installed pytorch?

**Comment by fritoni** [comment]
I solved it deleting the pytorch files.
Thank you
