### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by JosepZ** [facebookresearch/demucs#68]
I always get RuntimeError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 2.00 GiB total capacity; 1.43 GiB already allocated; 123.11 MiB free; 23.47 MiB cached).

I think I should use " -d cpu " but I have no idea the sintax to use it.

**Comment by adefossez** [comment]
If you are on windows `python.exe -m demucs.separate -d cpu --dl "FILENAME"`, otherwise `python3 -m demucs.separate -d cpu --dl "FILENAME` ;)

**Comment by JosepZ** [comment]
Worked! THANKS.
