### ISSUE TITLE
Help/Ayuda, Idon´t want to install conda/ No quiero instalar Conda

### ISSUE THREAD

**Issue by Kudakitsune** [facebookresearch/demucs#70]
Hi, i think this isnt a issue, but im new at the plataform, i already have python 3.7 installed n´d dont want to install conda to proced with the initializacion of the code, im using windows, i use the cmd console to run commands, someone knows how to run this code without conda?

Hola, creo que esto no es un problema, pero soy nuevo aqui, ya tengo instalado python 3.7 y no querer instalar conda para inicializar el codigo, uso windows, uso la consola cmd para correr con comandos, alguno conoce como correr este codigo sin contar con conda?

**Comment by adefossez** [comment]
You can look up all the dependencies in the `environment-cpu.yml` file and install them manually with `pip`. Once you have done that you can simply run the commands provided in the README file from the cmd console and it should work.

**Comment by Kudakitsune** [comment]
> 
> 
> You can look up all the dependencies in the `environment-cpu.yml` file and install them manually with `pip`. Once you have done that you can simply run the commands provided in the README file from the cmd console and it should work.

So much thank u bro!!!
