### ISSUE TITLE
Demucs has better separation performance for Children's songs. 

### ISSUE THREAD

**Issue by Seven-Color** [facebookresearch/demucs#71]
Demucs has better separation performance for Children's songs.  Is there any Children's songs in your extra training data?

**Comment by adefossez** [comment]
The default model is trained only with the MusDB dataset. The list of tracks is available there https://github.com/sigsep/website/blob/master/content/datasets/assets/tracklist.csv and it does not include a band called Children.
The `extra` model is trained with a 150 tracks that were specifically produced for Facebook as part of its program to provide free audio for video production on Instagram and Facebook. I could not find an artist called Children in the list of tracks.

**Comment by james34602** [comment]
@adefossez Anyway, do extra 150 tracks are available to be downloaded in somewhere?

**Comment by adefossez** [comment]
@james34602 , the stems haven't been released.
