### ISSUE TITLE
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll

### ISSUE THREAD

**Issue by Andrew-afk** [facebookresearch/demucs#74]
(base) D:\Program>cd demucs

(base) D:\Program\demucs>conda env update -f environment-cpu.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Ran pip subprocess with arguments:
['D:\\Program\\Anaconda\\envs\\demucs\\python.exe', '-m', 'pip', 'install', '-U'
, '-r', 'D:\\Program\\demucs\\condaenv.0z3apytv.requirements.txt']
Pip subprocess output:
Requirement already up-to-date: musdb==0.3.1 in d:\program\anaconda\envs\demucs\
lib\site-packages (from -r D:\Program\demucs\condaenv.0z3apytv.requirements.txt
(line 1)) (0.3.1)
Requirement already up-to-date: museval==0.3.0 in d:\program\anaconda\envs\demuc
s\lib\site-packages (from -r D:\Program\demucs\condaenv.0z3apytv.requirements.tx
t (line 2)) (0.3.0)
Requirement already up-to-date: requests==2.22 in d:\program\anaconda\envs\demuc
s\lib\site-packages (from -r D:\Program\demucs\condaenv.0z3apytv.requirements.tx
t (line 3)) (2.22.0)
Requirement already up-to-date: treetable==0.2.3 in d:\program\anaconda\envs\dem
ucs\lib\site-packages (from -r D:\Program\demucs\condaenv.0z3apytv.requirements.
txt (line 4)) (0.2.3)
Requirement already satisfied, skipping upgrade: soundfile>=0.9.0 in d:\program\
anaconda\envs\demucs\lib\site-packages (from musdb==0.3.1->-r D:\Program\demucs\
condaenv.0z3apytv.requirements.txt (line 1)) (0.10.3.post1)
Requirement already satisfied, skipping upgrade: pyaml in d:\program\anaconda\en
vs\demucs\lib\site-packages (from musdb==0.3.1->-r D:\Program\demucs\condaenv.0z
3apytv.requirements.txt (line 1)) (19.12.0)
Requirement already satisfied, skipping upgrade: tqdm in d:\program\anaconda\env
s\demucs\lib\site-packages (from musdb==0.3.1->-r D:\Program\demucs\condaenv.0z3
apytv.requirements.txt (line 1)) (4.36.1)
Requirement already satisfied, skipping upgrade: stempeg>=0.1.7 in d:\program\an
aconda\envs\demucs\lib\site-packages (from musdb==0.3.1->-r D:\Program\demucs\co
ndaenv.0z3apytv.requirements.txt (line 1)) (0.1.8)
Requirement already satisfied, skipping upgrade: numpy>=1.7 in d:\program\anacon
da\envs\demucs\lib\site-packages (from musdb==0.3.1->-r D:\Program\demucs\condae
nv.0z3apytv.requirements.txt (line 1)) (1.17.3)
Requirement already satisfied, skipping upgrade: simplejson in d:\program\anacon
da\envs\demucs\lib\site-packages (from museval==0.3.0->-r D:\Program\demucs\cond
aenv.0z3apytv.requirements.txt (line 2)) (3.17.0)
Requirement already satisfied, skipping upgrade: jsonschema in d:\program\anacon
da\envs\demucs\lib\site-packages (from museval==0.3.0->-r D:\Program\demucs\cond
aenv.0z3apytv.requirements.txt (line 2)) (3.2.0)
Requirement already satisfied, skipping upgrade: scipy in d:\program\anaconda\en
vs\demucs\lib\site-packages (from museval==0.3.0->-r D:\Program\demucs\condaenv.
0z3apytv.requirements.txt (line 2)) (1.3.1)
Requirement already satisfied, skipping upgrade: pandas>=0.25.0 in d:\program\an
aconda\envs\demucs\lib\site-packages (from museval==0.3.0->-r D:\Program\demucs\
condaenv.0z3apytv.requirements.txt (line 2)) (0.25.3)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,
>=1.21.1 in d:\program\anaconda\envs\demucs\lib\site-packages (from requests==2.
22->-r D:\Program\demucs\condaenv.0z3apytv.requirements.txt (line 3)) (1.25.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in d:\progra
m\anaconda\envs\demucs\lib\site-packages (from requests==2.22->-r D:\Program\dem
ucs\condaenv.0z3apytv.requirements.txt (line 3)) (2019.11.28)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in d:\pro
gram\anaconda\envs\demucs\lib\site-packages (from requests==2.22->-r D:\Program\
demucs\condaenv.0z3apytv.requirements.txt (line 3)) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in d:\program\an
aconda\envs\demucs\lib\site-packages (from requests==2.22->-r D:\Program\demucs\
condaenv.0z3apytv.requirements.txt (line 3)) (2.8)
Requirement already satisfied, skipping upgrade: cffi>=1.0 in d:\program\anacond
a\envs\demucs\lib\site-packages (from soundfile>=0.9.0->musdb==0.3.1->-r D:\Prog
ram\demucs\condaenv.0z3apytv.requirements.txt (line 1)) (1.13.2)
Requirement already satisfied, skipping upgrade: PyYAML in d:\program\anaconda\e
nvs\demucs\lib\site-packages (from pyaml->musdb==0.3.1->-r D:\Program\demucs\con
daenv.0z3apytv.requirements.txt (line 1)) (5.3)
Requirement already satisfied, skipping upgrade: pyrsistent>=0.14.0 in d:\progra
m\anaconda\envs\demucs\lib\site-packages (from jsonschema->museval==0.3.0->-r D:
\Program\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (0.15.7)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in d:\program\ana
conda\envs\demucs\lib\site-packages (from jsonschema->museval==0.3.0->-r D:\Prog
ram\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (19.3.0)
Requirement already satisfied, skipping upgrade: six>=1.11.0 in d:\program\anaco
nda\envs\demucs\lib\site-packages (from jsonschema->museval==0.3.0->-r D:\Progra
m\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (1.14.0)
Requirement already satisfied, skipping upgrade: importlib-metadata; python_vers
ion < "3.8" in d:\program\anaconda\envs\demucs\lib\site-packages (from jsonschem
a->museval==0.3.0->-r D:\Program\demucs\condaenv.0z3apytv.requirements.txt (line
 2)) (1.4.0)
Requirement already satisfied, skipping upgrade: setuptools in d:\program\anacon
da\envs\demucs\lib\site-packages (from jsonschema->museval==0.3.0->-r D:\Program
\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (45.0.0.post20200113)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in d:\program\anac
onda\envs\demucs\lib\site-packages (from pandas>=0.25.0->museval==0.3.0->-r D:\P
rogram\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (2019.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.1 in d:\pr
ogram\anaconda\envs\demucs\lib\site-packages (from pandas>=0.25.0->museval==0.3.
0->-r D:\Program\demucs\condaenv.0z3apytv.requirements.txt (line 2)) (2.8.1)
Requirement already satisfied, skipping upgrade: pycparser in d:\program\anacond
a\envs\demucs\lib\site-packages (from cffi>=1.0->soundfile>=0.9.0->musdb==0.3.1-
>-r D:\Program\demucs\condaenv.0z3apytv.requirements.txt (line 1)) (2.19)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in d:\program\anacond
a\envs\demucs\lib\site-packages (from importlib-metadata; python_version < "3.8"
->jsonschema->museval==0.3.0->-r D:\Program\demucs\condaenv.0z3apytv.requirement
s.txt (line 2)) (1.0.0)
Requirement already satisfied, skipping upgrade: more-itertools in d:\program\an
aconda\envs\demucs\lib\site-packages (from zipp>=0.5->importlib-metadata; python
_version < "3.8"->jsonschema->museval==0.3.0->-r D:\Program\demucs\condaenv.0z3a
pytv.requirements.txt (line 2)) (8.1.0)

#
# To activate this environment, use
#
#     $ conda activate demucs
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) D:\Program\demucs>conda activate demucs

(demucs) D:\Program\demucs>python -m demucs.separate -d cpu --dl D:\Program\samp
le.mp3
INTEL MKL ERROR: Operating system cannot execute %1. mkl_intel_thread.dll
.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

(demucs) D:\Program\demucs>set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1

(demucs) D:\Program\demucs>python -m demucs.separate -d cpu --dl D:\Program\samp
le.mp3
INTEL MKL ERROR: Operating system cannot execute  %1. mkl_intel_thread.dll
.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

The anaconda folder is in D:/Program/Anaconda
I uninstalled all, reinstalled demucs and Anaconda, restarted my PC but keeps giving me this error...

**Comment by Gringo541** [comment]
hola, ami me pasa lo mismo, pero fue de un dia a otro, encontraste la solucion?

**Comment by Gringo541** [comment]
Finalmente encontré una solución, desde este enlace:
https://stackoverflow.com/questions/53026985/the-ordinal-242-could-not-be-located-in-the-dynamic-link-library-anaconda3-libra
Básicamente , hay dos archivos adicionales que deben eliminarse: 'System32 \ libiomp5md.dll' y 'SysWOW64 \ libiomp5md.dll'. Después de eliminar estos dos en su carpeta respectiva, los paquetes numpy y otros se cargan correctamente.

**Comment by Gringo541** [comment]
avisame si te funciono!

**Comment by Andrew-afk** [comment]
> hola, ami me pasa lo mismo, pero fue de un dia a otro, encontraste la solucion?

No :(

**Comment by Andrew-afk** [comment]
> Finalmente encontré una solución, desde este enlace:
> https://stackoverflow.com/questions/53026985/the-ordinal-242-could-not-be-located-in-the-dynamic-link-library-anaconda3-libra
> Básicamente , hay dos archivos adicionales que deben eliminarse: 'System32 \ libiomp5md.dll' y 'SysWOW64 \ libiomp5md.dll'. Después de eliminar estos dos en su carpeta respectiva, los paquetes numpy y otros se cargan correctamente.

Isnt that dangerous? Did you do that?

**Comment by Gringo541** [comment]
si, hice eso y me anduvo la solucion la saque de un foro de la misma pagina para que te quedes tranquilo:
https://github.com/ContinuumIO/anaconda-issues/issues/10213#issuecomment-468964895

**Comment by Andrew-afk** [comment]
> si, hice eso y me anduvo la solucion la saque de un foro de la misma pagina para que te quedes tranquilo:
> [ContinuumIO/anaconda-issues#10213 (comment)](https://github.com/ContinuumIO/anaconda-issues/issues/10213#issuecomment-468964895)

Okay thanks :)
I will try it and comment if worked

**Comment by Gringo541** [comment]
recuerda que si te funciono, debes cerrar el tema

**Comment by Andrew-afk** [comment]
> recuerda que si te funciono, debes cerrar el tema

I deleted these files and... Windows failed at boot and i downloaded the iso file again with a very slow internet... So now i'll try to run demucs again..

**Comment by Andrew-afk** [comment]
> > recuerda que si te funciono, debes cerrar el tema
> 
> I deleted these files and... Windows failed at boot so i downloaded the iso file again with a very slow internet... So now i'll try to run demucs again..

NOW IT WORKS, THANKS <3

**Comment by MarckJ7** [comment]
Funciono Perfectamente!
