### ISSUE TITLE
Windows - CPU mode memory allocation issue

### ISSUE THREAD

**Issue by Katanarama666** [facebookresearch/demucs#80]
I've installed all the way through the process over a windows 7 machine, I got the pytorch issue but installed successfully and then when I ran the final command I got the memory allocation issue.

![image](https://user-images.githubusercontent.com/60491887/73500438-46c2b480-4388-11ea-8057-748244a597de.png)

I tried several commands regarding the CPU yml file forcing and still getting that one,

![image](https://user-images.githubusercontent.com/60491887/73500640-dd8f7100-4388-11ea-987a-d91e413f0ab3.png)

My specs:

OS: Win 7 Pro (x64)
Processor: AMD A8-5550M APU with Radeon(tm) Graphics 2.10 Ghz
RAM: 8 GB

**Comment by adefossez** [comment]
Thats weird, 8GB should be more than enough. If you have any other app running, try again after stopping them. Also try to update the repository, delete the files already downloaded in `models`.
Not sure if any can help.

**Comment by Katanarama666** [comment]
Hello,

I got the final solution, I rebooted and closed everything but the program and closed any unnecessary process through the task manager and then ir worked.

Thanks for the support.
