### ISSUE TITLE
CUDA Out of Memory

### ISSUE THREAD

**Issue by capgenemy** [facebookresearch/demucs#9]
Hi!

Everytime I run this command in Windows: 
python.exe -m demucs.separate --dl -n demucs NAMEOFTHEFILE.mp3

i'm facing this error message:
"RuntimeError: CUDA out of memory. Tried to allocate 158.00 MiB (GPU 0; 2.00 GiB total capacity; 1.12 GiB already allocated; 119.35 MiB free; 20.06 MiB cached)"

Do you know what can I do to solve it?

Thank you so much,

**Comment by adefossez** [comment]
Hi @capgenemy , you have too little memory on your GPU. You can try using `tasnet`, as the model of it is much smaller (with `-n tasnet`). Or you can do `-d cpu` to ignore the GPU and run on CPU.

**Comment by starg09** [comment]
@adefossez was just making some tests and found the same issue with a 6 GB GPU (a 1060). Is there a minimum memory requirement for using CUDA instead of CPU with demucs? Would be nice to have in the readme :)

**Comment by capgenemy** [comment]
It worked with "-d cpu". Thank you so much!!!

**Comment by rokimoki** [comment]
Seems that worked with "-d cpu", but I have the same problem using nvidia 1060 gtx 6gb.

**Comment by adefossez** [comment]
Hey guys, sorry for my late reply. `demucs` will require a fair bit of memory, just loading the model requires 4GB of RAM. Overall, it seems to require just above 6GB of memory. I'm retraining a smaller model in case that would be useful for you guys, but for now CPU generation is the way to go.

**Comment by essammubashir474** [comment]
where do i write -d cpu?
