### ISSUE TITLE
_error_catcher

### ISSUE THREAD

**Issue by MarginalCutz** [facebookresearch/demucs#90]
Cuando intento separar una canción, se pone a descargar los archivos y casi siempre cerca del 60% me arroja los errores que se pueden ver en la imagen.

Ayuuudaaaa, por favor :c

![imagen](https://user-images.githubusercontent.com/61678187/75648731-b8b04700-5c2f-11ea-9c0c-dba53d7b24bb.png)

**Comment by adefossez** [comment]
Can you try to run
`python.exe -m demucs.separate -d cpu --dl -n light "PATH_TO_AUDIO_FILE_1"` (notice the `-n light` extra)? This is a smaller model and it has higher chances to get through. It seems that your connection is too unstable and keep being lost while downloading the model.

**Comment by MarginalCutz** [comment]
Muchas gracias. Después de un intento fallido, me funcionó.
