### ISSUE TITLE
How to work with python3.6

### ISSUE THREAD

**Issue by panxin801** [facebookresearch/demucs#95]
When training, I notice the following line
from dataclasses import dataclass, field
in __main__.py can't be loaded, because I miss python 3.7. But I want to ask if there is a chance to work with python 3.6. Because I have a full environment with python 3.6 so I don't need start from scratch.

**Comment by adefossez** [comment]
Hey @panxin801 , sadly there is no plan to port this to python3.6 You can try installing this package https://github.com/ericvsmith/dataclasses that provides the feature for python3.6 but there might be other places in the training code that require python3.7.

**Comment by panxin801** [comment]
Oh thank you for reply @adefossez , and I have installed this lib and try to training the model, if that work i will close this issue myself . Thank you very much
